In [1]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_excel('appartments.xlsx').drop(22)

In [3]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."

In [4]:
df.shape

(246, 7)

In [5]:
df.iloc[2].NearbyLocations

"['AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56']"

In [6]:
df.iloc[2].LocationAdvantages

"{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}"

In [7]:
df.iloc[1].PriceDetails

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}"

In [8]:
df.iloc[2].TopFacilities

"['Terrace Garden', 'Gazebo', 'Fountain', 'Amphitheatre', 'Party Lawn', 'Basketball Court', 'Badminton Court', 'Yoga/Meditation Area', 'Indoor Games']"

In [9]:
df[['PropertyName','TopFacilities']]['TopFacilities'][0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

In [10]:
def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [11]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"[Terrace Garden, Gazebo, Fountain, Amphitheatr..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Volley Ball Court, Aerobics Ce..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"[Mini Theatre, Doctor on Call, Concierge Servi..."

In [12]:
df['FacilitiesStr'] = df['TopFacilities'].apply(' '.join)

In [13]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities,FacilitiesStr
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete...",Swimming Pool Salon Restaurant Spa Cafeteria S...
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden...",Bowling Alley Mini Theatre Manicured Garden Sw...
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"[Terrace Garden, Gazebo, Fountain, Amphitheatr...",Terrace Garden Gazebo Fountain Amphitheatre Pa...
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Volley Ball Court, Aerobics Ce...",Swimming Pool Volley Ball Court Aerobics Centr...
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"[Mini Theatre, Doctor on Call, Concierge Servi...",Mini Theatre Doctor on Call Concierge Service ...

In [14]:
df['FacilitiesStr'][0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

In [15]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [16]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [17]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.18809342, 0.18809342,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16873099, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27811185, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17445059, 0.17445059,
       0.15589841, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16355699, 0.29372893, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18084455, 0.18084455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17445059, 0.        , 0.24773259, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06440364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2659983 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12932284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21010446, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16522746,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25610081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15177345,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21412748, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14918792,
       0.29372893, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16355699, 0.16355699, 0.        ,
       0.        , 0.        , 0.06493586, 0.06493586, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [18]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [19]:
cosine_sim1.shape

(246, 246)

In [21]:
def recommend_properties(property_name, cosine_sim=cosine_sim1):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 5 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 5 most similar properties
    return recommendations_df

In [22]:
recommend_properties("DLF The Arbour")

           PropertyName             SimilarityScore
64      Ace Palm Floors   (63, 0.45293820624419556)
217         Yashika 104  (216, 0.41996063229267827)
93       JMS The Nation    (92, 0.4166584649363288)
154       India Rashtra  (153, 0.39895423468019414)
0    Smartworld One DXP      (0, 0.388850461994329)

In [26]:
df[['PropertyName','PriceDetails']]['PriceDetails'][6]

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,015 - 2,150 sq.ft.', 'price-range': '₹ 1.53 - 1.85 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,250 - 2,675 sq.ft.', 'price-range': '₹ 1.71 - 2.46 Cr'}}"

In [27]:
import pandas as pd
import json

# Load the dataset
df_appartments = pd.read_excel('appartments.xlsx').drop(22)

# Function to parse and extract the required features from the PriceDetails column
def refined_parse_modified_v2(detail_str):
    try:
        details = json.loads(detail_str.replace("'", "\""))
    except:
        return {}

    extracted = {}
    for bhk, detail in details.items():
        # Extract building type
        extracted[f'building type_{bhk}'] = detail.get('building_type')

        # Parsing area details
        area = detail.get('area', '')
        area_parts = area.split('-')
        if len(area_parts) == 1:
            try:
                value = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area low {bhk}'] = value
                extracted[f'area high {bhk}'] = value
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
        elif len(area_parts) == 2:
            try:
                extracted[f'area low {bhk}'] = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area high {bhk}'] = float(area_parts[1].replace(',', '').replace(' sq.ft.', '').strip())
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
                
                        # Parsing price details
        price_range = detail.get('price-range', '')
        price_parts = price_range.split('-')
        if len(price_parts) == 2:
            try:
                extracted[f'price low {bhk}'] = float(price_parts[0].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                extracted[f'price high {bhk}'] = float(price_parts[1].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                if 'L' in price_parts[0]:
                    extracted[f'price low {bhk}'] /= 100
                if 'L' in price_parts[1]:
                    extracted[f'price high {bhk}'] /= 100
            except:
                extracted[f'price low {bhk}'] = None
                extracted[f'price high {bhk}'] = None

    return extracted
# Apply the refined parsing and generate the new DataFrame structure
data_refined = []

for _, row in df_appartments.iterrows():
    features = refined_parse_modified_v2(row['PriceDetails'])
    
    # Construct a new row for the transformed dataframe
    new_row = {'PropertyName': row['PropertyName']}
    
    # Populate the new row with extracted features
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        new_row[f'building type_{config}'] = features.get(f'building type_{config}')
        new_row[f'area low {config}'] = features.get(f'area low {config}')
        new_row[f'area high {config}'] = features.get(f'area high {config}')
        new_row[f'price low {config}'] = features.get(f'price low {config}')
        new_row[f'price high {config}'] = features.get(f'price high {config}')
    
    data_refined.append(new_row)

df_final_refined_v2 = pd.DataFrame(data_refined).set_index('PropertyName')

In [28]:
df_final_refined_v2['building type_Land'] = df_final_refined_v2['building type_Land'].replace({'':'Land'})

In [33]:
df['PriceDetails'][0]

"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}"

In [30]:
df_final_refined_v2

,building type_1 BHK,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,building type_2 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,...,building type_1 RK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,building type_Land,area low Land,area high Land,price low Land,price high Land
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,None,NaN,NaN,NaN,NaN,Apartment,1370.0,1370.0,2.0000,2.40,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
M3M Crown,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,Land,500.0,4329.0,2.05,41.13
Sobha City,None,NaN,NaN,NaN,NaN,Apartment,1381.0,1692.0,1.5500,3.21,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Signature Global City 93,None,NaN,NaN,NaN,NaN,Independent Floor,981.0,1118.0,0.9301,1.06,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,None,NaN,NaN,NaN,NaN,Apartment,964.0,964.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Pyramid Urban Homes 2,Apartment,335.0,398.0,23.45,0.2786,Apartment,500.0,625.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Satya The Hermitage,None,NaN,NaN,NaN,NaN,Apartment,1450.0,1450.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
BPTP Spacio,None,NaN,NaN,NaN,NaN,Apartment,1000.0,1079.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
SS The Coralwood,None,NaN,NaN,NaN,NaN,Apartment,1320.0,1425.0,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [31]:
df_final_refined_v2.columns

Index(['building type_1 BHK', 'area low 1 BHK', 'area high 1 BHK',
       'price low 1 BHK', 'price high 1 BHK', 'building type_2 BHK',
       'area low 2 BHK', 'area high 2 BHK', 'price low 2 BHK',
       'price high 2 BHK', 'building type_3 BHK', 'area low 3 BHK',
       'area high 3 BHK', 'price low 3 BHK', 'price high 3 BHK',
       'building type_4 BHK', 'area low 4 BHK', 'area high 4 BHK',
       'price low 4 BHK', 'price high 4 BHK', 'building type_5 BHK',
       'area low 5 BHK', 'area high 5 BHK', 'price low 5 BHK',
       'price high 5 BHK', 'building type_6 BHK', 'area low 6 BHK',
       'area high 6 BHK', 'price low 6 BHK', 'price high 6 BHK',
       'building type_1 RK', 'area low 1 RK', 'area high 1 RK',
       'price low 1 RK', 'price high 1 RK', 'building type_Land',
       'area low Land', 'area high Land', 'price low Land', 'price high Land'],
      dtype='object')

In [34]:
categorical_columns = df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [35]:
categorical_columns

['building type_1 BHK',
 'building type_2 BHK',
 'building type_3 BHK',
 'building type_4 BHK',
 'building type_5 BHK',
 'building type_6 BHK',
 'building type_1 RK',
 'building type_Land']

In [36]:
ohe_df = pd.get_dummies(df_final_refined_v2, columns=categorical_columns, drop_first=True)

In [37]:
ohe_df.fillna(0,inplace=True)

In [38]:
ohe_df

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0.0,0.0,0.00,0.0000,1370.0,1370.0,2.0000,2.40,1850.0,2050.0,...,False,False,False,False,False,False,False,False,False,False
M3M Crown,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1605.0,2170.0,...,False,False,False,False,False,False,False,False,False,False
Adani Brahma Samsara Vilasa,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1800.0,3150.0,...,False,False,True,False,False,True,False,False,False,False
Sobha City,0.0,0.0,0.00,0.0000,1381.0,1692.0,1.5500,3.21,1711.0,2343.0,...,False,False,False,False,False,False,False,False,False,False
Signature Global City 93,0.0,0.0,0.00,0.0000,981.0,1118.0,0.9301,1.06,1235.0,1530.0,...,True,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.0,0.0,0.00,0.0000,964.0,964.0,0.0000,0.00,1127.0,1127.0,...,False,False,False,False,False,False,False,False,False,False
Pyramid Urban Homes 2,335.0,398.0,23.45,0.2786,500.0,625.0,0.0000,0.00,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
Satya The Hermitage,0.0,0.0,0.00,0.0000,1450.0,1450.0,0.0000,0.00,1991.0,1991.0,...,False,False,False,False,False,False,False,False,False,False
BPTP Spacio,0.0,0.0,0.00,0.0000,1000.0,1079.0,0.0000,0.00,1225.0,1865.0,...,False,False,False,False,False,False,False,False,False,False
SS The Coralwood,0.0,0.0,0.00,0.0000,1320.0,1425.0,0.0000,0.00,1750.0,1890.0,...,False,False,False,False,False,False,False,False,False,False

In [39]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
ohe_df_normalized = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=ohe_df.index)

In [40]:
ohe_df_normalized.head()

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,...,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-0.252266,-0.169584,-0.105197,-0.082332,1.223499,1.020101,-0.173712,1.158423,0.553787,0.370864,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
M3M Crown,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.293086,0.472749,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Adani Brahma Samsara Vilasa,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.500583,1.304803,...,-0.289310,-0.063888,2.683282,-0.063888,-0.171139,3.924283,-0.236208,-0.111111,-0.216353,-0.063888
Sobha City,-0.252266,-0.169584,-0.105197,-0.082332,1.240497,1.470610,-0.198425,1.680336,0.405879,0.619632,...,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Signature Global City 93,-0.252266,-0.169584,-0.105197,-0.082332,0.622383,0.667529,-0.232468,0.295011,-0.100626,-0.070634,...,3.456497,-0.063888,2.683282,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix
cosine_sim2 = cosine_similarity(ohe_df_normalized)

In [42]:
cosine_sim2.shape

(246, 246)

In [43]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim2[ohe_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = ohe_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('M3M Golf Hills')

                PropertyName  SimilarityScore
0    AIPL The Peaceful Homes         0.955462
1         Smartworld One DXP         0.954670
2             Unitech Escape         0.953092
3                M3M Capital         0.951156
4                 BPTP Terra         0.943128
..                       ...              ...
240              Golden Park        -0.522391
241      Satya Merano Greens        -0.523660
242       ROF Normanton Park        -0.525129
243          BPTP Green Oaks        -0.525286
244           JMS The Nation        -0.526287

[245 rows x 2 columns]

In [44]:
df[['PropertyName','LocationAdvantages']]['LocationAdvantages'][0]

"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"

In [45]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [360]:
import ast
# Extract distances for each location
location_matrix = {}
for index, row in df.iterrows():
    distances = {}
    for location, distance in ast.literal_eval(row['LocationAdvantages']).items():
        distances[location] = distance_to_meters(distance)
    location_matrix[index] = distances

# Convert the dictionary to a dataframe
location_df = pd.DataFrame.from_dict(location_matrix, orient='index')

# Display the first few rows
location_df.head()

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
0,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,NaN,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,5300.0,NaN,NaN,NaN,2500.0,8800.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,NaN,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,5500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [361]:
location_df.columns[10:50]

Index(['Indira Gandhi International Airport', 'Hamoni Golf Camp',
       'Fun N Food Waterpark', 'Accenture DDC5', 'DPSG Palam Vihar Gurugram',
       'Park Hospital, Palam Vihar', 'Palam Vihar Halt Railway Station',
       'Dwarka Sector 21 Metro Station', 'Dwarka Expressway',
       'Fun N Food Water Park', 'Tau DeviLal Sports Complex', 'Hyatt Place',
       'Altrade Business Centre', 'AIPL Business Club Sector 62',
       'Heritage Xperiential Learning School', 'CK Birla Hospital',
       'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56',
       'De Adventure Park', 'Golf Course Ext Rd',
       'DoubleTree by Hilton Hotel Gurgaon',
       'KIIT College of Engineering Sohna Road', 'Mehrauli-Gurgaon Road',
       'Nirvana Rd', 'TERI Golf Course', 'The Shikshiyan School', 'WTC Plaza',
       'Luxus Haritma Resort', 'BSF Golf Course', 'Rions Hospital', 'Gurgaon',
       'Dwarka Sector 21', 'Nehru Stadium', 'Fun N Food WaterPark',
       'IGI Airport', 'Vasant Kunj', 'Pranavananda Int. School',
       'DLF Site central office', 'Holiday Inn Gurugram Sector 90',
       'Krishna Hospital'],
      dtype='object')

In [362]:
location_df.index = df.PropertyName

In [363]:
location_df.head()

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
M3M Crown,550.0,NaN,NaN,NaN,NaN,6700.0,3800.0,NaN,NaN,7500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,5300.0,NaN,NaN,NaN,2500.0,8800.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sobha City,1500.0,NaN,NaN,NaN,6500.0,6700.0,5100.0,NaN,NaN,8200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Signature Global City 93,NaN,NaN,NaN,5500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [364]:
location_df.fillna(54000,inplace=True)

In [365]:
location_df

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,800.0,2500.0,3100.0,3100.0,4900.0,5400.0,1200.0,7700.0,7200.0,7400.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Crown,550.0,54000.0,54000.0,54000.0,54000.0,6700.0,3800.0,54000.0,54000.0,7500.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Adani Brahma Samsara Vilasa,5300.0,54000.0,54000.0,54000.0,2500.0,8800.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Sobha City,1500.0,54000.0,54000.0,54000.0,6500.0,6700.0,5100.0,54000.0,54000.0,8200.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Signature Global City 93,54000.0,54000.0,54000.0,5500.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Pyramid Urban Homes 2,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Satya The Hermitage,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
BPTP Spacio,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
SS The Coralwood,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,...,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0

In [53]:
from sklearn.preprocessing import StandardScaler
# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe

location_df_normalized = pd.DataFrame(scaler.fit_transform(location_df), columns=location_df.columns, index=location_df.index)

In [54]:
location_df_normalized

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,...,MCC Cricket Ground Dhankot,The Shri Ram School Aravali,Taj City Centre Gurugram,Minda Industries Corporate Office,"Rampura Flyover, Naurangpur Rd",Manesar toll plaza - Kherki Daula,"Imt Manesar, Gurugram",Holiday Inn,Sector 84 Road,Skyview Corporate Park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-7.960979,-15.652476,-15.652476,-3.149592,-2.966108,-3.147217,-3.726615,-10.231739,-15.652476,-6.023233,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
M3M Crown,-7.998993,0.063888,0.063888,0.328277,0.368941,-3.054053,-3.529275,0.090308,0.063888,-6.009941,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Adani Brahma Samsara Vilasa,-7.276720,0.063888,0.063888,0.328277,-3.129124,-2.903557,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Sobha City,-7.854539,0.063888,0.063888,0.328277,-2.857430,-3.054053,-3.430606,0.090308,0.063888,-5.916893,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Signature Global City 93,0.128476,0.063888,0.063888,-2.985606,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Pyramid Urban Homes 2,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
Satya The Hermitage,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
BPTP Spacio,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888
SS The Coralwood,0.128476,0.063888,0.063888,0.328277,0.368941,0.335688,0.280891,0.090308,0.063888,0.171073,...,0.0,0.063888,0.063888,0.063888,0.063888,0.063888,0.063888,0.0,0.063888,0.063888

In [55]:
cosine_sim3 = cosine_similarity(location_df_normalized)

In [56]:
cosine_sim3.shape

(246, 246)

In [60]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 30*cosine_sim1 + 20*cosine_sim2 + 8*cosine_sim3
    #cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('Ireo Victory Valley')

               PropertyName  SimilarityScore
0    Pioneer Urban Presidia        28.021460
1        Ambience Creacions        27.787913
2             DLF The Crest        24.205986
3             Pioneer Araya        23.415308
4    Silverglades The Melia        21.007840
..                      ...              ...
240          JMS The Nation       -14.735656
241     Shree Vardhman City       -14.888274
242          JMS Prime Land       -15.082229
243       Vatika Aspiration       -15.099679
244           Corona Greens       -15.673834

[245 rows x 2 columns]

In [58]:
(3*cosine_sim3 + 5*cosine_sim2 + 6*cosine_sim1).shape

(246, 246)

In [61]:
import pickle

with open('cosine_sim1.pkl', 'wb') as file:
    pickle.dump(cosine_sim1, file)

In [62]:

with open('cosine_sim2.pkl', 'wb') as file:
    pickle.dump(cosine_sim2, file)

In [63]:

with open('cosine_sim3.pkl', 'wb') as file:
    pickle.dump(cosine_sim3, file)

In [65]:
# location_df

In [67]:

with open('location_df.pkl', 'wb') as file:
    pickle.dump(location_df, file)

In [75]:
location_df.columns[0:30]

Index(['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar',
       'Park Hospital', 'Gurgaon Railway Station', 'The NorthCap University',
       'Dwarka Expy', 'Hyatt Place Gurgaon Udyog Vihar',
       'Dwarka Sector 21, Metro Station', 'Pacific D21 Mall',
       'Indira Gandhi International Airport', 'Hamoni Golf Camp',
       'Fun N Food Waterpark', 'Accenture DDC5', 'DPSG Palam Vihar Gurugram',
       'Park Hospital, Palam Vihar', 'Palam Vihar Halt Railway Station',
       'Dwarka Sector 21 Metro Station', 'Dwarka Expressway',
       'Fun N Food Water Park', 'Tau DeviLal Sports Complex', 'Hyatt Place',
       'Altrade Business Centre', 'AIPL Business Club Sector 62',
       'Heritage Xperiential Learning School', 'CK Birla Hospital',
       'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56',
       'De Adventure Park', 'Golf Course Ext Rd'],
      dtype='object')

In [159]:
#sorted(location_df.columns.to_list())

In [118]:
#location_df[["Aapno Ghar","AapnoGhar"]].sample(10)

In [367]:
location_df[location_df["Aapno Ghar"]+location_df["AapnoGhar"] < 100000][["Aapno Ghar","AapnoGhar"]]

                                  Aapno Ghar  AapnoGhar
PropertyName
Emaar MGF Emerald Floors Premier     54000.0     6000.0
M3M Sierra 68                         9400.0    54000.0
Pioneer Urban Presidia               54000.0     3600.0
Emaar The Palm Springs               54000.0     9600.0

In [368]:
location_df.loc["M3M Sierra 68"]["AapnoGhar"]

54000.0

In [369]:
location_df.at["M3M Sierra 68", "AapnoGhar"] = 9400

In [370]:
location_df[location_df["AIPL Business Club"]+location_df["AIPL Business Club Sector 62"] < 100000][["AIPL Business Club","AIPL Business Club Sector 62"]]

                   AIPL Business Club  AIPL Business Club Sector 62
PropertyName
ROF Insignia Park             54000.0                        2700.0
Corona Optus                   2200.0                       54000.0

In [371]:
location_df.at["ROF Insignia Park", "AIPL Business Club"] = 2700.0

In [372]:
location_df[location_df["Aarvy Healthcare"]+location_df["Aarvy Healthcare Hospital"] +location_df["Aarvy Hospital"] +location_df["Aarvy Healthcare Super Speciality"] < 216000][["Aarvy Healthcare","Aarvy Healthcare Hospital","Aarvy Hospital","Aarvy Healthcare Super Speciality"]]

,Aarvy Healthcare,Aarvy Healthcare Hospital,Aarvy Hospital,Aarvy Healthcare Super Speciality
PropertyName,,,,
International City by SOBHA Phase 2,54000.0,54000.0,8800.0,54000.0
Ireo Victory Valley,54000.0,54000.0,2500.0,54000.0
DLF Park Place,54000.0,54000.0,54000.0,4700.0
Central Park Flower Valley,54000.0,54000.0,54000.0,8000.0
Emaar MGF Emerald Floors Premier,54000.0,54000.0,3900.0,54000.0
M3M Sierra 68,3200.0,54000.0,54000.0,54000.0
Tulip Violet,54000.0,2300.0,54000.0,54000.0
Bestech Park View Grand Spa,54000.0,54000.0,3200.0,54000.0
Shree Vardhman Victoria,54000.0,3500.0,54000.0,54000.0
Shree Vardhman Flora,4700.0,54000.0,54000.0,54000.0
BPTP Fortuna,54000.0,3600.0,54000.0,54000.0
Godrej Oasis,4000.0,54000.0,54000.0,54000.0
Golden Park,54000.0,4000.0,54000.0,54000.0
Umang Winter Hills,54000.0,54000.0,54000.0,2900.0
Silverglades Hightown Residences,54000.0,54000.0,54000.0,1800.0
Mahindra Aura,54000.0,54000.0,54000.0,4100.0

In [373]:
location_df.at["International City by SOBHA Phase 2", "Aarvy Healthcare Super Speciality"] = 8800.0
location_df.at["Ireo Victory Valley", "Aarvy Healthcare Super Speciality"] = 2500.0
location_df.at["Emaar MGF Emerald Floors Premier", "Aarvy Healthcare Super Speciality"] = 3900.0
location_df.at["M3M Sierra 68", "Aarvy Healthcare Super Speciality"] = 3200.0
location_df.at["Tulip Violet", "Aarvy Healthcare Super Speciality"] = 2300.0
location_df.at["Bestech Park View Grand Spa", "Aarvy Healthcare Super Speciality"] = 3200.0
location_df.at["Shree Vardhman Victoria", "Aarvy Healthcare Super Speciality"] = 3500.0
location_df.at["Shree Vardhman Flora", "Aarvy Healthcare Super Speciality"] = 4700.0
location_df.at["BPTP Fortuna", "Aarvy Healthcare Super Speciality"] = 3600.0
location_df.at["Godrej Oasis", "Aarvy Healthcare Super Speciality"] = 4000.0
location_df.at["Golden Park", "Aarvy Healthcare Super Speciality"] = 4000.0

In [374]:
location_df[location_df["Adarsh Senior Secondary School"]+location_df["Adarsh public school,Garhi Harsaru"] < 108000][["Adarsh Senior Secondary School","Adarsh public school,Garhi Harsaru"]]

,Adarsh Senior Secondary School,"Adarsh public school,Garhi Harsaru"
PropertyName,,
Orchid IVY Floors,2000.0,54000.0

In [375]:
location_df[location_df["Airia Mall"]+location_df["Airia Mall Sector 68"] < 108000][["Airia Mall","Airia Mall Sector 68"]]

                                         Airia Mall  Airia Mall Sector 68
PropertyName
Mahindra Luminare                            3900.0               54000.0
Godrej Nature Plus Serenity                  4600.0               54000.0
Emaar Emerald Hills                          3900.0               54000.0
Signature Global City 37D Ph 2              17000.0               54000.0
DLF The Camellias                           11600.0               54000.0
Central Park Flower Valley Mikasa Plots     15800.0               54000.0
Ramprastha Primera                           4600.0               54000.0
DLF New Town Heights 2                       3700.0               54000.0
Central Park Resorts                         5700.0               54000.0
Anand Niketan                                3400.0               54000.0
Godrej Aria                                 54000.0                5800.0
Vipul World                                  6900.0               54000.0
Bellavista Central Park Resorts              3700.0               54000.0
Bestech Park View Spa Next                  12000.0               54000.0
Signature Global Prime                      18400.0               54000.0
BPTP Pedestal                                5900.0               54000.0
Pegasus Atulyam 83                           8900.0               54000.0

In [376]:
location_df.at["Godrej Aria", "Airia Mall"] = 5800.0

In [377]:
location_df[location_df["Alpine Convent School"]+location_df["Alpine School"] < 108000][["Alpine Convent School","Alpine School"]]

                        Alpine Convent School  Alpine School
PropertyName
Emaar Digihomes                        1500.0        54000.0
DLF New Town Heights 2                  950.0        54000.0
DLF The Skycourt                       1800.0        54000.0
Anand Niketan                          2800.0        54000.0
JMS Prime Land                        54000.0         2000.0

In [378]:
location_df.at["JMS Prime Land", "Alpine Convent School"] = 2000.0

In [379]:
location_df[location_df["Aman Hospital"]+location_df["Aman Hospital & Surgical Centre"] < 108000][["Aman Hospital","Aman Hospital & Surgical Centre"]]

Empty DataFrame
Columns: [Aman Hospital, Aman Hospital & Surgical Centre]
Index: []

In [380]:
location_df[location_df["Ambience Mall"]+location_df["Ambience Mall New"] < 108000][["Ambience Mall","Ambience Mall New"]]

                   Ambience Mall  Ambience Mall New
PropertyName
4S Aradhya Homes          5300.0            54000.0
Vatika Aspiration         8600.0            54000.0
Ireo Savannah            54000.0             2300.0

In [381]:
location_df.at["Ireo Savannah", "Ambience Mall"] = 2300.0

In [382]:
location_df[location_df["Amity University"]+location_df["Amity University Gurugram"] < 108000][["Amity University","Amity University Gurugram"]]

                   Amity University  Amity University Gurugram
PropertyName
Indiabulls Enigma           54000.0                    12000.0

In [383]:
location_df[location_df["Apollo"]+location_df["Apollo Pharmacy"] < 108000][["Apollo","Apollo Pharmacy"]]

                                 Apollo  Apollo Pharmacy
PropertyName
Emaar Mgf Palm Terraces Select  54000.0            900.0
Suncity Avenue 102              54000.0           4100.0

In [384]:
location_df[location_df["Appu Ghar"]+location_df["Appu Ghar Water Park"] < 108000][["Appu Ghar","Appu Ghar Water Park"]]

                         Appu Ghar  Appu Ghar Water Park
PropertyName
Experion The Westerlies     9200.0               54000.0
M3M Natura                 54000.0                8200.0
DLF The Grove              54000.0                2800.0
Mapsko The Icon 79          7500.0               54000.0
M3M Sky Lofts              54000.0                4700.0

In [385]:
location_df.at["Experion The Westerlies", "Appu Ghar Water Park"] = 9200.0
location_df.at["Mapsko The Icon 79", "Appu Ghar Water Park"] = 7500.0

In [386]:
location_df[location_df["Aravali Adventure Hill"]+location_df["Aravalli Hill View Point"] +location_df["Aravalli Hills"] < 162000][["Aravali Adventure Hill","Aravalli Hill View Point","Aravalli Hills"]]

,Aravali Adventure Hill,Aravalli Hill View Point,Aravalli Hills
PropertyName,,,
Adani Brahma Samsara,54000.0,54000.0,6500.0

In [387]:
location_df[location_df["Arc Hospital"]+location_df["Arc Multi Speciality"] +location_df["Arc Multi Speciality Hospital"] < 162000][["Arc Hospital","Arc Multi Speciality","Arc Multi Speciality Hospital"]]

,Arc Hospital,Arc Multi Speciality,Arc Multi Speciality Hospital
PropertyName,,,
Central Park Flower Valley The Room,54000.0,54000.0,4100.0
BPTP Mansions Park Prime,54000.0,2500.0,54000.0

In [388]:
location_df.at["BPTP Mansions Park Prime", "Arc Multi Speciality Hospital"] = 2500.0

In [389]:
location_df[location_df["Artemis"]+location_df["Artemis Hospital"] +location_df["Artemis Hospital Gurgaon"] +location_df["Artimis hospital"] < 216000][["Artemis","Artemis Hospital Gurgaon","Artemis Hospital","Artimis hospital"]]

,Artemis,Artemis Hospital Gurgaon,Artemis Hospital,Artimis hospital
PropertyName,,,,
Signature The Roselia,54000.0,5900.0,54000.0,54000.0

In [390]:
location_df[location_df["Arvy Hospital"] +location_df["Aarvy Healthcare Super Speciality"] < 108000][["Arvy Hospital","Aarvy Healthcare Super Speciality"]]

,Arvy Hospital,Aarvy Healthcare Super Speciality
PropertyName,,
International City by SOBHA Phase 2,54000.0,8800.0
Ireo Victory Valley,54000.0,2500.0
DLF Park Place,54000.0,4700.0
Central Park Flower Valley,54000.0,8000.0
Emaar MGF Emerald Floors Premier,54000.0,3900.0
M3M Sierra 68,54000.0,3200.0
Tulip Violet,54000.0,2300.0
Bestech Park View Grand Spa,54000.0,3200.0
Shree Vardhman Victoria,54000.0,3500.0
Shree Vardhman Flora,54000.0,4700.0
BPTP Fortuna,54000.0,3600.0
Godrej Oasis,54000.0,4000.0
Golden Park,54000.0,4000.0
Umang Winter Hills,54000.0,2900.0
Silverglades Hightown Residences,54000.0,1800.0
Mahindra Aura,54000.0,4100.0
Zara Rossa,6500.0,54000.0

In [391]:
location_df.at["Zara Rossa", "Aarvy Healthcare Super Speciality"] = 6500.0

In [392]:
location_df[location_df["Ascendas OneHub Gurgaon"] +location_df["Ascendas OneHub Gurgaon Business Park"] < 108000][["Ascendas OneHub Gurgaon","Ascendas OneHub Gurgaon Business Park"]]

,Ascendas OneHub Gurgaon,Ascendas OneHub Gurgaon Business Park
PropertyName,,
Vatika Express City,5800.0,54000.0
Pegasus Atulyam 83,54000.0,2200.0

In [393]:
location_df.at["Pegasus Atulyam 83", "Ascendas OneHub Gurgaon"] = 2200.0

In [394]:
location_df[location_df["Axis Bank"]+location_df["Axis Bank ATM"] +location_df["Axis Bank, Sohna Rd"] < 162000][["Axis Bank","Axis Bank ATM","Axis Bank, Sohna Rd"]]

                                Axis Bank  Axis Bank ATM  Axis Bank, Sohna Rd
PropertyName
BPTP Pedestal                     54000.0        54000.0               5600.0
Emaar Mgf Palm Terraces Select     1400.0        54000.0              54000.0
Unitech Fresco                      300.0        54000.0              54000.0

In [395]:
location_df.at["Emaar Mgf Palm Terraces Select", "Axis Bank, Sohna Rd"] = 1400.0
location_df.at["Unitech Fresco", "Axis Bank, Sohna Rd"] = 300.0

In [396]:
location_df.shape

(246, 1070)

In [397]:
location_df.drop(columns=["Aapno Ghar", "AIPL Business Club Sector 62", "Aarvy Healthcare", "Aarvy Healthcare Hospital", "Aarvy Hospital","Adarsh public school,Garhi Harsaru","Airia Mall Sector 68","Alpine School","Ambience Mall New","Amity University","Apollo","Appu Ghar","Aravali Adventure Hill","Aravalli Hill View Point","Arc Hospital","Arc Multi Speciality","Artemis","Artemis Hospital","Artimis hospital","Arvy Hospital","Ascendas OneHub Gurgaon Business Park","Axis Bank","Axis Bank ATM"],inplace=True)

In [398]:
sorted(location_df.columns.to_list())

['AIIMS',
 'AIIMS Jhajjar',
 'AIPL Business Centre',
 'AIPL Business Club',
 'AIPL Business Co Working Space',
 'AIPL Business Tower',
 'AIPL Joy Street Mall',
 'APJ Abdul Kalam Park',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Ajit Stadium Dhanwapur',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Alpine Hospital',
 'Altrade Business Centre',
 'Aman Hospital',
 'Aman Hospital & Surgical Centre',
 'Ambience Mall',
 'Ambience Public School',
 'American Express',
 'Amity',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Ap Sports cricket ground',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Approved Sector 37 Mero Station',
 'Appu Ghar Water Park',
 'Aradhya Cricket Club Gurgaon',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Athena',
 'Au Grand Air',
 'Axis Bank, Sohna Rd',
 'BM College of Technology',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BOB ATM',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Hwy',
 'Badshahpur Sohna Rd Hwy',
 'Badshahpur Sohna Rd Hwy, Haryana',
 'Badshahpur Sohna Rd Hwy, Malibu Town',
 'Badshahpur Sohna Rd Hwy, Raghav Vatika',
 'Badshahpur Sohna Rd Hwy, Rajoria Ngr',
 'Badshahpur Sohna Rd Hwy, Sector 68',
 'Badshahpur Sohna Rd Hwy,Sector 48',
 'Badshapur Sohna Highway',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Bamroli Cricket Ground',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Bank Of Baroda ATM',
 'Basai Dhancourt Railway Station',
 'Basai Dhankot',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Best IVF Centre',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petrol Pump',
 'Bharat Petroleum Petrol Pump',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharat Singh fuel company',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'BigBazaar',
 'Bijwasan Railway Station',
 'Biryani Shah',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CBR Cricket Ground',
 'CD International School',
 'CK Birla Hospital',
 'CK Birla Hospital, Gurgaon',
 'CNG Petrol Pump',
 'Cambridge College Of Education',
 'Cambridge Montessori',
 'Cambridge Montessori Preschool',
 'Cambridge Pre-School',
 'Canara Bank',
 'Canara Bank - Nawada Fatehpur',
 'Canara Bank ATM',
 'Canara Bank New Palam Vihar',
 'Candor TechSpace, Sector 48',
 'Candor Techspace',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park Flower Valley',
 'Central Park II Road',
 'Central Park Resorts',
 'Central Park, Sohna Rd',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Centrum Plaza',
 'Chauma Road',
 "Cherub's Cradle",
 'Children Park',
 'Chirag Hospital',
 'Choice pharmacy',
 'Citibank ATM',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 'CoNexus.Life B35',
 "Colonel's Central Academy",
 'Conscient One',
 'Conscient One Mall',
 'Cool Deck Coffee',
 'Country Inn',
 'Country Inn & Suites By Radisson',
 'Country Inn & Suites by Radisson',
 'Country Inn and Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLC Cricket Ground',
 'DLF Corporate Greens',
 'DLF Corporate Park',
 'DLF Cyber City',
 'DLF Golf and Country Club',
 'DLF Grand Mall',
 'DLF Linear Park',
 'DLF Site central office',
 'DLF World Tech Park',
 'DLF5 Summit Plaza',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPS International Edge',
 'DPS International School',
 'DPS Manesar',
 'DPS Sector 103',
 'DPSG Palam Vihar',
 'DPSG Palam Vihar Gurugram',
 'DSD College',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'Daultabad Village Park',
 'De Adventure Amusement Park',
 'De Adventure Park',
 'Deerika HyperMart',
 'Delh-Ajmer Expy',
 'Delhi',
 'Delhi - Jaipur Expressway',
 'Delhi Ajmer Expressway',
 'Delhi Gurgaon Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School Sector 84',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Delhi-Mumbai Expressway',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'Dishoom Cinemas',
 "Domino's Pizza",
 'Double Infinity market',
 'Double Tree by Hilton',
 'DoubleTree by Hilton Hotel',
 'DoubleTree by Hilton Hotel Gurgaon',
 'Dr Naveen Chawla General Physician',
 'Dreamz Cafe',
 'Drona Sports Village',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwaraka Expressway',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka Sector 21 Metro station',
 'Dwarka Sector 21, Metro Station',
 'Dwarka expressway',
 'Dwarka expressway Basai crossing',
 'Dwarka sector 21 metro station',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC HOSPITAL',
 'ESIC Hospital',
 'Early Basket Grocery shop',
 'Edge towers tennis court',
 'Ektaa Hospital',
 'Ektaa Hospitals',
 'Ektaa Hospitals  Main Sohna Rd',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza',
 'Emerald Plaza Shopping Mall',
 'Enkays Hospital',
 'Entertainland Mall',
 'Ernst & Young',
 'Eros City Square',
 'Eros Corporate Park',
 'Esplanade Mall',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro Int. School',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector 37D',
 'Euro International School, Sector 84',
 'Euro International School, Sector- 109',
 'Euro International School, Sector- 109.',
 'Euro International School, sector- 51',
 'Euro Intl School Sec-51',
 'Euro Intl School, Sector 37D, Gurugram',
 'Euro Intl School, Sector- 109',
 'EuroKids Preschool Suncity',
 'Excellere World School',
 'Eye Doctors at Krishna Netralaya',
 'F9 Go Karting Gurgaon',
 'FUEL NATION',
 'Faridabad',
 'Faridabad - Gurgaon Rd',
 'Faridabad - Gurgaon Road',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fortis hospital',
 'Fresco Market',
 'Frescos',
 'Fun N Food Village',
 'Fun N Food Water Park',
 'Fun N Food WaterPark',
 'Fun N Food Waterpark',
 'G D Goenka University',
 'G D Goenka World School',
 'GD Goenka',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka School',
 'GD Goenka Signature School',
 'GD Goenka University',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Garima Public School',
 'Gaytri Public School',
 'Gd goenka university',
 'Gems International School',
 'Genesis Hospital',
 'Genesis Hospital Sector 84',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global City Centre Mall',
 'Global Foyer Mall',
 'Global Foyer Mall,  Palam Vihar',
 'Global Ways School',
 'Global city centre',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Greens Golf & Resorts Limited',
 'Golden Tulip Suites Gurgaon',
 'Golf Corse Ext. Rd.',
 'Golf Course Ext Rd',
 'Golf Course Ext Road',
 'Golf Course Extension',
 'Golf Course Extension Rd',
 'Golf Course Extension Road',
 'Golf Course Extn Road',
 'Golf Course Rd',
 'Golf Course Road',
 'Golf Pavilion',
 'Golf course extension road',
 'Govind Hospital',
 'Govt. Model Sanskriti Primary School',
 'Govt. PG College',
 'Grand Hyatt',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Green Field School',
 'Green garden narsari',
 'Greenway Hospital',
 "Guls' Kitchen",
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon - Delhi Expy, Sector 75A',
 'Gurgaon Dreamz Mall',
 'Gurgaon Faridabad Highway',
 'Gurgaon Gramin Bank',
 'Gurgaon Old Railway Station',
 'Gurgaon Railway Station',
 'Gurgaon Road',
 'Gurgaon Toll',
 'Gurgaon railway station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram City Bus Depot',
 'Gurugram Global Heights School',
 'Gurugram Hospital',
 'Gurugram Public School',
 'Gurugram Railway Station',
 'Gurugram Rd',
 'Gurugram Road',
 'Gurugram University',
 'Gurugram University Kankrola',
 'Gurugram University Sector 87',
 'Gurukul Preschool',
 'Gyaananda School',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HDFC Bank ATM, Dhunela Ghamroj',
 'HDFC Bank, Pataudi Rd',
 'HDFC bank ATM',
 'HP PETROL PUMP Unnamed Rd',
 'HP Petrol Pump',
 'HSBC',
 'HUB 66',
 'HUDA Market',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Hanuman & Shani Mandir',
 'Harsaru Village Bus Stop',
 'Haryana City Gas',
 'Hasanpur',
 'Health Care Pharmacy',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Heritage Xperiential Learning, CRPF Rd',
 'Heritage badminton academy',
 'Hero Honda Chowk',
 'Holiday Inn',
 'Holiday Inn Express Gurugram',
 'Holiday Inn Express Gurugram Sec 50',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Hotel Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Horizon 1 Mall',
 'Hotel Golf View Suites',
 'Hub 66',
 'Huda City Centre',
 'Huda City Centre Metro Station',
 'Huda Metro Station',
 'Huda Metro Station (Gurugram)',
 'Huda Metro station',
 'Huda Park',
 'Huda city center',
 'Huda metro station',
 'Hyatt Place',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency',
 'Hyatt Regency Gurgaon',
 'Hyatt Regency Gurugram',
 'Hyatt Regency Hotel',
 'ICFAI University',
 'ICICI ATM',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank',
 'ICICI Bank ATM',
 'ICICI Bank ATM, Sector 86',
 'IDFC FIRST Bank',
 'IFFCO Chowk',
 'IFFCO Chowk Metro Station',
 'IG International Airport',
 'IGI Airport',
 'IGIA Airport',
 'IILM School of Management',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'IMT Sohna',
 'INOX Cinema',
 'INXT High Street',
 'IRIS Broadway Mall',
 'ISBM College',
 'ISKCON',
 'ISKCON Temple',
 'Ibis Hotel',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperfecto Patio',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Imt Manesar',
 'Imt Manesar, Gurugram',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Airport',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi Int. Airport',
 'Indira Gandhi International Airport',
 'Indira Gandhi Intl Airport',
 'Indus World School',
 'Indus valley Public School',
 'IndusInd Bank',
 'IndusInd Bank ATM',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Infinitys Badminton Academy',
 'Info Technology Park Phase 2',
 'Insfire Sports',
 'International Airport',
 'International Tech Park Gurgaon',
 'International Tech Park Gurgaon,',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jagdish Super Market',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinaglala Theme Park',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Jungle Safari & Trails',
 'K. R. Mangalam University',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'K.R.Mangalam World School',
 'KDM Public School, Sohna',
 'KFG Sports Club',
 'KFG sports club Parking',
 'KIIT College',
 'KIIT College of Engineering',
 'KIIT College of Engineering Sohna Road',
 'KLAY Play School',
 'KMP Corridor',
 'KMP Expressway',
 'KMP corridor',
 'KR Mangalam',
 'KR Mangalam University',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Kangaroo Kids Preschool',
 'Karma Lakelands',
 'Keshav Pharmacy',
 'Khatu Shyam Mandir',
 'Kheri Railway station',
 'Kidzee',
 'Kidzee Sec-93',
 'Kinder Care Playschool',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kundli Manesar Palwal Expressway',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Learning Stars School',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel,',
 'Lemon Tree Hotel, Sohna Road',
 'Leopard hills',
 "Lingaya's Lalita Devi Institute",
 'Lions Public School',
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lotus Valley School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MCC Cricket Ground Dhankot',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Megacity Mall',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Mamta Hospital',
 'Manav Rachna School',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Marigold Secondary School',
 'Marriott Courtyard',
 'MatriKiran High School',
 'Matrikiran High School',
 'Matrikiran School',
 'Mavens Inn',
 'Mavens Orange - Hotel',
 'Max, Fortis',
 "McDonald's India",
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta Dialysis Center',
 'Medanta Hospital',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Medhaam Pre School & Daycare',
 'Medicity',
 'Meditree Market',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle / Spectra',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'Moksh Wellness Pvt Ltd.',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'N.H-8',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248',
 'NH 248 A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Neemrana Palace',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'New Water Pond',
 'Newtown Square Mall',
 'Ninex Mall',
 'Nirvana Rd',
 'Nischay Cricket Academy',
 'Nora Solomon Medicenter',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'OMAXE Gurgaon Mall',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Bengali Market',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Omex City Centre Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open Tap',
 'Open gym garden',
 'Orchid Business Park',
 'Oriental Bank of Commerce',
 "Oyster's Water Park",
 'PHC Garhi Harsaru',
 'PNB ATM',
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Park inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pataudi road',
 'Pathfinder Global School, Pataudi',
 'Pathways',
 'Pathways School Gurgaon',
 'Patil Station',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Peer Baba Ki Mazar',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Prakash Hospital',
 'Pranavananda Int. School',
 'Pranavananda International School',
 'Presidium School Gurgoan',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Propose Metro Station',
 'Proposed Metro Station',
 'Proposed Metro corridor',
 'Public Bazar',
 'Punjab National Bank',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Raheja Market',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Rajiv Chowk - Sohna Highway',
 'Ram Krishna Public School',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 55-56',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 55 56',
 'Rapid Metro Station Sector 56',
 'Rathore IMT Hospital',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCJ Academy',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UHTC Basai',
 'SGT UNIVERSITY',

In [399]:
location_df[location_df["BM College of Technology"] +location_df["BM College of Technology & Mgmt"] < 108000][["BM College of Technology","BM College of Technology & Mgmt"]]

              BM College of Technology  BM College of Technology & Mgmt
PropertyName
Vatika City                    54000.0                           9600.0

In [400]:
#location_df[location_df["Badshahpur Sohna Hwy"] +location_df["Badshahpur Sohna Rd Hwy"]+location_df["Badshahpur Sohna Rd Hwy, Haryana"]+location_df["Badshahpur Sohna Rd Hwy, Malibu Town"]+location_df["Badshahpur Sohna Rd Hwy, Raghav Vatika"]+location_df["Badshahpur Sohna Rd Hwy, Rajoria Ngr"]+location_df["Badshahpur Sohna Rd Hwy, Sector 68"]+location_df["Badshahpur Sohna Rd Hwy,Sector 48"]+location_df["Badshapur Sohna Highway"] < (9*54000)][["Badshahpur Sohna Hwy","Badshahpur Sohna Rd Hwy","Badshahpur Sohna Rd Hwy, Haryana","Badshahpur Sohna Rd Hwy, Malibu Town","Badshahpur Sohna Rd Hwy, Raghav Vatika","Badshahpur Sohna Rd Hwy, Rajoria Ngr","Badshahpur Sohna Rd Hwy, Sector 68","Badshahpur Sohna Rd Hwy,Sector 48","Badshapur Sohna Highway"]]

In [401]:
location_df.at["Signature Global City 93", "Badshahpur Sohna Rd Hwy"] = 7500.0
location_df.at["Whiteland The Aspen", "Badshahpur Sohna Rd Hwy"] = 8700.0
location_df.at["Krisumi Waterfall Residences", "Badshahpur Sohna Rd Hwy"] = 7500.0
location_df.at["Birla Navya", "Badshahpur Sohna Rd Hwy"] = 5400.0
location_df.at["Bestech Park View Ananda", "Badshahpur Sohna Rd Hwy"] = 10500.0
location_df.at["Signature Global Solera", "Badshahpur Sohna Rd Hwy"] = 2600.0
location_df.at["Vatika India Next Plots", "Badshahpur Sohna Rd Hwy"] = 3000.0
location_df.at["Optimal ultra luxury builder floors", "Badshahpur Sohna Rd Hwy"] = 4100.0

In [402]:
location_df[location_df["Bank Of Baroda ATM"] +location_df["Bank Of Baroda"] < 108000][["Bank Of Baroda","Bank Of Baroda ATM"]]

                  Bank Of Baroda  Bank Of Baroda ATM
PropertyName
Birla Navya Avik         54000.0              1300.0
La Lagune                 2500.0             54000.0

In [403]:
location_df.at["Birla Navya Avik", "Bank Of Baroda"] = 1300.0

In [404]:
location_df.at["DLF The Crest", "Basai Dhankot Railway Station"] = 2000.0
location_df.at["Smart World Gems", "Basai Dhankot Railway Station"] = 4300.0

In [405]:
location_df[location_df["Bharat Petrol Pump"] +location_df["Bharat Petroleum Petrol Pump"]+location_df["Bharat Petroleum Retail Outlet"]+location_df["Bharat Petroleum Shree Shyam Filling"] < (4*54000)][["Bharat Petrol Pump","Bharat Petroleum Petrol Pump","Bharat Petroleum Retail Outlet","Bharat Petroleum Shree Shyam Filling"]]

,Bharat Petrol Pump,Bharat Petroleum Petrol Pump,Bharat Petroleum Retail Outlet,Bharat Petroleum Shree Shyam Filling
PropertyName,,,,
Yashika 104,54000.0,54000.0,54000.0,1000.0
Suncity Avenue 102,54000.0,54000.0,2600.0,54000.0

In [406]:
location_df["Bharat Petrol Pump"].min()

54000.0

In [407]:
location_df[location_df["CK Birla Hospital"] +location_df["CK Birla Hospital, Gurgaon"] < 108000][["CK Birla Hospital","CK Birla Hospital, Gurgaon"]]

                        CK Birla Hospital  CK Birla Hospital, Gurgaon
PropertyName
ATS Triumph                       54000.0                      6200.0
ROF Insignia Park                  2500.0                     54000.0
DLF The Skycourt                   4500.0                     54000.0
DLF New Town Heights 1             4000.0                     54000.0
Vatika Gurgaon 21                  5200.0                     54000.0
Signature The Roselia              3800.0                     54000.0

In [408]:
location_df.at["ATS Triumph", "CK Birla Hospital"] = 6200.0

In [409]:
location_df[location_df["Cambridge College Of Education"] +location_df["Cambridge Montessori"]+location_df["Cambridge Montessori Preschool"]+location_df["Cambridge Pre-School"] < (4*54000)][["Cambridge College Of Education","Cambridge Montessori","Cambridge Montessori Preschool","Cambridge Pre-School"]]

,Cambridge College Of Education,Cambridge Montessori,Cambridge Montessori Preschool,Cambridge Pre-School
PropertyName,,,,
Paras Ekam Homes,54000.0,54000.0,2600.0,54000.0

In [410]:
location_df["Canara Bank ATM"].min()

54000.0

In [411]:
location_df[location_df["CANARA BANK"] +location_df["Canara Bank"]+location_df["Canara Bank - Nawada Fatehpur"]+location_df["Canara Bank ATM"]+location_df["Canara Bank New Palam Vihar"] < (5*54000)][["CANARA BANK","Canara Bank","Canara Bank - Nawada Fatehpur","Canara Bank ATM","Canara Bank New Palam Vihar"]]

,CANARA BANK,Canara Bank,Canara Bank - Nawada Fatehpur,Canara Bank ATM,Canara Bank New Palam Vihar
PropertyName,,,,,
Birla Navya Avik,1300.0,54000.0,54000.0,54000.0,54000.0
Umang Winter Hills,54000.0,54000.0,2200.0,54000.0,54000.0
Yashika 104,54000.0,54000.0,54000.0,54000.0,2700.0

In [412]:
location_df.at["Umang Winter Hills", "CANARA BANK"] = 2200.0
location_df.at["Yashika 104", "CANARA BANK"] = 2700.0

In [413]:
location_df[location_df["Candor TechSpace, Sector 48"] +location_df["Candor Techspace"] < 108000][["Candor TechSpace, Sector 48","Candor Techspace"]]

                  Candor TechSpace, Sector 48  Candor Techspace
PropertyName
4S Aradhya Homes                      54000.0            1300.0
Eldeco Accolade                         500.0           54000.0

In [414]:
location_df.at["4S Aradhya Homes", "Candor TechSpace, Sector 48"] = 1300.0

In [415]:
location_df[location_df["Central Park Flower Valley"] +location_df["Central Park II Road"]+location_df["Central Park Resorts"]+location_df["Central Park, Sohna Rd"] < (4*54000)][["Central Park Flower Valley","Central Park II Road","Central Park Resorts","Central Park, Sohna Rd"]]

,Central Park Flower Valley,Central Park II Road,Central Park Resorts,"Central Park, Sohna Rd"
PropertyName,,,,
M3M Capital,54000.0,13.0,54000.0,54000.0
Vatika The Seven Lamps,54000.0,54000.0,54000.0,850.0

In [416]:
location_df.at["Vatika The Seven Lamps", "Central Park II Road"] = 850.0

In [417]:
location_df[location_df["Central Plaza Mall"] +location_df["Centrum Plaza"] < 108000][["Central Plaza Mall","Centrum Plaza"]]

                           Central Plaza Mall  Centrum Plaza
PropertyName
DLF Garden City Floors                 8900.0        54000.0
Anant Raj Estate Plots                  500.0        54000.0
Landmark The Homes 81                  2700.0        54000.0
Conscient Habitat                      1800.0        54000.0
ILD Grand                              1700.0        54000.0
Signature Global Solera 2              2100.0        54000.0
Breez Global Heights 89                1000.0        54000.0

In [418]:
location_df["Conscient One Mall"].min()

54000.0

In [419]:
location_df[location_df["Conscient One"] +location_df["Conscient One Mall"] < 108000][["Conscient One","Conscient One Mall"]]

              Conscient One  Conscient One Mall
PropertyName
Yashika 104          1100.0             54000.0

In [420]:
location_df[location_df["Country Inn"] +location_df["Country Inn & Suites By Radisson"]+location_df["Country Inn & Suites by Radisson"]+location_df["Country Inn and Suites by Radisson"] < (4*54000)][["Country Inn","Country Inn & Suites By Radisson","Country Inn & Suites by Radisson","Country Inn and Suites by Radisson"]]

,Country Inn,Country Inn & Suites By Radisson,Country Inn & Suites by Radisson,Country Inn and Suites by Radisson
PropertyName,,,,
Smart World Orchard,54000.0,54000.0,54000.0,8300.0
DLF The Camellias,54000.0,8100.0,54000.0,54000.0
DLF Gardencity,54000.0,54000.0,11300.0,54000.0
M3M Natura,54000.0,54000.0,4100.0,54000.0
Central Park Flower Valley Flamingo Floors,54000.0,54000.0,7900.0,54000.0
Bestech Park View Spa Next,54000.0,9100.0,54000.0,54000.0
Pegasus Atulyam 83,54000.0,5900.0,54000.0,54000.0

In [421]:
location_df.at["Smart World Orchard", "Country Inn & Suites by Radisson"] = 8300.0
location_df.at["DLF The Camellias", "Country Inn & Suites by Radisson"] = 8100.0
location_df.at["Bestech Park View Spa Next", "Country Inn & Suites by Radisson"] = 9100.0
location_df.at["Pegasus Atulyam 83", "Country Inn & Suites by Radisson"] = 5900.0

In [422]:
location_df.drop(columns=["BM College of Technology","Badshahpur Sohna Hwy","Badshahpur Sohna Rd Hwy, Haryana","Badshahpur Sohna Rd Hwy, Malibu Town","Badshahpur Sohna Rd Hwy, Raghav Vatika","Badshahpur Sohna Rd Hwy, Rajoria Ngr","Badshahpur Sohna Rd Hwy, Sector 68","Badshahpur Sohna Rd Hwy,Sector 48","Badshapur Sohna Highway","Bank Of Baroda ATM","Basai Dhankot","Basai Dhancourt Railway Station","Bharat Petrol Pump","Bharat Petroleum Petrol Pump","CK Birla Hospital, Gurgaon","Cambridge Pre-School","Cambridge College Of Education","Cambridge Montessori","Canara Bank","Canara Bank ATM","Canara Bank - Nawada Fatehpur","Canara Bank New Palam Vihar","Candor Techspace","Central Park Flower Valley","Central Park Resorts","Central Park, Sohna Rd","Centrum Plaza","Conscient One Mall","Country Inn","Country Inn & Suites By Radisson","Country Inn and Suites by Radisson"],inplace=True)

In [423]:
location_df.shape

(246, 1016)

In [424]:
sorted(location_df.columns.to_list())

['AIIMS',
 'AIIMS Jhajjar',
 'AIPL Business Centre',
 'AIPL Business Club',
 'AIPL Business Co Working Space',
 'AIPL Business Tower',
 'AIPL Joy Street Mall',
 'APJ Abdul Kalam Park',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Ajit Stadium Dhanwapur',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Alpine Hospital',
 'Altrade Business Centre',
 'Aman Hospital',
 'Aman Hospital & Surgical Centre',
 'Ambience Mall',
 'Ambience Public School',
 'American Express',
 'Amity',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Ap Sports cricket ground',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Approved Sector 37 Mero Station',
 'Appu Ghar Water Park',
 'Aradhya Cricket Club Gurgaon',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Athena',
 'Au Grand Air',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BOB ATM',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Bamroli Cricket Ground',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Best IVF Centre',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharat Singh fuel company',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'BigBazaar',
 'Bijwasan Railway Station',
 'Biryani Shah',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CBR Cricket Ground',
 'CD International School',
 'CK Birla Hospital',
 'CNG Petrol Pump',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 "Cherub's Cradle",
 'Children Park',
 'Chirag Hospital',
 'Choice pharmacy',
 'Citibank ATM',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 'CoNexus.Life B35',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLC Cricket Ground',
 'DLF Corporate Greens',
 'DLF Corporate Park',
 'DLF Cyber City',
 'DLF Golf and Country Club',
 'DLF Grand Mall',
 'DLF Linear Park',
 'DLF Site central office',
 'DLF World Tech Park',
 'DLF5 Summit Plaza',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPS International Edge',
 'DPS International School',
 'DPS Manesar',
 'DPS Sector 103',
 'DPSG Palam Vihar',
 'DPSG Palam Vihar Gurugram',
 'DSD College',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'Daultabad Village Park',
 'De Adventure Amusement Park',
 'De Adventure Park',
 'Deerika HyperMart',
 'Delh-Ajmer Expy',
 'Delhi',
 'Delhi - Jaipur Expressway',
 'Delhi Ajmer Expressway',
 'Delhi Gurgaon Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School Sector 84',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Delhi-Mumbai Expressway',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'Dishoom Cinemas',
 "Domino's Pizza",
 'Double Infinity market',
 'Double Tree by Hilton',
 'DoubleTree by Hilton Hotel',
 'DoubleTree by Hilton Hotel Gurgaon',
 'Dr Naveen Chawla General Physician',
 'Dreamz Cafe',
 'Drona Sports Village',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwaraka Expressway',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka Sector 21 Metro station',
 'Dwarka Sector 21, Metro Station',
 'Dwarka expressway',
 'Dwarka expressway Basai crossing',
 'Dwarka sector 21 metro station',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC HOSPITAL',
 'ESIC Hospital',
 'Early Basket Grocery shop',
 'Edge towers tennis court',
 'Ektaa Hospital',
 'Ektaa Hospitals',
 'Ektaa Hospitals  Main Sohna Rd',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza',
 'Emerald Plaza Shopping Mall',
 'Enkays Hospital',
 'Entertainland Mall',
 'Ernst & Young',
 'Eros City Square',
 'Eros Corporate Park',
 'Esplanade Mall',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro Int. School',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector 37D',
 'Euro International School, Sector 84',
 'Euro International School, Sector- 109',
 'Euro International School, Sector- 109.',
 'Euro International School, sector- 51',
 'Euro Intl School Sec-51',
 'Euro Intl School, Sector 37D, Gurugram',
 'Euro Intl School, Sector- 109',
 'EuroKids Preschool Suncity',
 'Excellere World School',
 'Eye Doctors at Krishna Netralaya',
 'F9 Go Karting Gurgaon',
 'FUEL NATION',
 'Faridabad',
 'Faridabad - Gurgaon Rd',
 'Faridabad - Gurgaon Road',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fortis hospital',
 'Fresco Market',
 'Frescos',
 'Fun N Food Village',
 'Fun N Food Water Park',
 'Fun N Food WaterPark',
 'Fun N Food Waterpark',
 'G D Goenka University',
 'G D Goenka World School',
 'GD Goenka',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka School',
 'GD Goenka Signature School',
 'GD Goenka University',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Garima Public School',
 'Gaytri Public School',
 'Gd goenka university',
 'Gems International School',
 'Genesis Hospital',
 'Genesis Hospital Sector 84',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global City Centre Mall',
 'Global Foyer Mall',
 'Global Foyer Mall,  Palam Vihar',
 'Global Ways School',
 'Global city centre',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Greens Golf & Resorts Limited',
 'Golden Tulip Suites Gurgaon',
 'Golf Corse Ext. Rd.',
 'Golf Course Ext Rd',
 'Golf Course Ext Road',
 'Golf Course Extension',
 'Golf Course Extension Rd',
 'Golf Course Extension Road',
 'Golf Course Extn Road',
 'Golf Course Rd',
 'Golf Course Road',
 'Golf Pavilion',
 'Golf course extension road',
 'Govind Hospital',
 'Govt. Model Sanskriti Primary School',
 'Govt. PG College',
 'Grand Hyatt',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Green Field School',
 'Green garden narsari',
 'Greenway Hospital',
 "Guls' Kitchen",
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon - Delhi Expy, Sector 75A',
 'Gurgaon Dreamz Mall',
 'Gurgaon Faridabad Highway',
 'Gurgaon Gramin Bank',
 'Gurgaon Old Railway Station',
 'Gurgaon Railway Station',
 'Gurgaon Road',
 'Gurgaon Toll',
 'Gurgaon railway station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram City Bus Depot',
 'Gurugram Global Heights School',
 'Gurugram Hospital',
 'Gurugram Public School',
 'Gurugram Railway Station',
 'Gurugram Rd',
 'Gurugram Road',
 'Gurugram University',
 'Gurugram University Kankrola',
 'Gurugram University Sector 87',
 'Gurukul Preschool',
 'Gyaananda School',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HDFC Bank ATM, Dhunela Ghamroj',
 'HDFC Bank, Pataudi Rd',
 'HDFC bank ATM',
 'HP PETROL PUMP Unnamed Rd',
 'HP Petrol Pump',
 'HSBC',
 'HUB 66',
 'HUDA Market',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Hanuman & Shani Mandir',
 'Harsaru Village Bus Stop',
 'Haryana City Gas',
 'Hasanpur',
 'Health Care Pharmacy',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Heritage Xperiential Learning, CRPF Rd',
 'Heritage badminton academy',
 'Hero Honda Chowk',
 'Holiday Inn',
 'Holiday Inn Express Gurugram',
 'Holiday Inn Express Gurugram Sec 50',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Hotel Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Horizon 1 Mall',
 'Hotel Golf View Suites',
 'Hub 66',
 'Huda City Centre',
 'Huda City Centre Metro Station',
 'Huda Metro Station',
 'Huda Metro Station (Gurugram)',
 'Huda Metro station',
 'Huda Park',
 'Huda city center',
 'Huda metro station',
 'Hyatt Place',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency',
 'Hyatt Regency Gurgaon',
 'Hyatt Regency Gurugram',
 'Hyatt Regency Hotel',
 'ICFAI University',
 'ICICI ATM',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank',
 'ICICI Bank ATM',
 'ICICI Bank ATM, Sector 86',
 'IDFC FIRST Bank',
 'IFFCO Chowk',
 'IFFCO Chowk Metro Station',
 'IG International Airport',
 'IGI Airport',
 'IGIA Airport',
 'IILM School of Management',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'IMT Sohna',
 'INOX Cinema',
 'INXT High Street',
 'IRIS Broadway Mall',
 'ISBM College',
 'ISKCON',
 'ISKCON Temple',
 'Ibis Hotel',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperfecto Patio',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Imt Manesar',
 'Imt Manesar, Gurugram',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Airport',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi Int. Airport',
 'Indira Gandhi International Airport',
 'Indira Gandhi Intl Airport',
 'Indus World School',
 'Indus valley Public School',
 'IndusInd Bank',
 'IndusInd Bank ATM',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Infinitys Badminton Academy',
 'Info Technology Park Phase 2',
 'Insfire Sports',
 'International Airport',
 'International Tech Park Gurgaon',
 'International Tech Park Gurgaon,',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jagdish Super Market',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinaglala Theme Park',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Jungle Safari & Trails',
 'K. R. Mangalam University',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'K.R.Mangalam World School',
 'KDM Public School, Sohna',
 'KFG Sports Club',
 'KFG sports club Parking',
 'KIIT College',
 'KIIT College of Engineering',
 'KIIT College of Engineering Sohna Road',
 'KLAY Play School',
 'KMP Corridor',
 'KMP Expressway',
 'KMP corridor',
 'KR Mangalam',
 'KR Mangalam University',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Kangaroo Kids Preschool',
 'Karma Lakelands',
 'Keshav Pharmacy',
 'Khatu Shyam Mandir',
 'Kheri Railway station',
 'Kidzee',
 'Kidzee Sec-93',
 'Kinder Care Playschool',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kundli Manesar Palwal Expressway',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Learning Stars School',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel,',
 'Lemon Tree Hotel, Sohna Road',
 'Leopard hills',
 "Lingaya's Lalita Devi Institute",
 'Lions Public School',
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lotus Valley School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MCC Cricket Ground Dhankot',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Megacity Mall',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Mamta Hospital',
 'Manav Rachna School',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Marigold Secondary School',
 'Marriott Courtyard',
 'MatriKiran High School',
 'Matrikiran High School',
 'Matrikiran School',
 'Mavens Inn',
 'Mavens Orange - Hotel',
 'Max, Fortis',
 "McDonald's India",
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta Dialysis Center',
 'Medanta Hospital',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Medhaam Pre School & Daycare',
 'Medicity',
 'Meditree Market',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle / Spectra',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'Moksh Wellness Pvt Ltd.',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'N.H-8',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248',
 'NH 248 A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Neemrana Palace',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'New Water Pond',
 'Newtown Square Mall',
 'Ninex Mall',
 'Nirvana Rd',
 'Nischay Cricket Academy',
 'Nora Solomon Medicenter',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'OMAXE Gurgaon Mall',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Bengali Market',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Omex City Centre Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open Tap',
 'Open gym garden',
 'Orchid Business Park',
 'Oriental Bank of Commerce',
 "Oyster's Water Park",
 'PHC Garhi Harsaru',
 'PNB ATM',
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Park inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pataudi road',
 'Pathfinder Global School, Pataudi',
 'Pathways',
 'Pathways School Gurgaon',
 'Patil Station',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Peer Baba Ki Mazar',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Prakash Hospital',
 'Pranavananda Int. School',
 'Pranavananda International School',
 'Presidium School Gurgoan',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Propose Metro Station',
 'Proposed Metro Station',
 'Proposed Metro corridor',
 'Public Bazar',
 'Punjab National Bank',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Raheja Market',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Rajiv Chowk - Sohna Highway',
 'Ram Krishna Public School',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 55-56',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 55 56',
 'Rapid Metro Station Sector 56',
 'Rathore IMT Hospital',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCJ Academy',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UHTC Basai',
 'SGT UNIVERSITY',
 'SGT University',
 'SPM Hospital',
 'SRS Cinemas',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sanskar Jyoti School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Scottish International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 102 Dhankot',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43',

In [425]:
location_df[location_df["DLF Corporate Greens"] +location_df["DLF Corporate Park"]+location_df["DLF Cyber City"]+location_df["DLF Golf and Country Club"]+location_df["DLF Grand Mall"]+location_df["DLF Linear Park"]+location_df["DLF Site central office"]+location_df["DLF World Tech Park"]+location_df["DLF5 Summit Plaza"] < (9*54000)][["DLF5 Summit Plaza","DLF World Tech Park","DLF Site central office","DLF Linear Park","DLF Grand Mall","DLF Golf and Country Club","DLF Cyber City","DLF Corporate Park","DLF Corporate Greens"]]

,DLF5 Summit Plaza,DLF World Tech Park,DLF Site central office,DLF Linear Park,DLF Grand Mall,DLF Golf and Country Club,DLF Cyber City,DLF Corporate Park,DLF Corporate Greens
PropertyName,,,,,,,,,
SS Linden Floors,54000.0,54000.0,54000.0,54000.0,54000.0,11900.0,54000.0,54000.0,54000.0
SS The Leaf,54000.0,54000.0,54000.0,54000.0,54000.0,10500.0,54000.0,54000.0,54000.0
BPTP Amstoria,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,15700.0,54000.0
Emaar Emerald Hills,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,5400.0
ATS Marigold,54000.0,54000.0,54000.0,54000.0,54000.0,6000.0,54000.0,54000.0,54000.0
Experion Windchants,54000.0,54000.0,54000.0,54000.0,54000.0,15000.0,54000.0,54000.0,54000.0
Smart World Gems,54000.0,54000.0,54000.0,54000.0,54000.0,15500.0,54000.0,54000.0,54000.0
Vatika Aspiration,54000.0,54000.0,54000.0,900.0,54000.0,54000.0,54000.0,54000.0,54000.0
Ace Palm Floors,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,15800.0,54000.0
Rishali Luxe Residency 112,54000.0,54000.0,54000.0,54000.0,54000.0,17400.0,54000.0,54000.0,54000.0
International City by SOBHA Phase 2,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,10300.0
DLF The Ultima,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,6200.0
Central Park Flower Valley Mikasa Plots,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,9600.0
Experion The Heartsong,54000.0,54000.0,54000.0,54000.0,54000.0,8700.0,54000.0,54000.0,54000.0
DLF New Town Heights 2,54000.0,54000.0,54000.0,54000.0,54000.0,13000.0,54000.0,54000.0,54000.0
Central Park Resorts,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,4800.0
Anand Niketan,54000.0,54000.0,54000.0,54000.0,54000.0,16200.0,54000.0,54000.0,54000.0
Ansals Shiva Som Valley,54000.0,54000.0,54000.0,54000.0,54000.0,4200.0,54000.0,54000.0,54000.0
DLF The Grove,54000.0,54000.0,54000.0,54000.0,54000.0,4500.0,54000.0,54000.0,54000.0
Corona Optus,54000.0,54000.0,54000.0,54000.0,54000.0,10300.0,54000.0,54000.0,54000.0
Anant Raj Estate Plots,54000.0,54000.0,54000.0,54000.0,54000.0,4100.0,54000.0,54000.0,54000.0
M3M Sky Lofts,54000.0,54000.0,54000.0,54000.0,54000.0,3700.0,54000.0,54000.0,54000.0
Emaar Palm Gardens,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,8400.0
The Close North,54000.0,13000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Emaar The Palm Springs,54000.0,54000.0,1200.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Landmark The Homes 81,700.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
ILD Grand,54000.0,54000.0,54000.0,54000.0,54000.0,5300.0,54000.0,54000.0,54000.0
Signature Global Solera 2,54000.0,54000.0,54000.0,54000.0,54000.0,3000.0,54000.0,54000.0,54000.0
Breez Global Heights 89,54000.0,54000.0,54000.0,54000.0,54000.0,4600.0,54000.0,54000.0,54000.0
Zara Rossa,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,21500.0,54000.0,54000.0

In [426]:
location_df.at["BPTP Amstoria", "DLF Golf and Country Club"] = 15700.0
location_df.at["Vatika Aspiration", "DLF Golf and Country Club"] = 900.0
location_df.at["Ace Palm Floors", "DLF Golf and Country Club"] = 15800.0
location_df.at["Emaar Emerald Hills", "DLF Golf and Country Club"] = 5400.0
location_df.at["International City by SOBHA Phase 2", "DLF Golf and Country Club"] = 10300.0
location_df.at["DLF The Ultima", "DLF Golf and Country Club"] = 6200.0
location_df.at["Central Park Flower Valley Mikasa Plots", "DLF Golf and Country Club"] = 9600.0
location_df.at["Central Park Resorts", "DLF Golf and Country Club"] = 4800.0
location_df.at["Emaar Palm Gardens", "DLF Golf and Country Club"] = 8400.0
location_df.at["The Close North", "DLF Golf and Country Club"] = 13000.0
location_df.at["Emaar The Palm Springs", "DLF Golf and Country Club"] = 1200.0
location_df.at["Landmark The Homes 81", "DLF Golf and Country Club"] = 700.0
location_df.at["Zara Rossa", "DLF Golf and Country Club"] = 21500.0

In [427]:
location_df[location_df["DPS"] +location_df["DPS International Edge"]+location_df["DPS International School"] < (3*54000)][["DPS","DPS International Edge","DPS International School"]]

,DPS,DPS International Edge,DPS International School
PropertyName,,,
Tulip Monsella,54000.0,54000.0,850.0
M3M Skycity,54000.0,1500.0,54000.0
DLF New Town Heights 1,54000.0,1400.0,54000.0
Zara Rossa,4000.0,54000.0,54000.0

In [428]:
location_df.at["Tulip Monsella", "DPS"] = 850.0
location_df.at["M3M Skycity", "DPS"] = 1500.0
location_df.at["DLF New Town Heights 1", "DPS"] = 1400.0

In [429]:
location_df[location_df["DPSG Palam Vihar"] +location_df["DPSG Palam Vihar Gurugram"] < 108000][["DPSG Palam Vihar","DPSG Palam Vihar Gurugram"]]

                    DPSG Palam Vihar  DPSG Palam Vihar Gurugram
PropertyName
Smartworld One DXP            3100.0                    54000.0
Pioneer Araya                54000.0                     1400.0

In [430]:
location_df.at["Pioneer Araya", "DPSG Palam Vihar"] = 1400.0

In [431]:
location_df[location_df["De Adventure Amusement Park"] +location_df["De Adventure Park"] < 108000][["De Adventure Amusement Park","De Adventure Park"]]

                                De Adventure Amusement Park  De Adventure Park
PropertyName
Whiteland The Aspen                                 54000.0             5900.0
Signature Global City 81                            54000.0             5400.0
SS Linden Floors                                    54000.0             5000.0
Eldeco Acclaim                                      54000.0             4300.0
Emaar Emerald Hills                                 54000.0             3700.0
ATS Triumph                                         54000.0             6800.0
Signature Global City 37D Ph 2                      15000.0            54000.0
ROF Insignia Park                                   54000.0             6800.0
DLF The Ultima                                      54000.0             8800.0
Ramprastha Primera                                  54000.0             5300.0
Eldeco Accolade                                     54000.0             9000.0
Silverglades The Melia                              54000.0             8300.0
ROF Insignia Park 2                                 54000.0             6000.0
BPTP Fortuna                                        54000.0            16600.0
Vatika Independent Floors                           54000.0            11300.0
Emaar Palm Gardens                                  54000.0            11100.0

In [432]:
location_df.at["Signature Global City 37D Ph 2", "De Adventure Park"] = 15000.0

In [433]:
location_df[location_df["Delh-Ajmer Expy"] +location_df["Delhi Ajmer Expressway"] < 108000][["Delh-Ajmer Expy","Delhi Ajmer Expressway"]]

                   Delh-Ajmer Expy  Delhi Ajmer Expressway
PropertyName
Anant Raj Estates          54000.0                  9000.0
BPTP Green Oaks             5800.0                 54000.0

In [434]:
location_df.at["BPTP Green Oaks", "Delhi Ajmer Expressway"] = 5800.0

In [435]:
location_df[location_df["Delhi - Jaipur Expressway"] +location_df["Delhi Jaipur Expressway"] < 108000][["Delhi - Jaipur Expressway","Delhi Jaipur Expressway"]]

,Delhi - Jaipur Expressway,Delhi Jaipur Expressway
PropertyName,,
Oxirich Chintamanis,54000.0,5500.0
Yash Vihar,54000.0,3500.0
Adani Samsara Avasa,54000.0,3500.0
DLF The Aralias,54000.0,7700.0
Ambience Creacions,54000.0,5000.0
DLF The Belaire,54000.0,4200.0
Bellavista Central Park Resorts,54000.0,8000.0
Adani Brahma Samsara,54000.0,2500.0
Vatika Independent Floors,4400.0,54000.0
Puri Diplomatic Greens,54000.0,2000.0

In [436]:
location_df.at["Vatika Independent Floors", "Delhi Jaipur Expressway"] = 4400.0

In [437]:
location_df[location_df["Delhi Public School Sector 84"] +location_df["Delhi Public School, Sector 84"] < 108000][["Delhi Public School Sector 84","Delhi Public School, Sector 84"]]

,Delhi Public School Sector 84,"Delhi Public School, Sector 84"
PropertyName,,
International City by SOBHA Phase 2,54000.0,3100.0
Emaar MGF Emerald Floors Premier,54000.0,1300.0
M3M Skywalk,650.0,54000.0
Pioneer Urban Presidia,54000.0,2400.0

In [438]:
location_df.at["M3M Skywalk", "Delhi Public School, Sector 84"] = 650.0

In [439]:
location_df[location_df["Double Tree by Hilton"] +location_df["DoubleTree by Hilton Hotel"]+location_df["DoubleTree by Hilton Hotel Gurgaon"] < (3*54000)][["Double Tree by Hilton","DoubleTree by Hilton Hotel","DoubleTree by Hilton Hotel Gurgaon"]]

,Double Tree by Hilton,DoubleTree by Hilton Hotel,DoubleTree by Hilton Hotel Gurgaon
PropertyName,,,
Whiteland The Aspen,54000.0,5200.0,54000.0
Tulip Yellow,54000.0,3000.0,54000.0
ATS Marigold,54000.0,3700.0,54000.0
ROF Insignia Park,54000.0,54000.0,3600.0
Vipul World,54000.0,2400.0,54000.0
Eldeco Accolade,54000.0,54000.0,10600.0
Anant Raj Estate Plots,54000.0,4300.0,54000.0
DLF New Town Heights 1,54000.0,6000.0,54000.0
Breez Global Heights 89,54000.0,1600.0,54000.0

In [440]:
location_df.at["ROF Insignia Park", "DoubleTree by Hilton Hotel"] = 3600.0
location_df.at["Eldeco Accolade", "DoubleTree by Hilton Hotel"] = 10600.0

In [441]:
location_df[location_df["Dwaraka Expressway"] +location_df["Dwarka Expressway"]+location_df["Dwarka Expy"] < (3*54000)][["Dwaraka Expressway","Dwarka Expressway","Dwarka Expy"]]

,Dwaraka Expressway,Dwarka Expressway,Dwarka Expy
PropertyName,,,
Smartworld One DXP,54000.0,54000.0,1200.0
M3M Crown,54000.0,54000.0,3800.0
Adani Brahma Samsara Vilasa,54000.0,700.0,54000.0
Sobha City,54000.0,54000.0,5100.0
Emaar Digihomes,54000.0,2000.0,54000.0
DLF The Arbour,1200.0,54000.0,54000.0
Oxirich Chintamanis,54000.0,1700.0,54000.0
Anant Raj Estates,54000.0,1800.0,54000.0
BPTP Amstoria,54000.0,54000.0,3500.0
Signature Global City 37D Ph 2,54000.0,2900.0,54000.0
DLF Alameda,54000.0,2700.0,54000.0
Saan Verdante,54000.0,100.0,54000.0
Smart World Orchard,54000.0,2300.0,54000.0
DLF The Crest,54000.0,2500.0,54000.0
DLF The Magnolias,54000.0,1600.0,54000.0
DLF The Aralias,54000.0,1200.0,54000.0
Ansal API Esencia,54000.0,1500.0,54000.0
M3M Merlin,54000.0,5100.0,54000.0
Smart World Gems,54000.0,2900.0,54000.0
DLF Gardencity Enclave,54000.0,3700.0,54000.0
Signature Global Park,54000.0,300.0,54000.0
Rishali Luxe Residency 112,54000.0,5200.0,54000.0
Puri The Aravallis,54000.0,54000.0,2800.0
International City by SOBHA Phase 2,54000.0,54000.0,6000.0
BPTP Green Oaks,54000.0,54000.0,2500.0
Puri Emerald Bay,54000.0,54000.0,4200.0
Ireo Victory Valley,54000.0,54000.0,4100.0
DLF Gardencity,54000.0,54000.0,3400.0
Tata Primanti,54000.0,54000.0,3300.0
DLF Park Place,54000.0,54000.0,3000.0
Central Park Flower Valley,54000.0,54000.0,4000.0
Ireo Skyon,54000.0,54000.0,3400.0
AIPL The Peaceful Homes,54000.0,54000.0,1300.0
Adani M2K Oyster Grande,54000.0,54000.0,3200.0
G99,54000.0,54000.0,4800.0
Emaar MGF Emerald Floors Premier,54000.0,54000.0,2000.0
Hero Homes,54000.0,3600.0,54000.0
Central Park Flower Valley Mikasa Plots,54000.0,1400.0,54000.0
M3M Skywalk,54000.0,3800.0,54000.0
Ireo The Grand Arch,54000.0,6100.0,54000.0
JMS The Nation,54000.0,6600.0,54000.0
Suncity Avenue 76,54000.0,5000.0,54000.0
Ambience Creacions,54000.0,1900.0,54000.0
Vatika Xpressions,54000.0,3000.0,54000.0
Central Park Flower Valley Aqua Front Towers,54000.0,5600.0,54000.0
M3M Natura,54000.0,5800.0,54000.0
Parsvnath Exotica,54000.0,4300.0,54000.0
Bestech Park View Grand Spa,54000.0,5100.0,54000.0
Shree Vardhman Victoria,54000.0,4400.0,54000.0
Silverglades The Melia,54000.0,8400.0,54000.0
Shree Vardhman Flora,54000.0,6900.0,54000.0
M3M Heights,54000.0,6200.0,54000.0
Central Park Flower Valley Flamingo Floors,54000.0,1700.0,54000.0
Indiabulls Centrum Park,54000.0,4000.0,54000.0
BPTP Fortuna,54000.0,5800.0,54000.0
DLF The Pinnacle,54000.0,6300.0,54000.0
Golden Park,54000.0,6600.0,54000.0
Ireo Savannah,54000.0,4300.0,54000.0
Ashiana Amarah,54000.0,1600.0,54000.0
JMS Prime Land,54000.0,4500.0,54000.0

In [442]:
location_df.at["Smartworld One DXP", "Dwarka Expressway"] = 1200.0
location_df.at["M3M Crown", "Dwarka Expressway"] = 3800.0
location_df.at["Sobha City", "Dwarka Expressway"] = 5100.0
location_df.at["DLF The Arbour", "Dwarka Expressway"] = 1200.0
location_df.at["BPTP Amstoria", "Dwarka Expressway"] = 3500.0
location_df.at["Puri The Aravallis", "Dwarka Expressway"] = 2800.0
location_df.at["International City by SOBHA Phase 2", "Dwarka Expressway"] = 6000.0
location_df.at["BPTP Green Oaks", "Dwarka Expressway"] = 2500.0
location_df.at["Puri Emerald Bay", "Dwarka Expressway"] = 4200.0
location_df.at["Ireo Victory Valley", "Dwarka Expressway"] = 4100.0
location_df.at["DLF Gardencity", "Dwarka Expressway"] = 3400.0
location_df.at["Tata Primanti", "Dwarka Expressway"] = 3300.0
location_df.at["DLF Park Place", "Dwarka Expressway"] = 3000.0
location_df.at["Central Park Flower Valley", "Dwarka Expressway"] = 4000.0
location_df.at["Ireo Skyon", "Dwarka Expressway"] = 3400.0
location_df.at["AIPL The Peaceful Homes", "Dwarka Expressway"] = 1300.0
location_df.at["Adani M2K Oyster Grande", "Dwarka Expressway"] = 3200.0
location_df.at["G99", "Dwarka Expressway"] = 4800.0
location_df.at["Emaar MGF Emerald Floors Premier", "Dwarka Expressway"] = 2000.0

In [443]:
location_df[location_df["Dwarka Sector 21 Metro Station"] +location_df["Dwarka Sector 21 Metro station"]+location_df["Dwarka Sector 21, Metro Station"] < (3*54000)][["Dwarka Sector 21 Metro Station","Dwarka Sector 21 Metro station","Dwarka Sector 21, Metro Station"]]

,Dwarka Sector 21 Metro Station,Dwarka Sector 21 Metro station,"Dwarka Sector 21, Metro Station"
PropertyName,,,
Smartworld One DXP,54000.0,54000.0,7200.0
Sobha City,54000.0,8100.0,54000.0
BPTP Amstoria,11300.0,54000.0,54000.0
DLF Alameda,10900.0,54000.0,54000.0
Saan Verdante,10400.0,54000.0,54000.0
Pioneer Araya,8100.0,54000.0,54000.0
Signature Global Park,10000.0,54000.0,54000.0
Puri The Aravallis,9000.0,54000.0,54000.0

In [444]:
location_df.at["Smartworld One DXP", "Dwarka Sector 21 Metro Station"] = 7200.0
location_df.at["Sobha City", "Dwarka Sector 21 Metro Station"] = 8100.0

In [445]:
#location_df[location_df["Dwarka Expressway"] +location_df["Dwarka expressway"] < 108000][["Dwarka Expressway","Dwarka expressway"]]

In [446]:
location_df[location_df["Dwarka Sector 21 Metro Station"] +location_df["Dwarka sector 21 metro station"] < 108000][["Dwarka Sector 21 Metro Station","Dwarka sector 21 metro station"]]

,Dwarka Sector 21 Metro Station,Dwarka sector 21 metro station
PropertyName,,
Smartworld One DXP,7200.0,54000.0
Sobha City,8100.0,54000.0
BPTP Amstoria,11300.0,54000.0
DLF Alameda,10900.0,54000.0
Saan Verdante,10400.0,54000.0
Pioneer Araya,8100.0,54000.0
DLF Gardencity Enclave,54000.0,9900.0
Signature Global Park,10000.0,54000.0
Puri The Aravallis,9000.0,54000.0

In [447]:
location_df.at["DLF Gardencity Enclave", "Dwarka Sector 21 Metro Station"] = 9900.0

In [448]:
location_df.drop(columns=["DLF Grand Mall","DLF5 Summit Plaza","DLF World Tech Park","DLF Site central office","DLF Linear Park","DLF Cyber City","DLF Corporate Park","DLF Corporate Greens","DPS International Edge","DPS International School","DPSG Palam Vihar Gurugram","De Adventure Amusement Park","Delh-Ajmer Expy","Delhi - Jaipur Expressway","Delhi Public School Sector 84","Double Tree by Hilton","DoubleTree by Hilton Hotel Gurgaon","Dwaraka Expressway","Dwarka Expy","Dwarka Sector 21 Metro station","Dwarka Sector 21, Metro Station","Dwarka expressway","Dwarka sector 21 metro station"],inplace=True)

In [449]:
location_df.shape

(246, 993)

In [450]:
sorted(location_df.columns.to_list())

['AIIMS',
 'AIIMS Jhajjar',
 'AIPL Business Centre',
 'AIPL Business Club',
 'AIPL Business Co Working Space',
 'AIPL Business Tower',
 'AIPL Joy Street Mall',
 'APJ Abdul Kalam Park',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Ajit Stadium Dhanwapur',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Alpine Hospital',
 'Altrade Business Centre',
 'Aman Hospital',
 'Aman Hospital & Surgical Centre',
 'Ambience Mall',
 'Ambience Public School',
 'American Express',
 'Amity',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Ap Sports cricket ground',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Approved Sector 37 Mero Station',
 'Appu Ghar Water Park',
 'Aradhya Cricket Club Gurgaon',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Athena',
 'Au Grand Air',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BOB ATM',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Bamroli Cricket Ground',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Best IVF Centre',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharat Singh fuel company',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'BigBazaar',
 'Bijwasan Railway Station',
 'Biryani Shah',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CBR Cricket Ground',
 'CD International School',
 'CK Birla Hospital',
 'CNG Petrol Pump',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 "Cherub's Cradle",
 'Children Park',
 'Chirag Hospital',
 'Choice pharmacy',
 'Citibank ATM',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 'CoNexus.Life B35',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLC Cricket Ground',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPS Manesar',
 'DPS Sector 103',
 'DPSG Palam Vihar',
 'DSD College',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'Daultabad Village Park',
 'De Adventure Park',
 'Deerika HyperMart',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi Gurgaon Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Delhi-Mumbai Expressway',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'Dishoom Cinemas',
 "Domino's Pizza",
 'Double Infinity market',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dreamz Cafe',
 'Drona Sports Village',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC HOSPITAL',
 'ESIC Hospital',
 'Early Basket Grocery shop',
 'Edge towers tennis court',
 'Ektaa Hospital',
 'Ektaa Hospitals',
 'Ektaa Hospitals  Main Sohna Rd',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza',
 'Emerald Plaza Shopping Mall',
 'Enkays Hospital',
 'Entertainland Mall',
 'Ernst & Young',
 'Eros City Square',
 'Eros Corporate Park',
 'Esplanade Mall',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro Int. School',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector 37D',
 'Euro International School, Sector 84',
 'Euro International School, Sector- 109',
 'Euro International School, Sector- 109.',
 'Euro International School, sector- 51',
 'Euro Intl School Sec-51',
 'Euro Intl School, Sector 37D, Gurugram',
 'Euro Intl School, Sector- 109',
 'EuroKids Preschool Suncity',
 'Excellere World School',
 'Eye Doctors at Krishna Netralaya',
 'F9 Go Karting Gurgaon',
 'FUEL NATION',
 'Faridabad',
 'Faridabad - Gurgaon Rd',
 'Faridabad - Gurgaon Road',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fortis hospital',
 'Fresco Market',
 'Frescos',
 'Fun N Food Village',
 'Fun N Food Water Park',
 'Fun N Food WaterPark',
 'Fun N Food Waterpark',
 'G D Goenka University',
 'G D Goenka World School',
 'GD Goenka',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka School',
 'GD Goenka Signature School',
 'GD Goenka University',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Garima Public School',
 'Gaytri Public School',
 'Gd goenka university',
 'Gems International School',
 'Genesis Hospital',
 'Genesis Hospital Sector 84',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global City Centre Mall',
 'Global Foyer Mall',
 'Global Foyer Mall,  Palam Vihar',
 'Global Ways School',
 'Global city centre',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Greens Golf & Resorts Limited',
 'Golden Tulip Suites Gurgaon',
 'Golf Corse Ext. Rd.',
 'Golf Course Ext Rd',
 'Golf Course Ext Road',
 'Golf Course Extension',
 'Golf Course Extension Rd',
 'Golf Course Extension Road',
 'Golf Course Extn Road',
 'Golf Course Rd',
 'Golf Course Road',
 'Golf Pavilion',
 'Golf course extension road',
 'Govind Hospital',
 'Govt. Model Sanskriti Primary School',
 'Govt. PG College',
 'Grand Hyatt',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Green Field School',
 'Green garden narsari',
 'Greenway Hospital',
 "Guls' Kitchen",
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon - Delhi Expy, Sector 75A',
 'Gurgaon Dreamz Mall',
 'Gurgaon Faridabad Highway',
 'Gurgaon Gramin Bank',
 'Gurgaon Old Railway Station',
 'Gurgaon Railway Station',
 'Gurgaon Road',
 'Gurgaon Toll',
 'Gurgaon railway station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram City Bus Depot',
 'Gurugram Global Heights School',
 'Gurugram Hospital',
 'Gurugram Public School',
 'Gurugram Railway Station',
 'Gurugram Rd',
 'Gurugram Road',
 'Gurugram University',
 'Gurugram University Kankrola',
 'Gurugram University Sector 87',
 'Gurukul Preschool',
 'Gyaananda School',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HDFC Bank ATM, Dhunela Ghamroj',
 'HDFC Bank, Pataudi Rd',
 'HDFC bank ATM',
 'HP PETROL PUMP Unnamed Rd',
 'HP Petrol Pump',
 'HSBC',
 'HUB 66',
 'HUDA Market',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Hanuman & Shani Mandir',
 'Harsaru Village Bus Stop',
 'Haryana City Gas',
 'Hasanpur',
 'Health Care Pharmacy',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Heritage Xperiential Learning, CRPF Rd',
 'Heritage badminton academy',
 'Hero Honda Chowk',
 'Holiday Inn',
 'Holiday Inn Express Gurugram',
 'Holiday Inn Express Gurugram Sec 50',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Hotel Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Horizon 1 Mall',
 'Hotel Golf View Suites',
 'Hub 66',
 'Huda City Centre',
 'Huda City Centre Metro Station',
 'Huda Metro Station',
 'Huda Metro Station (Gurugram)',
 'Huda Metro station',
 'Huda Park',
 'Huda city center',
 'Huda metro station',
 'Hyatt Place',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency',
 'Hyatt Regency Gurgaon',
 'Hyatt Regency Gurugram',
 'Hyatt Regency Hotel',
 'ICFAI University',
 'ICICI ATM',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank',
 'ICICI Bank ATM',
 'ICICI Bank ATM, Sector 86',
 'IDFC FIRST Bank',
 'IFFCO Chowk',
 'IFFCO Chowk Metro Station',
 'IG International Airport',
 'IGI Airport',
 'IGIA Airport',
 'IILM School of Management',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'IMT Sohna',
 'INOX Cinema',
 'INXT High Street',
 'IRIS Broadway Mall',
 'ISBM College',
 'ISKCON',
 'ISKCON Temple',
 'Ibis Hotel',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperfecto Patio',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Imt Manesar',
 'Imt Manesar, Gurugram',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Airport',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi Int. Airport',
 'Indira Gandhi International Airport',
 'Indira Gandhi Intl Airport',
 'Indus World School',
 'Indus valley Public School',
 'IndusInd Bank',
 'IndusInd Bank ATM',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Infinitys Badminton Academy',
 'Info Technology Park Phase 2',
 'Insfire Sports',
 'International Airport',
 'International Tech Park Gurgaon',
 'International Tech Park Gurgaon,',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jagdish Super Market',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinaglala Theme Park',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Jungle Safari & Trails',
 'K. R. Mangalam University',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'K.R.Mangalam World School',
 'KDM Public School, Sohna',
 'KFG Sports Club',
 'KFG sports club Parking',
 'KIIT College',
 'KIIT College of Engineering',
 'KIIT College of Engineering Sohna Road',
 'KLAY Play School',
 'KMP Corridor',
 'KMP Expressway',
 'KMP corridor',
 'KR Mangalam',
 'KR Mangalam University',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Kangaroo Kids Preschool',
 'Karma Lakelands',
 'Keshav Pharmacy',
 'Khatu Shyam Mandir',
 'Kheri Railway station',
 'Kidzee',
 'Kidzee Sec-93',
 'Kinder Care Playschool',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kundli Manesar Palwal Expressway',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Learning Stars School',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel,',
 'Lemon Tree Hotel, Sohna Road',
 'Leopard hills',
 "Lingaya's Lalita Devi Institute",
 'Lions Public School',
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lotus Valley School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MCC Cricket Ground Dhankot',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Megacity Mall',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Mamta Hospital',
 'Manav Rachna School',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Marigold Secondary School',
 'Marriott Courtyard',
 'MatriKiran High School',
 'Matrikiran High School',
 'Matrikiran School',
 'Mavens Inn',
 'Mavens Orange - Hotel',
 'Max, Fortis',
 "McDonald's India",
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta Dialysis Center',
 'Medanta Hospital',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Medhaam Pre School & Daycare',
 'Medicity',
 'Meditree Market',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle / Spectra',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'Moksh Wellness Pvt Ltd.',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'N.H-8',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248',
 'NH 248 A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Neemrana Palace',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'New Water Pond',
 'Newtown Square Mall',
 'Ninex Mall',
 'Nirvana Rd',
 'Nischay Cricket Academy',
 'Nora Solomon Medicenter',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'OMAXE Gurgaon Mall',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Bengali Market',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Omex City Centre Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open Tap',
 'Open gym garden',
 'Orchid Business Park',
 'Oriental Bank of Commerce',
 "Oyster's Water Park",
 'PHC Garhi Harsaru',
 'PNB ATM',
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Park inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pataudi road',
 'Pathfinder Global School, Pataudi',
 'Pathways',
 'Pathways School Gurgaon',
 'Patil Station',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Peer Baba Ki Mazar',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Prakash Hospital',
 'Pranavananda Int. School',
 'Pranavananda International School',
 'Presidium School Gurgoan',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Propose Metro Station',
 'Proposed Metro Station',
 'Proposed Metro corridor',
 'Public Bazar',
 'Punjab National Bank',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Raheja Market',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Rajiv Chowk - Sohna Highway',
 'Ram Krishna Public School',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 55-56',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 55 56',
 'Rapid Metro Station Sector 56',
 'Rathore IMT Hospital',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCJ Academy',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UHTC Basai',
 'SGT UNIVERSITY',
 'SGT University',
 'SPM Hospital',
 'SRS Cinemas',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sanskar Jyoti School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Scottish International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 102 Dhankot',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43',
 'Sector 42-43 Metro Station',
 'Sector 42-43 Metro station',
 'Sector 42-43 Rapid Metro',
 'Sector 42-43 Rapid Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 45 SO Post Office',
 'Sector 53 Metro Station',
 'Sector 53-54',
 'Sector 53-54 Metro Station',
 'Sector 53-54 Rapid Metro',
 'Sector 53/54 Metro Station',
 'Sector 54 Chowk',
 'Sector 54 Chowk Metro Station',
 'Sector 55 Metro Station',
 'Sector 55-56 Metro',
 'Sector 55-56 Metro Station',
 'Sector 55-56 Metro station',
 'Sector 55-56 Rapid Metro',
 'Sector 55-56 Rapid Metro Station',
 'Sector 55-56 metro',
 'Sector 55-56 metro station',

In [451]:
location_df[location_df["ESIC HOSPITAL"] +location_df["ESIC Hospital"] < 108000][["ESIC HOSPITAL","ESIC Hospital"]]

                        ESIC HOSPITAL  ESIC Hospital
PropertyName
Birla Navya Avik               4200.0        54000.0
Conscient Heritage Max        54000.0         8800.0

In [452]:
location_df.at["Birla Navya Avik", "ESIC Hospital"] = 4200.0

In [453]:
location_df[location_df["Ektaa Hospital"] +location_df["Ektaa Hospitals"]+location_df["Ektaa Hospitals  Main Sohna Rd"] < (3*54000)][["Ektaa Hospital","Ektaa Hospitals","Ektaa Hospitals  Main Sohna Rd"]]

,Ektaa Hospital,Ektaa Hospitals,Ektaa Hospitals Main Sohna Rd
PropertyName,,,
Godrej Aria,54000.0,3900.0,54000.0
Ireo City Plots,1500.0,54000.0,54000.0
Raheja Vanya,54000.0,1900.0,54000.0
BPTP Pedestal,54000.0,54000.0,4000.0

In [454]:
location_df.at["Ireo City Plots", "Ektaa Hospitals"] = 1500.0
location_df.at["BPTP Pedestal", "Ektaa Hospitals"] = 4000.0

In [455]:
location_df[location_df["Emerald Plaza"] +location_df["Emerald Plaza Shopping Mall"] < 108000][["Emerald Plaza","Emerald Plaza Shopping Mall"]]

                    Emerald Plaza  Emerald Plaza Shopping Mall
PropertyName
Imperia The Esfera        54000.0                       1000.0

In [456]:
location_df["Euro Int. School"].min()

54000.0

In [457]:
location_df[location_df["Euro Int School, Sector 37D, Gurugram"] +location_df["Euro International School, Sector 37D"]+location_df["Euro Intl School, Sector 37D, Gurugram"] < (3*54000)][["Euro Int School, Sector 37D, Gurugram","Euro International School, Sector 37D","Euro Intl School, Sector 37D, Gurugram"]]

,"Euro Int School, Sector 37D, Gurugram","Euro International School, Sector 37D","Euro Intl School, Sector 37D, Gurugram"
PropertyName,,,
Godrej Meridien,54000.0,54000.0,4100.0
The Close North,54000.0,6300.0,54000.0
Ramprastha The Edge Towers,5100.0,54000.0,54000.0

In [458]:
location_df.at["Godrej Meridien", "Euro Int School, Sector 37D, Gurugram"] = 4100.0
location_df.at["The Close North", "Euro Int School, Sector 37D, Gurugram"] = 6300.0

In [459]:
location_df[location_df["Euro International School, Sec 84"] +location_df["Euro International School, Sector 84"] < 108000][["Euro International School, Sec 84","Euro International School, Sector 84"]]

,"Euro International School, Sec 84","Euro International School, Sector 84"
PropertyName,,
Whiteland Blissville,54000.0,6400.0
DLF Park Place,1600.0,54000.0
Pioneer Park,3200.0,54000.0

In [460]:
location_df.at["Whiteland Blissville", "Euro International School, Sec 84"] = 6400.0

In [461]:
location_df[location_df["Euro International School, Sector- 109"] +location_df["Euro International School, Sector- 109."]+location_df["Euro Intl School, Sector- 109"] < (3*54000)][["Euro International School, Sector- 109","Euro International School, Sector- 109.","Euro Intl School, Sector- 109"]]

,"Euro International School, Sector- 109","Euro International School, Sector- 109.","Euro Intl School, Sector- 109"
PropertyName,,,
M3M Crown,54000.0,6100.0,54000.0
Sobha City,54000.0,54000.0,4100.0
Emaar Gurgaon Greens,1900.0,54000.0,54000.0
Anant Raj Estates,2100.0,54000.0,54000.0
BPTP Amstoria,2300.0,54000.0,54000.0
Ace Palm Floors,54000.0,54000.0,2400.0

In [462]:
location_df.at["M3M Crown", "Euro International School, Sector- 109"] = 6100.0
location_df.at["Sobha City", "Euro International School, Sector- 109"] = 4100.0
location_df.at["Ace Palm Floors", "Euro International School, Sector- 109"] = 2400.0

In [463]:
location_df[location_df["Euro International School, sector- 51"] +location_df["Euro Intl School Sec-51"] < 108000][["Euro International School, sector- 51","Euro Intl School Sec-51"]]

,"Euro International School, sector- 51",Euro Intl School Sec-51
PropertyName,,
Signature Global City,54000.0,1200.0
Godrej 101,4700.0,54000.0

In [464]:
location_df.at["Signature Global City", "Euro International School, sector- 51"] = 1200.0

In [465]:
location_df[location_df["Faridabad - Gurgaon Rd"] +location_df["Faridabad - Gurgaon Road"]+location_df["Faridabad Gurgaon Road"] < (3*54000)][["Faridabad - Gurgaon Rd","Faridabad - Gurgaon Road","Faridabad Gurgaon Road"]]

,Faridabad - Gurgaon Rd,Faridabad - Gurgaon Road,Faridabad Gurgaon Road
PropertyName,,,
Godrej Nature Plus Serenity,54000.0,54000.0,7000.0
DLF Garden City Floors,54000.0,170.0,54000.0
Vatika Aspiration,7000.0,54000.0,54000.0
Experion The Westerlies,54000.0,54000.0,4900.0
Godrej Nature Plus,54000.0,6.0,54000.0
BPTP Park Generations,54000.0,54000.0,10000.0

In [466]:
location_df.at["DLF Garden City Floors", "Faridabad Gurgaon Road"] = 170.0
location_df.at["Vatika Aspiration", "Faridabad Gurgaon Road"] = 7000.0
location_df.at["Godrej Nature Plus", "Faridabad Gurgaon Road"] = 6.0

In [467]:
location_df[location_df["Fun N Food Water Park"] +location_df["Fun N Food WaterPark"]+location_df["Fun N Food Waterpark"] < (3*54000)][["Fun N Food Water Park","Fun N Food WaterPark","Fun N Food Waterpark"]]

,Fun N Food Water Park,Fun N Food WaterPark,Fun N Food Waterpark
PropertyName,,,
Smartworld One DXP,54000.0,54000.0,8800.0
4S Aradhya Homes,54000.0,3200.0,54000.0
Pioneer Araya,8100.0,54000.0,54000.0
M3M Merlin,54000.0,12100.0,54000.0

In [468]:
location_df.at["Smartworld One DXP", "Fun N Food WaterPark"] = 8800.0
location_df.at["Pioneer Araya", "Fun N Food WaterPark"] = 8100.0

In [469]:
location_df[location_df["G D Goenka University"] +location_df["GD Goenka University"]+location_df["GD Goenka University, Gurugram"] < (3*54000)][["G D Goenka University","GD Goenka University","GD Goenka University, Gurugram"]]

,G D Goenka University,GD Goenka University,"GD Goenka University, Gurugram"
PropertyName,,,
Signature Global Solera,54000.0,54000.0,4700.0
Vatika India Next Plots,54000.0,54000.0,1600.0
Signature Global Prime,1000.0,54000.0,54000.0
Vatika Express City,54000.0,2600.0,54000.0
DLF The Summit,54000.0,3500.0,54000.0
Vatika The Seven Lamps,3900.0,54000.0,54000.0

In [470]:
location_df.at["Signature Global Prime", "GD Goenka University, Gurugram"] = 1000.0
location_df.at["Vatika Express City", "GD Goenka University, Gurugram"] = 2600.0
location_df.at["DLF The Summit", "GD Goenka University, Gurugram"] = 3500.0
location_df.at["Vatika The Seven Lamps", "GD Goenka University, Gurugram"] = 3900.0

In [471]:
location_df[location_df["G D Goenka World School"] +location_df["GD Goenka World School"] < 108000][["G D Goenka World School","GD Goenka World School"]]

                          G D Goenka World School  GD Goenka World School
PropertyName
DLF The Camellias                         54000.0                  1900.0
Anant Raj Ashok Estate                    54000.0                  2100.0
Signature Global Solera                   54000.0                  5400.0
Vatika India Next Plots                   54000.0                  1400.0
MV Buildcon Precore City                  54000.0                   600.0
Signature Global Prime                    54000.0                  1700.0
Antriksh Heights                          54000.0                  1700.0
Vatika The Seven Lamps                     4000.0                 54000.0

In [472]:
location_df.at["Vatika The Seven Lamps", "GD Goenka World School"] = 4000.0

In [473]:
location_df[location_df["GD Goenka University, Gurugram"] +location_df["Gd goenka university"] < 108000][["GD Goenka University, Gurugram","Gd goenka university"]]

                         GD Goenka University, Gurugram  Gd goenka university
PropertyName
DLF The Primus                                  54000.0                3300.0
Signature Global Solera                          4700.0               54000.0
Vatika India Next Plots                          1600.0               54000.0
Signature Global Prime                           1000.0               54000.0
Vatika Express City                              2600.0               54000.0
DLF The Summit                                   3500.0               54000.0
Vatika The Seven Lamps                           3900.0               54000.0

In [474]:
location_df.at["DLF The Primus", "GD Goenka University, Gurugram"] = 3300.0

In [475]:
location_df[location_df["GEMS International School"] +location_df["Gems International School"] < 108000][["GEMS International School","Gems International School"]]

,GEMS International School,Gems International School
PropertyName,,
Adani Brahma Samsara Vilasa,5700.0,54000.0
Puri The Aravallis,6200.0,54000.0
M3M Natura,54000.0,2500.0

In [476]:
location_df.at["M3M Natura", "GEMS International School"] = 2500.0

In [477]:
location_df[location_df["Genesis Hospital Sector 84"] +location_df["Genesis Hospital"] < 108000][["Genesis Hospital","Genesis Hospital Sector 84"]]

                                Genesis Hospital  Genesis Hospital Sector 84
PropertyName
Signature Global City 37D Ph 2           54000.0                      2200.0
BPTP Green Oaks                           1500.0                     54000.0
G99                                       2500.0                     54000.0
Hero Homes                               54000.0                      7100.0
M3M Skywalk                              54000.0                       700.0
Ireo The Corridors                        3400.0                     54000.0
Ramprastha The Edge Towers                4000.0                     54000.0
Mapsko Casa Bella                         4400.0                     54000.0

In [478]:
location_df.at["Signature Global City 37D Ph 2", "Genesis Hospital"] = 2200.0
location_df.at["Hero Homes", "Genesis Hospital"] = 7100.0
location_df.at["M3M Skywalk", "Genesis Hospital"] = 700.0

In [479]:
location_df[location_df["Global City Centre"] +location_df["Global City Centre Mall"] < 108000][["Global City Centre","Global City Centre Mall"]]

                         Global City Centre  Global City Centre Mall
PropertyName
Anant Raj Ashok Estate               2400.0                  54000.0
Signature Global Solera             54000.0                   6800.0
Antriksh Heights                     3000.0                  54000.0
Vatika Express City                 54000.0                   2400.0

In [480]:
location_df.at["Signature Global Solera", "Global City Centre"] = 6800.0
location_df.at["Vatika Express City", "Global City Centre"] = 2400.0

In [481]:
location_df[location_df["Global Foyer Mall"] +location_df["Global Foyer Mall,  Palam Vihar"] < 108000][["Global Foyer Mall","Global Foyer Mall,  Palam Vihar"]]

                          Global Foyer Mall  Global Foyer Mall,  Palam Vihar
PropertyName
Emaar MGF Marbella                  54000.0                           3300.0
Emaar MGF The Palm Drive             4200.0                          54000.0

In [482]:
location_df.at["Emaar MGF Marbella", "Global Foyer Mall"] = 3300.0

In [483]:
location_df[location_df["Global City Centre"] +location_df["Global city centre"] < 108000][["Global City Centre","Global city centre"]]

                         Global City Centre  Global city centre
PropertyName
Anant Raj Ashok Estate               2400.0             54000.0
Signature Global Solera              6800.0             54000.0
Antriksh Heights                     3000.0             54000.0
Vatika Express City                  2400.0             54000.0

In [484]:
location_df["Global city centre"].min()

54000.0

In [485]:
location_df[location_df["Golden Greens Golf & Resorts"] +location_df["Golden Greens Golf & Resorts Limited"] < 108000][["Golden Greens Golf & Resorts","Golden Greens Golf & Resorts Limited"]]

,Golden Greens Golf & Resorts,Golden Greens Golf & Resorts Limited
PropertyName,,
DLF The Ultima,54000.0,9200.0
Indiabulls Enigma,8200.0,54000.0
Bellavista Central Park Resorts,6700.0,54000.0
Vatika Sovereign Next,13400.0,54000.0
Vatika Independent Floors,54000.0,11600.0
Emaar Palm Gardens,11400.0,54000.0

In [486]:
location_df.at["DLF The Ultima", "Golden Greens Golf & Resorts"] = 9200.0
location_df.at["Vatika Independent Floors", "Golden Greens Golf & Resorts"] = 11600.0

In [487]:
location_df[location_df['Golf Corse Ext. Rd.'] +location_df['Golf Course Ext Rd']+location_df['Golf Course Ext Road']+location_df["Golf Course Extension"]+location_df["Golf Course Extension Rd"]+location_df["Golf Course Extension Road"]+location_df["Golf Course Extn Road"]+location_df["Golf Course Rd"]+location_df["Golf Course Road"]+location_df["Golf course extension road"] < (10*54000)][['Golf Corse Ext. Rd.',
 'Golf Course Ext Rd',
 'Golf Course Ext Road',
 'Golf Course Extension',
 'Golf Course Extension Rd',
 'Golf Course Extension Road',
 'Golf Course Extn Road',
 'Golf Course Rd',
 'Golf Course Road',
 'Golf course extension road']]

,Golf Corse Ext. Rd.,Golf Course Ext Rd,Golf Course Ext Road,Golf Course Extension,Golf Course Extension Rd,Golf Course Extension Road,Golf Course Extn Road,Golf Course Rd,Golf Course Road,Golf course extension road
PropertyName,,,,,,,,,,
Elan The Presidential,54000.0,54000.0,3800.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Tulip Monsella,54000.0,54000.0,54000.0,54000.0,54000.0,1400.0,54000.0,54000.0,54000.0,54000.0
Birla Navya,54000.0,54000.0,1100.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Skycity,54000.0,900.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
SS The Leaf,54000.0,54000.0,2500.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Tulip Yellow,54000.0,54000.0,2200.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Golfestate,54000.0,54000.0,1100.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
ATS Marigold,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,1100.0,54000.0
ROF Insignia Park,54000.0,99.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Indiabulls Enigma,54000.0,54000.0,54000.0,54000.0,54000.0,13600.0,54000.0,54000.0,54000.0,54000.0
Central Park Flower Valley Mikasa Plots,54000.0,54000.0,54000.0,54000.0,54000.0,13200.0,54000.0,54000.0,54000.0,54000.0
Ramprastha Primera,54000.0,54000.0,6600.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Experion The Heartsong,54000.0,54000.0,54000.0,54000.0,54000.0,2900.0,54000.0,54000.0,54000.0,54000.0
DLF New Town Heights 2,54000.0,54000.0,54000.0,54000.0,54000.0,3900.0,54000.0,54000.0,54000.0,54000.0
DLF The Skycourt,54000.0,54000.0,54000.0,54000.0,54000.0,3300.0,54000.0,54000.0,54000.0,54000.0
Central Park Resorts,7600.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Anand Niketan,54000.0,54000.0,54000.0,54000.0,54000.0,7100.0,54000.0,54000.0,54000.0,54000.0
Godrej Aria,54000.0,54000.0,54000.0,54000.0,6300.0,54000.0,54000.0,54000.0,54000.0,54000.0
Ansals Shiva Som Valley,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,1400.0,54000.0
Vipul World,54000.0,54000.0,2400.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Emaar Imperial Gardens,54000.0,54000.0,54000.0,54000.0,54000.0,4400.0,54000.0,54000.0,54000.0,54000.0
Ireo City Plots,54000.0,54000.0,54000.0,54000.0,54000.0,5000.0,54000.0,54000.0,54000.0,54000.0
Corona Optus,54000.0,2800.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Anant Raj Estate Plots,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,1300.0,54000.0
Vatika Sovereign Next,54000.0,5100.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Central Park Flower Valley The Room,54000.0,15000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Sky Lofts,54000.0,7600.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Vatika Gurgaon 21,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,5600.0,54000.0
Orchid IVY Floors,54000.0,54000.0,54000.0,2300.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Landmark The Homes 81,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,650.0,54000.0
ILD Grand,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,160.0,54000.0,54000.0
Signature Global Solera 2,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,23.0,54000.0
BPTP Pedestal,54000.0,54000.0,54000.0,54000.0,54000.0,54000.0,200.0,54000.0,54000.0,54000.0

In [488]:
location_df.at["Elan The Presidential", "Golf Course Extension Road"] = 3800.0
location_df.at["Birla Navya", "Golf Course Extension Road"] = 1100.0
location_df.at["M3M Skycity", "Golf Course Extension Road"] = 900.0
location_df.at["SS The Leaf", "Golf Course Extension Road"] = 2500.0
location_df.at["Tulip Yellow", "Golf Course Extension Road"] = 2200.0
location_df.at["M3M Golfestate", "Golf Course Extension Road"] = 1100.0
location_df.at["ATS Marigold", "Golf Course Extension Road"] = 1100.0
location_df.at["ROF Insignia Park", "Golf Course Extension Road"] = 99.0
location_df.at["Ramprastha Primera", "Golf Course Extension Road"] = 6600.0
location_df.at["Central Park Resorts", "Golf Course Extension Road"] = 7600.0
location_df.at["Godrej Aria", "Golf Course Extension Road"] = 6300.0
location_df.at["Ansals Shiva Som Valley", "Golf Course Extension Road"] = 1400.0
location_df.at["Vipul World", "Golf Course Extension Road"] = 2400.0
location_df.at["Corona Optus", "Golf Course Extension Road"] = 2800.0
location_df.at["Anant Raj Estate Plots", "Golf Course Extension Road"] = 1300.0
location_df.at["Vatika Sovereign Next", "Golf Course Extension Road"] = 5100.0
location_df.at["Central Park Flower Valley The Room", "Golf Course Extension Road"] = 15000.0
location_df.at["M3M Sky Lofts", "Golf Course Extension Road"] = 7600.0
location_df.at["Vatika Gurgaon 21", "Golf Course Extension Road"] = 5600.0
location_df.at["Orchid IVY Floors", "Golf Course Extension Road"] = 2300.0
location_df.at["Landmark The Homes 81", "Golf Course Extension Road"] = 650.0
location_df.at["ILD Grand", "Golf Course Extension Road"] = 160.0
location_df.at["Signature Global Solera 2", "Golf Course Extension Road"] = 23.0
location_df.at["BPTP Pedestal", "Golf Course Extension Road"] = 200.0

In [489]:
location_df.drop(columns=["ESIC HOSPITAL","Ektaa Hospital","Ektaa Hospitals  Main Sohna Rd","Emerald Plaza","Euro International School, Sector 37D","Euro Intl School, Sector 37D, Gurugram","Euro Int. School","Euro International School, Sector 84","Euro International School, Sector- 109.","Euro Intl School, Sector- 109","Euro Intl School Sec-51","Faridabad - Gurgaon Rd","Faridabad - Gurgaon Road","Fun N Food Water Park","Fun N Food Waterpark","G D Goenka University","GD Goenka University","G D Goenka World School","Gd goenka university","Gems International School","Genesis Hospital Sector 84","Global City Centre Mall","Global Foyer Mall,  Palam Vihar","Global city centre","Golden Greens Golf & Resorts Limited","Golf Corse Ext. Rd.","Golf Course Ext Rd","Golf Course Ext Road","Golf Course Extension","Golf Course Extension Rd","Golf Course Extn Road","Golf Course Rd","Golf Course Road","Golf course extension road"],inplace=True)

In [490]:
location_df.shape

(246, 959)

In [491]:
sorted(location_df.columns.to_list())

['AIIMS',
 'AIIMS Jhajjar',
 'AIPL Business Centre',
 'AIPL Business Club',
 'AIPL Business Co Working Space',
 'AIPL Business Tower',
 'AIPL Joy Street Mall',
 'APJ Abdul Kalam Park',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Ajit Stadium Dhanwapur',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Alpine Hospital',
 'Altrade Business Centre',
 'Aman Hospital',
 'Aman Hospital & Surgical Centre',
 'Ambience Mall',
 'Ambience Public School',
 'American Express',
 'Amity',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Ap Sports cricket ground',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Approved Sector 37 Mero Station',
 'Appu Ghar Water Park',
 'Aradhya Cricket Club Gurgaon',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Athena',
 'Au Grand Air',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BOB ATM',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Bamroli Cricket Ground',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Best IVF Centre',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharat Singh fuel company',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'BigBazaar',
 'Bijwasan Railway Station',
 'Biryani Shah',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CBR Cricket Ground',
 'CD International School',
 'CK Birla Hospital',
 'CNG Petrol Pump',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 "Cherub's Cradle",
 'Children Park',
 'Chirag Hospital',
 'Choice pharmacy',
 'Citibank ATM',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 'CoNexus.Life B35',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLC Cricket Ground',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPS Manesar',
 'DPS Sector 103',
 'DPSG Palam Vihar',
 'DSD College',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'Daultabad Village Park',
 'De Adventure Park',
 'Deerika HyperMart',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi Gurgaon Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Delhi-Mumbai Expressway',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'Dishoom Cinemas',
 "Domino's Pizza",
 'Double Infinity market',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dreamz Cafe',
 'Drona Sports Village',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Early Basket Grocery shop',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Enkays Hospital',
 'Entertainland Mall',
 'Ernst & Young',
 'Eros City Square',
 'Eros Corporate Park',
 'Esplanade Mall',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'EuroKids Preschool Suncity',
 'Excellere World School',
 'Eye Doctors at Krishna Netralaya',
 'F9 Go Karting Gurgaon',
 'FUEL NATION',
 'Faridabad',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fortis hospital',
 'Fresco Market',
 'Frescos',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Garima Public School',
 'Gaytri Public School',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. Model Sanskriti Primary School',
 'Govt. PG College',
 'Grand Hyatt',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Green Field School',
 'Green garden narsari',
 'Greenway Hospital',
 "Guls' Kitchen",
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon - Delhi Expy, Sector 75A',
 'Gurgaon Dreamz Mall',
 'Gurgaon Faridabad Highway',
 'Gurgaon Gramin Bank',
 'Gurgaon Old Railway Station',
 'Gurgaon Railway Station',
 'Gurgaon Road',
 'Gurgaon Toll',
 'Gurgaon railway station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram City Bus Depot',
 'Gurugram Global Heights School',
 'Gurugram Hospital',
 'Gurugram Public School',
 'Gurugram Railway Station',
 'Gurugram Rd',
 'Gurugram Road',
 'Gurugram University',
 'Gurugram University Kankrola',
 'Gurugram University Sector 87',
 'Gurukul Preschool',
 'Gyaananda School',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HDFC Bank ATM, Dhunela Ghamroj',
 'HDFC Bank, Pataudi Rd',
 'HDFC bank ATM',
 'HP PETROL PUMP Unnamed Rd',
 'HP Petrol Pump',
 'HSBC',
 'HUB 66',
 'HUDA Market',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Hanuman & Shani Mandir',
 'Harsaru Village Bus Stop',
 'Haryana City Gas',
 'Hasanpur',
 'Health Care Pharmacy',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Heritage Xperiential Learning, CRPF Rd',
 'Heritage badminton academy',
 'Hero Honda Chowk',
 'Holiday Inn',
 'Holiday Inn Express Gurugram',
 'Holiday Inn Express Gurugram Sec 50',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Hotel Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Horizon 1 Mall',
 'Hotel Golf View Suites',
 'Hub 66',
 'Huda City Centre',
 'Huda City Centre Metro Station',
 'Huda Metro Station',
 'Huda Metro Station (Gurugram)',
 'Huda Metro station',
 'Huda Park',
 'Huda city center',
 'Huda metro station',
 'Hyatt Place',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency',
 'Hyatt Regency Gurgaon',
 'Hyatt Regency Gurugram',
 'Hyatt Regency Hotel',
 'ICFAI University',
 'ICICI ATM',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank',
 'ICICI Bank ATM',
 'ICICI Bank ATM, Sector 86',
 'IDFC FIRST Bank',
 'IFFCO Chowk',
 'IFFCO Chowk Metro Station',
 'IG International Airport',
 'IGI Airport',
 'IGIA Airport',
 'IILM School of Management',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'IMT Sohna',
 'INOX Cinema',
 'INXT High Street',
 'IRIS Broadway Mall',
 'ISBM College',
 'ISKCON',
 'ISKCON Temple',
 'Ibis Hotel',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperfecto Patio',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Imt Manesar',
 'Imt Manesar, Gurugram',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Airport',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi Int. Airport',
 'Indira Gandhi International Airport',
 'Indira Gandhi Intl Airport',
 'Indus World School',
 'Indus valley Public School',
 'IndusInd Bank',
 'IndusInd Bank ATM',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Infinitys Badminton Academy',
 'Info Technology Park Phase 2',
 'Insfire Sports',
 'International Airport',
 'International Tech Park Gurgaon',
 'International Tech Park Gurgaon,',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jagdish Super Market',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinaglala Theme Park',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Jungle Safari & Trails',
 'K. R. Mangalam University',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'K.R.Mangalam World School',
 'KDM Public School, Sohna',
 'KFG Sports Club',
 'KFG sports club Parking',
 'KIIT College',
 'KIIT College of Engineering',
 'KIIT College of Engineering Sohna Road',
 'KLAY Play School',
 'KMP Corridor',
 'KMP Expressway',
 'KMP corridor',
 'KR Mangalam',
 'KR Mangalam University',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Kangaroo Kids Preschool',
 'Karma Lakelands',
 'Keshav Pharmacy',
 'Khatu Shyam Mandir',
 'Kheri Railway station',
 'Kidzee',
 'Kidzee Sec-93',
 'Kinder Care Playschool',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kundli Manesar Palwal Expressway',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Learning Stars School',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel,',
 'Lemon Tree Hotel, Sohna Road',
 'Leopard hills',
 "Lingaya's Lalita Devi Institute",
 'Lions Public School',
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lotus Valley School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MCC Cricket Ground Dhankot',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Megacity Mall',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Mamta Hospital',
 'Manav Rachna School',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Marigold Secondary School',
 'Marriott Courtyard',
 'MatriKiran High School',
 'Matrikiran High School',
 'Matrikiran School',
 'Mavens Inn',
 'Mavens Orange - Hotel',
 'Max, Fortis',
 "McDonald's India",
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta Dialysis Center',
 'Medanta Hospital',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Medhaam Pre School & Daycare',
 'Medicity',
 'Meditree Market',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle / Spectra',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'Moksh Wellness Pvt Ltd.',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'N.H-8',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248',
 'NH 248 A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Neemrana Palace',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'New Water Pond',
 'Newtown Square Mall',
 'Ninex Mall',
 'Nirvana Rd',
 'Nischay Cricket Academy',
 'Nora Solomon Medicenter',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'OMAXE Gurgaon Mall',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Bengali Market',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Omex City Centre Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open Tap',
 'Open gym garden',
 'Orchid Business Park',
 'Oriental Bank of Commerce',
 "Oyster's Water Park",
 'PHC Garhi Harsaru',
 'PNB ATM',
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Park inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pataudi road',
 'Pathfinder Global School, Pataudi',
 'Pathways',
 'Pathways School Gurgaon',
 'Patil Station',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Peer Baba Ki Mazar',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Prakash Hospital',
 'Pranavananda Int. School',
 'Pranavananda International School',
 'Presidium School Gurgoan',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Propose Metro Station',
 'Proposed Metro Station',
 'Proposed Metro corridor',
 'Public Bazar',
 'Punjab National Bank',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Raheja Market',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Rajiv Chowk - Sohna Highway',
 'Ram Krishna Public School',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 55-56',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 55 56',
 'Rapid Metro Station Sector 56',
 'Rathore IMT Hospital',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCJ Academy',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UHTC Basai',
 'SGT UNIVERSITY',
 'SGT University',
 'SPM Hospital',
 'SRS Cinemas',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sanskar Jyoti School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Scottish International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 102 Dhankot',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43',
 'Sector 42-43 Metro Station',
 'Sector 42-43 Metro station',
 'Sector 42-43 Rapid Metro',
 'Sector 42-43 Rapid Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 45 SO Post Office',
 'Sector 53 Metro Station',
 'Sector 53-54',
 'Sector 53-54 Metro Station',
 'Sector 53-54 Rapid Metro',
 'Sector 53/54 Metro Station',
 'Sector 54 Chowk',
 'Sector 54 Chowk Metro Station',
 'Sector 55 Metro Station',
 'Sector 55-56 Metro',
 'Sector 55-56 Metro Station',
 'Sector 55-56 Metro station',
 'Sector 55-56 Rapid Metro',
 'Sector 55-56 Rapid Metro Station',
 'Sector 55-56 metro',
 'Sector 55-56 metro station',
 'Sector 55-56 rapid metro station',
 'Sector 55/56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shaheed Bhagat Singh Chowk',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shikshantar - Primary School',
 'Shishu Kalyan School',
 'Shiskshantar',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shiva Temple Tigra',
 'Shivai Hospital',
 'Shivani public school',
 'Shoppers Stop',
 'Shopping complex',
 'Shree Balaji College',
 'Shree Deep Petrol Pump',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Shri Hanuman Ji Mandir',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Hospital',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Hospital',

In [492]:
location_df[location_df["Grand Hyatt"] +location_df["Grand Hyatt Gurgaon"] < 108000][["Grand Hyatt","Grand Hyatt Gurgaon"]]

                                     Grand Hyatt  Grand Hyatt Gurgaon
PropertyName
Eldeco Acclaim                           54000.0               6100.0
Experion The Westerlies                  54000.0               1700.0
International City by Sobha Phase 1      54000.0               1400.0

In [493]:
location_df[location_df["Green Field Public School"] +location_df["Green Field School"] < 108000][["Green Field Public School","Green Field School"]]

                     Green Field Public School  Green Field School
PropertyName
Emaar Digihomes                        54000.0              1000.0
Yash Vihar                              1400.0             54000.0
Adani Samsara Avasa                     1100.0             54000.0
M3M Woodshire                            750.0             54000.0

In [494]:
location_df.at["Emaar Digihomes", "Green Field Public School"] = 1000.0

In [495]:
location_df[location_df["Gurgaon - Delhi Expy"] +location_df["Gurgaon - Delhi Expy, Sector 75A"] < 108000][["Gurgaon - Delhi Expy","Gurgaon - Delhi Expy, Sector 75A"]]

                  Gurgaon - Delhi Expy  Gurgaon - Delhi Expy, Sector 75A
PropertyName
M3M Golf Hills                 54000.0                            7900.0
Tulip Monsella                  3700.0                           54000.0
Tulip Yellow                   14100.0                           54000.0
4S Aradhya Homes                4800.0                           54000.0
DLF Park Place                  2900.0                           54000.0
G99                             1900.0                           54000.0
ILD Grand                      10800.0                           54000.0

In [496]:
location_df.at["M3M Golf Hills", "Gurgaon - Delhi Expy"] = 7900.0

In [497]:
location_df[location_df["Gurgaon - Delhi Expy"] +location_df["Delhi Gurgaon Expressway"] < 108000][["Gurgaon - Delhi Expy","Delhi Gurgaon Expressway"]]

                     Gurgaon - Delhi Expy  Delhi Gurgaon Expressway
PropertyName
M3M Golf Hills                     7900.0                   54000.0
Tulip Monsella                     3700.0                   54000.0
Tulip Yellow                      14100.0                   54000.0
Saan Verdante                     54000.0                    8400.0
4S Aradhya Homes                   4800.0                   54000.0
Smart World Orchard               54000.0                    9000.0
DLF Park Place                     2900.0                   54000.0
G99                                1900.0                   54000.0
Mapsko The Icon 79                54000.0                    3200.0
ILD Grand                         10800.0                   54000.0

In [498]:
location_df.at["Saan Verdante", "Gurgaon - Delhi Expy"] = 8400.0
location_df.at["Smart World Orchard", "Gurgaon - Delhi Expy"] = 9000.0
location_df.at["Mapsko The Icon 79", "Gurgaon - Delhi Expy"] = 3200.0

In [499]:
location_df[location_df["Faridabad Gurgaon Road"] +location_df["Gurgaon Faridabad Highway"] < 108000][["Faridabad Gurgaon Road","Gurgaon Faridabad Highway"]]

                             Faridabad Gurgaon Road  Gurgaon Faridabad Highway
PropertyName
Godrej Nature Plus Serenity                  7000.0                    54000.0
DLF Garden City Floors                        170.0                    54000.0
Vatika Aspiration                            7000.0                    54000.0
Experion The Westerlies                      4900.0                    54000.0
Godrej Nature Plus                              6.0                    54000.0
BPTP Park Generations                       10000.0                    54000.0

In [500]:
location_df[location_df["Gurgaon Railway Station"] +location_df["Gurgaon railway station"]+location_df["Gurugram Railway Station"] < (3*54000)][["Gurgaon Railway Station","Gurgaon railway station","Gurugram Railway Station"]]

,Gurgaon Railway Station,Gurgaon railway station,Gurugram Railway Station
PropertyName,,,
Smartworld One DXP,4900.0,54000.0,54000.0
Adani Brahma Samsara Vilasa,2500.0,54000.0,54000.0
Sobha City,6500.0,54000.0,54000.0
Whiteland The Aspen,15600.0,54000.0,54000.0
Elan The Presidential,17800.0,54000.0,54000.0
DLF The Arbour,5200.0,54000.0,54000.0
Emaar Gurgaon Greens,3200.0,54000.0,54000.0
Oxirich Chintamanis,13900.0,54000.0,54000.0
DLF Garden City Floors,19500.0,54000.0,54000.0
Anant Raj Estates,1600.0,54000.0,54000.0
Tulip Yellow,17200.0,54000.0,54000.0
BPTP Amstoria,4000.0,54000.0,54000.0
Emaar Emerald Hills,13000.0,54000.0,54000.0
M3M Golfestate,16000.0,54000.0,54000.0
ATS Triumph,16100.0,54000.0,54000.0
ATS Marigold,15400.0,54000.0,54000.0
Signature Global City 37D Ph 2,12400.0,54000.0,54000.0
DLF Alameda,4200.0,54000.0,54000.0
Experion Windchants,2800.0,54000.0,54000.0
Saan Verdante,3400.0,54000.0,54000.0
4S Aradhya Homes,8300.0,54000.0,54000.0
Yash Vihar,7500.0,54000.0,54000.0
Smart World Orchard,4400.0,54000.0,54000.0
DLF The Camellias,24200.0,54000.0,54000.0
Birla Navya Avik,8100.0,54000.0,54000.0
Adani Samsara Avasa,8700.0,54000.0,54000.0
DLF The Crest,9300.0,54000.0,54000.0
DLF The Magnolias,7800.0,54000.0,54000.0
DLF The Aralias,3300.0,54000.0,54000.0
Ansal API Esencia,7000.0,54000.0,54000.0
DLF Gardencity Enclave,54000.0,6200.0,54000.0
Ashiana Amarah,54000.0,54000.0,1100.0

In [501]:
location_df.at["DLF Gardencity Enclave", "Gurgaon Railway Station"] = 6200.0
location_df.at["Ashiana Amarah", "Gurgaon Railway Station"] = 1100.0

In [502]:
location_df[location_df["Gurgaon Road"] +location_df["Gurugram Rd"]+location_df["Gurugram Road"] < (3*54000)][["Gurgaon Road","Gurugram Rd","Gurugram Road"]]

                         Gurgaon Road  Gurugram Rd  Gurugram Road
PropertyName
Yash Vihar                    54000.0      54000.0         1100.0
Adani Samsara Avasa            1500.0      54000.0        54000.0
DLF The Magnolias             54000.0      54000.0         1300.0
Ansal API Esencia             54000.0      54000.0         1000.0
AIPL The Peaceful Homes       54000.0      54000.0          220.0

In [503]:
location_df.at["Adani Samsara Avasa", "Gurugram Road"] = 1500.0

In [506]:
location_df[location_df["Gurugram University"] +location_df["Gurugram University Kankrola"]+location_df["Gurugram University Sector 87"] < (3*54000)][["Gurugram University","Gurugram University Kankrola","Gurugram University Sector 87"]]

,Gurugram University,Gurugram University Kankrola,Gurugram University Sector 87
PropertyName,,,
Signature Global City 93,3600.0,54000.0,54000.0
Bestech Altura,5200.0,54000.0,54000.0
Signature Global City 92,4100.0,54000.0,54000.0
Signature Global City 81,4100.0,54000.0,54000.0
SS Linden Floors,4300.0,54000.0,54000.0
M3M Golf Hills,10600.0,54000.0,54000.0
Whiteland Blissville,10300.0,54000.0,54000.0
Krisumi Waterfall Residences,8800.0,54000.0,54000.0
M3M Capital,4700.0,54000.0,54000.0
Signature Global City,2200.0,54000.0,54000.0
Godrej Nature Plus Serenity,3300.0,54000.0,54000.0
SS The Leaf,3700.0,54000.0,54000.0
Emaar Emerald Hills,6800.0,54000.0,54000.0
Yash Vihar,10800.0,54000.0,54000.0
BPTP Green Oaks,15700.0,54000.0,54000.0
Adani M2K Oyster Grande,16400.0,54000.0,54000.0
G99,12500.0,54000.0,54000.0
Central Park Resorts,10300.0,54000.0,54000.0
Shree Vardhman Flora,6500.0,54000.0,6500.0
Bellavista Central Park Resorts,7000.0,54000.0,54000.0
DLF The Grove,7800.0,54000.0,54000.0
Corona Optus,4500.0,54000.0,54000.0
Vatika Independent Floors,16100.0,54000.0,54000.0
Ireo The Corridors,15000.0,54000.0,54000.0
Bestech Park View Sanskruti,16500.0,54000.0,54000.0
Bestech Park View Ananda,6200.0,54000.0,54000.0
Optimal ultra luxury builder floors,4300.0,54000.0,54000.0

In [505]:
location_df.at["Shree Vardhman Flora", "Gurugram University"] = 6500.0

In [509]:
location_df[location_df["HDFC Bank"] +location_df["HDFC Bank, Pataudi Rd"] < 108000][["HDFC Bank","HDFC Bank, Pataudi Rd"]]

                                HDFC Bank  HDFC Bank, Pataudi Rd
PropertyName
Umang Winter Hills                 1600.0                 1600.0
BPTP Mansions Park Prime           2200.0                54000.0
Emaar Mgf Palm Terraces Select      950.0                54000.0

In [508]:
location_df.at["Umang Winter Hills", "HDFC Bank"] = 1600.0

In [512]:
location_df[location_df["HDFC Bank ATM"] +location_df["HDFC Bank ATM, Dhunela Ghamroj"]+location_df["HDFC bank ATM"] < (3*54000)][["HDFC Bank ATM","HDFC Bank ATM, Dhunela Ghamroj","HDFC bank ATM"]]

,HDFC Bank ATM,"HDFC Bank ATM, Dhunela Ghamroj",HDFC bank ATM
PropertyName,,,
Vatika The Seven Lamps,1200.0,1200.0,54000.0
La Lagune,2500.0,54000.0,54000.0

In [511]:
location_df.at["Vatika The Seven Lamps", "HDFC Bank ATM"] = 1200.0

In [516]:
location_df[location_df["HP PETROL PUMP Unnamed Rd"] +location_df["HP Petrol Pump"] < 108000][["HP PETROL PUMP Unnamed Rd","HP Petrol Pump"]]

                          HP PETROL PUMP Unnamed Rd  HP Petrol Pump
PropertyName
BPTP Mansions Park Prime                     2600.0          2600.0

In [515]:
location_df.at["BPTP Mansions Park Prime", "HP Petrol Pump"] = 2600.0

In [519]:
location_df[location_df["HUDA Market"] +location_df["HUDA Market, Sector 14"] < 108000][["HUDA Market","HUDA Market, Sector 14"]]

                     HUDA Market  HUDA Market, Sector 14
PropertyName
Saan Verdante            54000.0                  8000.0
Smart World Orchard      54000.0                  9600.0
DLF The Aralias          54000.0                  7900.0
Ambience Creacions       13600.0                 13600.0
Ashiana Amarah            3000.0                  3000.0

In [518]:
location_df.at["Ambience Creacions", "HUDA Market, Sector 14"] = 13600.0
location_df.at["Ashiana Amarah", "HUDA Market, Sector 14"] = 3000.0

In [520]:
location_df[location_df["Health Care Pharmacy"] +location_df["Health care pharmacy"] < 108000][["Health Care Pharmacy","Health care pharmacy"]]

                    Health Care Pharmacy  Health care pharmacy
PropertyName
Ireo The Corridors               54000.0                4300.0

In [524]:
location_df[location_df["Heritage Badminton Academy"] +location_df["Heritage badminton academy"] < 108000][["Heritage Badminton Academy","Heritage badminton academy"]]

,Heritage Badminton Academy,Heritage badminton academy
PropertyName,,
Yash Vihar,1100.0,1100.0
Shree Vardhman Victoria,8300.0,54000.0

In [523]:
location_df.at["Yash Vihar", "Heritage Badminton Academy"] = 1100.0

In [528]:
location_df[location_df["Heritage Xperiential Learning School"] +location_df["Heritage Xperiential Learning, CRPF Rd"] < 108000][["Heritage Xperiential Learning School","Heritage Xperiential Learning, CRPF Rd"]]

,Heritage Xperiential Learning School,"Heritage Xperiential Learning, CRPF Rd"
PropertyName,,
Tulip Yellow,2300.0,2300.0
ATS Triumph,1200.0,54000.0
ROF Insignia Park,2000.0,54000.0
Experion The Heartsong,1400.0,54000.0
Vipul World,1100.0,54000.0
Emaar Imperial Gardens,1700.0,54000.0
Vatika City,3000.0,54000.0

In [527]:
location_df.at["Tulip Yellow", "Heritage Xperiential Learning School"] = 2300.0

In [532]:
location_df[location_df["Holiday Inn"]+location_df["Holiday Inn Express Gurugram"]+location_df["Holiday Inn Express Gurugram Sec 50"] +location_df["Holiday Inn Express Gurugram Sector 50"] +location_df["Holiday Inn Gurugram"] < (5*54000)][["Holiday Inn","Holiday Inn Express Gurugram","Holiday Inn Express Gurugram Sec 50","Holiday Inn Express Gurugram Sector 50","Holiday Inn Gurugram"]]

,Holiday Inn,Holiday Inn Express Gurugram,Holiday Inn Express Gurugram Sec 50,Holiday Inn Express Gurugram Sector 50,Holiday Inn Gurugram
PropertyName,,,,,
Signature Global City 92,54000.0,2700.0,54000.0,2700.0,54000.0
Emaar Emerald Hills,54000.0,54000.0,54000.0,6200.0,54000.0
Godrej Oasis,54000.0,54000.0,54000.0,4400.0,4400.0
Optimal ultra luxury builder floors,54000.0,54000.0,3800.0,3800.0,54000.0
Satya The Hermitage,54000.0,54000.0,54000.0,3200.0,3200.0

In [531]:
location_df.at["Signature Global City 92", "Holiday Inn Express Gurugram Sector 50"] = 2700.0
location_df.at["Godrej Oasis", "Holiday Inn Express Gurugram Sector 50"] = 4400.0
location_df.at["Optimal ultra luxury builder floors", "Holiday Inn Express Gurugram Sector 50"] = 3800.0
location_df.at["Satya The Hermitage", "Holiday Inn Express Gurugram Sector 50"] = 3200.0

In [535]:
location_df[location_df["Holiday Inn Gurugram Sector 90"] +location_df["Holiday Inn Hotel Sector 90"] < 108000][["Holiday Inn Gurugram Sector 90","Holiday Inn Hotel Sector 90"]]

,Holiday Inn Gurugram Sector 90,Holiday Inn Hotel Sector 90
PropertyName,,
Oxirich Chintamanis,2700.0,54000.0
Signature Global City 37D Ph 2,4100.0,54000.0
Yash Vihar,12900.0,54000.0
International City by SOBHA Phase 2,9100.0,54000.0
Ireo Victory Valley,2300.0,54000.0
AIPL The Peaceful Homes,11900.0,54000.0
Hero Homes,8700.0,8700.0
M3M Skywalk,3000.0,3000.0
JMS The Nation,3100.0,54000.0
Ambience Creacions,10500.0,54000.0
M3M Sierra 68,1700.0,1700.0
Tulip Violet,1900.0,54000.0
Suncity Platinum Towers,7200.0,54000.0
Bestech Park View Grand Spa,2500.0,54000.0
Shree Vardhman Victoria,5500.0,54000.0
Indiabulls Centrum Park,9000.0,54000.0
Emaar The Palm Springs,2000.0,54000.0
Umang Winter Hills,1600.0,54000.0

In [534]:
location_df.at["Hero Homes", "Holiday Inn Gurugram Sector 90"] = 8700.0
location_df.at["M3M Skywalk", "Holiday Inn Gurugram Sector 90"] = 3000.0
location_df.at["M3M Sierra 68", "Holiday Inn Gurugram Sector 90"] = 1700.0

In [538]:
location_df[location_df["Hub 66"] +location_df["HUB 66"] < 108000][["Hub 66","HUB 66"]]

                                 Hub 66  HUB 66
PropertyName
Signature Global City 81        54000.0  2700.0
SS Linden Floors                54000.0  2600.0
Emaar Mgf Palm Terraces Select   1600.0  1600.0

In [537]:
location_df.at["Emaar Mgf Palm Terraces Select", "HUB 66"] = 1600.0

In [542]:
location_df[location_df["Huda City Centre Metro Station"]+location_df["Huda Metro Station"]+location_df["Huda Metro Station (Gurugram)"] +location_df["Huda Metro station"] +location_df["Huda metro station"] < (5*54000)][["Huda City Centre Metro Station","Huda Metro Station","Huda Metro Station (Gurugram)","Huda Metro station","Huda metro station"]]

,Huda City Centre Metro Station,Huda Metro Station,Huda Metro Station (Gurugram),Huda Metro station,Huda metro station
PropertyName,,,,,
Adani Brahma Samsara Vilasa,54000.0,11000.0,54000.0,54000.0,54000.0
M3M Capital,54000.0,5900.0,54000.0,54000.0,54000.0
Signature Global City,54000.0,4800.0,4800.0,54000.0,54000.0
Godrej 101,54000.0,8100.0,54000.0,54000.0,54000.0
SS The Leaf,54000.0,9000.0,9000.0,54000.0,54000.0
DLF The Aralias,54000.0,11600.0,54000.0,54000.0,54000.0
DLF Park Place,54000.0,18100.0,18100.0,54000.0,54000.0
AIPL The Peaceful Homes,54000.0,13900.0,54000.0,54000.0,54000.0
Eldeco Accolade,54000.0,7300.0,54000.0,54000.0,54000.0
M3M Natura,8200.0,8200.0,54000.0,54000.0,54000.0
ROF Insignia Park 2,54000.0,9900.0,9900.0,54000.0,54000.0
Indiabulls Centrum Park,54000.0,13700.0,13700.0,54000.0,54000.0
Mapsko The Icon 79,54000.0,6600.0,54000.0,54000.0,54000.0
BPTP Park Serene,54000.0,16000.0,54000.0,54000.0,54000.0
Landmark The Homes 81,54000.0,6800.0,54000.0,6800.0,54000.0
Pioneer Park,54000.0,19500.0,19500.0,54000.0,54000.0
Suncity Avenue 102,5800.0,5800.0,54000.0,54000.0,54000.0

In [541]:
location_df.at["Signature Global City", "Huda Metro Station"] = 4800.0
location_df.at["SS The Leaf", "Huda Metro Station"] = 9000.0
location_df.at["DLF Park Place", "Huda Metro Station"] = 18100.0
location_df.at["M3M Natura", "Huda Metro Station"] = 8200.0
location_df.at["ROF Insignia Park 2", "Huda Metro Station"] = 9900.0
location_df.at["Indiabulls Centrum Park", "Huda Metro Station"] = 13700.0
location_df.at["Landmark The Homes 81", "Huda Metro Station"] = 6800.0
location_df.at["Pioneer Park", "Huda Metro Station"] = 19500.0
location_df.at["Suncity Avenue 102", "Huda Metro Station"] = 5800.0

In [549]:
location_df[location_df["Hyatt Place"] +location_df["Hyatt Place Gurgaon Udyog Vihar"] < 108000][["Hyatt Place","Hyatt Place Gurgaon Udyog Vihar"]]

                    Hyatt Place  Hyatt Place Gurgaon Udyog Vihar
PropertyName
Smartworld One DXP      54000.0                           7700.0
4S Aradhya Homes        54000.0                            650.0
Pioneer Araya            6100.0                           6100.0

In [548]:
location_df.at["Pioneer Araya", "Hyatt Place Gurgaon Udyog Vihar"] = 6100.0

In [552]:
location_df[location_df["Hyatt Regency"] +location_df["Hyatt Regency Gurgaon"]+location_df["Hyatt Regency Gurugram"]+location_df["Hyatt Regency Hotel"] < (4*54000)][["Hyatt Regency","Hyatt Regency Gurgaon","Hyatt Regency Gurugram","Hyatt Regency Hotel"]]

,Hyatt Regency,Hyatt Regency Gurgaon,Hyatt Regency Gurugram,Hyatt Regency Hotel
PropertyName,,,,
Whiteland Blissville,54000.0,4500.0,54000.0,54000.0
SS The Leaf,54000.0,12600.0,54000.0,12600.0
Emaar MGF Emerald Floors Premier,54000.0,3900.0,54000.0,54000.0
DLF The Ultima,54000.0,3900.0,3900.0,54000.0
Central Park Resorts,54000.0,7500.0,54000.0,54000.0
Central Park Flower Valley Aqua Front Towers,54000.0,4900.0,54000.0,54000.0
Pioneer Urban Presidia,54000.0,2200.0,54000.0,54000.0
Silverglades The Melia,54000.0,4400.0,54000.0,54000.0
Vatika Seven Elements,3200.0,3200.0,54000.0,54000.0
Adani Brahma Samsara,54000.0,5200.0,54000.0,54000.0
Vatika Sovereign Next,54000.0,18000.0,54000.0,54000.0
Central Park Flower Valley The Room,54000.0,3900.0,54000.0,54000.0
Ireo Savannah,54000.0,5600.0,54000.0,54000.0
BPTP Park Serene,54000.0,3600.0,54000.0,54000.0
Puri Diplomatic Greens,54000.0,3000.0,54000.0,54000.0
Ireo The Corridors,54000.0,8800.0,54000.0,54000.0

In [551]:
location_df.at["SS The Leaf", "Hyatt Regency Gurgaon"] = 12600.0
location_df.at["DLF The Ultima", "Hyatt Regency Gurgaon"] = 3900.0
location_df.at["Vatika Seven Elements", "Hyatt Regency Gurgaon"] = 3200.0

In [546]:
location_df["Huda City Centre"].min()

54000.0

In [553]:
location_df.drop(columns=["AIIMS","AIIMS Jhajjar","Grand Hyatt","Green Field School","Gurgaon - Delhi Expy, Sector 75A","Delhi Gurgaon Expressway","Gurgaon Faridabad Highway","Gurgaon railway station","Gurugram Railway Station","Gurgaon Road","Gurugram Rd","Gurugram University Kankrola","Gurugram University Sector 87","HDFC Bank, Pataudi Rd","HDFC Bank ATM, Dhunela Ghamroj","HDFC bank ATM","HP PETROL PUMP Unnamed Rd","HUDA Market","Health Care Pharmacy","Heritage badminton academy","Heritage Xperiential Learning, CRPF Rd","Holiday Inn","Holiday Inn Express Gurugram","Holiday Inn Express Gurugram Sec 50","Holiday Inn Gurugram","Holiday Inn Hotel Sector 90","Hub 66","Huda metro station","Huda City Centre Metro Station","Huda Metro Station (Gurugram)","Huda Metro station","Huda City Centre","Huda city center","Hyatt Place","Hyatt Regency","Hyatt Regency Gurugram","Hyatt Regency Hotel"],inplace=True)

In [554]:
location_df.shape

(246, 922)

In [555]:
sorted(location_df.columns.to_list())

['AIPL Business Centre',
 'AIPL Business Club',
 'AIPL Business Co Working Space',
 'AIPL Business Tower',
 'AIPL Joy Street Mall',
 'APJ Abdul Kalam Park',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Ajit Stadium Dhanwapur',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Alpine Hospital',
 'Altrade Business Centre',
 'Aman Hospital',
 'Aman Hospital & Surgical Centre',
 'Ambience Mall',
 'Ambience Public School',
 'American Express',
 'Amity',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Ap Sports cricket ground',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Approved Sector 37 Mero Station',
 'Appu Ghar Water Park',
 'Aradhya Cricket Club Gurgaon',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Athena',
 'Au Grand Air',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BOB ATM',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Bamroli Cricket Ground',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Best IVF Centre',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharat Singh fuel company',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'BigBazaar',
 'Bijwasan Railway Station',
 'Biryani Shah',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CBR Cricket Ground',
 'CD International School',
 'CK Birla Hospital',
 'CNG Petrol Pump',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 "Cherub's Cradle",
 'Children Park',
 'Chirag Hospital',
 'Choice pharmacy',
 'Citibank ATM',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 'CoNexus.Life B35',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLC Cricket Ground',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPS Manesar',
 'DPS Sector 103',
 'DPSG Palam Vihar',
 'DSD College',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'Daultabad Village Park',
 'De Adventure Park',
 'Deerika HyperMart',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Delhi-Mumbai Expressway',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'Dishoom Cinemas',
 "Domino's Pizza",
 'Double Infinity market',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dreamz Cafe',
 'Drona Sports Village',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Early Basket Grocery shop',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Enkays Hospital',
 'Entertainland Mall',
 'Ernst & Young',
 'Eros City Square',
 'Eros Corporate Park',
 'Esplanade Mall',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'EuroKids Preschool Suncity',
 'Excellere World School',
 'Eye Doctors at Krishna Netralaya',
 'F9 Go Karting Gurgaon',
 'FUEL NATION',
 'Faridabad',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fortis hospital',
 'Fresco Market',
 'Frescos',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Garima Public School',
 'Gaytri Public School',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. Model Sanskriti Primary School',
 'Govt. PG College',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Green garden narsari',
 'Greenway Hospital',
 "Guls' Kitchen",
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon Dreamz Mall',
 'Gurgaon Gramin Bank',
 'Gurgaon Old Railway Station',
 'Gurgaon Railway Station',
 'Gurgaon Toll',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram City Bus Depot',
 'Gurugram Global Heights School',
 'Gurugram Hospital',
 'Gurugram Public School',
 'Gurugram Road',
 'Gurugram University',
 'Gurukul Preschool',
 'Gyaananda School',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HP Petrol Pump',
 'HSBC',
 'HUB 66',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Hanuman & Shani Mandir',
 'Harsaru Village Bus Stop',
 'Haryana City Gas',
 'Hasanpur',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Hero Honda Chowk',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Horizon 1 Mall',
 'Hotel Golf View Suites',
 'Huda Metro Station',
 'Huda Park',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency Gurgaon',
 'ICFAI University',
 'ICICI ATM',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank',
 'ICICI Bank ATM',
 'ICICI Bank ATM, Sector 86',
 'IDFC FIRST Bank',
 'IFFCO Chowk',
 'IFFCO Chowk Metro Station',
 'IG International Airport',
 'IGI Airport',
 'IGIA Airport',
 'IILM School of Management',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'IMT Sohna',
 'INOX Cinema',
 'INXT High Street',
 'IRIS Broadway Mall',
 'ISBM College',
 'ISKCON',
 'ISKCON Temple',
 'Ibis Hotel',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperfecto Patio',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Imt Manesar',
 'Imt Manesar, Gurugram',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Airport',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi Int. Airport',
 'Indira Gandhi International Airport',
 'Indira Gandhi Intl Airport',
 'Indus World School',
 'Indus valley Public School',
 'IndusInd Bank',
 'IndusInd Bank ATM',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Infinitys Badminton Academy',
 'Info Technology Park Phase 2',
 'Insfire Sports',
 'International Airport',
 'International Tech Park Gurgaon',
 'International Tech Park Gurgaon,',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jagdish Super Market',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinaglala Theme Park',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Jungle Safari & Trails',
 'K. R. Mangalam University',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'K.R.Mangalam World School',
 'KDM Public School, Sohna',
 'KFG Sports Club',
 'KFG sports club Parking',
 'KIIT College',
 'KIIT College of Engineering',
 'KIIT College of Engineering Sohna Road',
 'KLAY Play School',
 'KMP Corridor',
 'KMP Expressway',
 'KMP corridor',
 'KR Mangalam',
 'KR Mangalam University',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Kangaroo Kids Preschool',
 'Karma Lakelands',
 'Keshav Pharmacy',
 'Khatu Shyam Mandir',
 'Kheri Railway station',
 'Kidzee',
 'Kidzee Sec-93',
 'Kinder Care Playschool',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kundli Manesar Palwal Expressway',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Learning Stars School',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel,',
 'Lemon Tree Hotel, Sohna Road',
 'Leopard hills',
 "Lingaya's Lalita Devi Institute",
 'Lions Public School',
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lotus Valley School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MCC Cricket Ground Dhankot',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Megacity Mall',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Mamta Hospital',
 'Manav Rachna School',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Marigold Secondary School',
 'Marriott Courtyard',
 'MatriKiran High School',
 'Matrikiran High School',
 'Matrikiran School',
 'Mavens Inn',
 'Mavens Orange - Hotel',
 'Max, Fortis',
 "McDonald's India",
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta Dialysis Center',
 'Medanta Hospital',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Medhaam Pre School & Daycare',
 'Medicity',
 'Meditree Market',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle / Spectra',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'Moksh Wellness Pvt Ltd.',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'N.H-8',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248',
 'NH 248 A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Neemrana Palace',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'New Water Pond',
 'Newtown Square Mall',
 'Ninex Mall',
 'Nirvana Rd',
 'Nischay Cricket Academy',
 'Nora Solomon Medicenter',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'OMAXE Gurgaon Mall',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Bengali Market',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Omex City Centre Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open Tap',
 'Open gym garden',
 'Orchid Business Park',
 'Oriental Bank of Commerce',
 "Oyster's Water Park",
 'PHC Garhi Harsaru',
 'PNB ATM',
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Park inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pataudi road',
 'Pathfinder Global School, Pataudi',
 'Pathways',
 'Pathways School Gurgaon',
 'Patil Station',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Peer Baba Ki Mazar',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Prakash Hospital',
 'Pranavananda Int. School',
 'Pranavananda International School',
 'Presidium School Gurgoan',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Propose Metro Station',
 'Proposed Metro Station',
 'Proposed Metro corridor',
 'Public Bazar',
 'Punjab National Bank',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Raheja Market',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Rajiv Chowk - Sohna Highway',
 'Ram Krishna Public School',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 55-56',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 55 56',
 'Rapid Metro Station Sector 56',
 'Rathore IMT Hospital',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCJ Academy',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UHTC Basai',
 'SGT UNIVERSITY',
 'SGT University',
 'SPM Hospital',
 'SRS Cinemas',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sanskar Jyoti School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Scottish International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 102 Dhankot',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43',
 'Sector 42-43 Metro Station',
 'Sector 42-43 Metro station',
 'Sector 42-43 Rapid Metro',
 'Sector 42-43 Rapid Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 45 SO Post Office',
 'Sector 53 Metro Station',
 'Sector 53-54',
 'Sector 53-54 Metro Station',
 'Sector 53-54 Rapid Metro',
 'Sector 53/54 Metro Station',
 'Sector 54 Chowk',
 'Sector 54 Chowk Metro Station',
 'Sector 55 Metro Station',
 'Sector 55-56 Metro',
 'Sector 55-56 Metro Station',
 'Sector 55-56 Metro station',
 'Sector 55-56 Rapid Metro',
 'Sector 55-56 Rapid Metro Station',
 'Sector 55-56 metro',
 'Sector 55-56 metro station',
 'Sector 55-56 rapid metro station',
 'Sector 55/56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shaheed Bhagat Singh Chowk',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shikshantar - Primary School',
 'Shishu Kalyan School',
 'Shiskshantar',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shiva Temple Tigra',
 'Shivai Hospital',
 'Shivani public school',
 'Shoppers Stop',
 'Shopping complex',
 'Shree Balaji College',
 'Shree Deep Petrol Pump',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Shri Hanuman Ji Mandir',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Hospital',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Hospital',
 'Silver Streak Multi Speciality',
 'Silver Streak Multi Speciality Hospital',
 'Singhania University, Manesar',
 'SkyJumper Trampoline Park',
 'SkyJumper Trampoline Park Gurgaon',
 'Skylark Cricket Academy',
 'Skyview Corporate Park',
 'Smart View Hotel and Resort',
 'Sneh Hospital',
 'Society Park',
 "Sodhi's Supermarket, Sector 82",
 'Sohna Bus Stand',
 'Sohna Gurgaon Road',
 'Sohna Hill Viewpoint',
 'Sohna Rd',
 'Sohna Road',
 'Sohna road dhunela',
 'Solitaire Banquet Hall',
 'South point Mall',
 'Southern Peripheral Rd',
 'Southern Peripheral Rd, Dhani',
 'Southern Peripheral Rd, Gurugram',
 'Southern Peripheral Road',
 'Southern Periphery Road',
 'Spaze Business Park',
 'Spaze Itech Park',
 'Spaze Palazo, Golf Course Ext Rd',
 'Spazedge IT Park',
 'Spectra Hospital',
 'Splendor Trade Tower',
 'SportsCube Center(Sports Complex)',
 'Sri Ma Montessori International',
 'St Pauls School',
 'St Xavier High School',
 "St. Angel's Global",

In [558]:
location_df[location_df["AIPL Business Centre"] +location_df["AIPL Business Club"]+location_df["AIPL Business Co Working Space"]+location_df["AIPL Business Tower"] < (4*54000)][["AIPL Business Centre","AIPL Business Club","AIPL Business Co Working Space","AIPL Business Tower"]]

,AIPL Business Centre,AIPL Business Club,AIPL Business Co Working Space,AIPL Business Tower
PropertyName,,,,
Signature Global City 93,54000.0,160.0,54000.0,160.0
ROF Insignia Park,54000.0,2700.0,54000.0,54000.0
Experion The Heartsong,54000.0,2400.0,2400.0,54000.0
Corona Optus,54000.0,2200.0,54000.0,54000.0
ROF Insignia Park 2,9800.0,9800.0,54000.0,54000.0

In [557]:
location_df.at["Signature Global City 93", "AIPL Business Club"] = 160.0
location_df.at["Experion The Heartsong", "AIPL Business Club"] = 2400.0
location_df.at["ROF Insignia Park 2", "AIPL Business Club"] = 9800.0

In [560]:
location_df[location_df["Aman Hospital"] +location_df["Aman Hospital & Surgical Centre"]+location_df["Amma Hospital"] < (3*54000)][["Aman Hospital","Aman Hospital & Surgical Centre","Amma Hospital"]]

,Aman Hospital,Aman Hospital & Surgical Centre,Amma Hospital
PropertyName,,,
Central Park Flower Valley Mikasa Plots,54000.0,54000.0,1000.0

In [563]:
location_df[location_df["ICICI ATM"]+location_df["ICICI BANK ATM, Annapurna MKT"]+location_df["ICICI Bank ATM"] +location_df["ICICI Bank ATM, Sector 86"] +location_df["ICICI Bank"] < (5*54000)][["ICICI ATM","ICICI BANK ATM, Annapurna MKT","ICICI Bank ATM","ICICI Bank ATM, Sector 86","ICICI Bank"]]

,ICICI ATM,"ICICI BANK ATM, Annapurna MKT",ICICI Bank ATM,"ICICI Bank ATM, Sector 86",ICICI Bank
PropertyName,,,,,
Umang Winter Hills,54000.0,54000.0,54000.0,2300.0,54000.0
BPTP Mansions Park Prime,850.0,54000.0,54000.0,54000.0,54000.0
Yashika 104,54000.0,1100.0,54000.0,54000.0,54000.0
Suncity Avenue 102,54000.0,54000.0,2400.0,54000.0,54000.0

In [568]:
location_df[location_df["IG International Airport"] +location_df["IGI Airport"]+location_df["IGIA Airport"] < (3*54000)][["IG International Airport","IGI Airport","IGIA Airport"]]

,IG International Airport,IGI Airport,IGIA Airport
PropertyName,,,
Whiteland The Aspen,54000.0,22700.0,54000.0
DLF The Arbour,54000.0,16400.0,54000.0
Godrej Nature Plus Serenity,54000.0,22500.0,54000.0
M3M Merlin,54000.0,19300.0,54000.0
Emaar MGF The Palm Drive,54000.0,16500.0,54000.0
Ashiana Amarah,54000.0,21300.0,54000.0
Emaar The Palm Springs,54000.0,31000.0,54000.0
BPTP Park Serene,54000.0,27900.0,54000.0
Orchid IVY Floors,54000.0,22500.0,54000.0
Raheja Vanya,54000.0,22800.0,54000.0
Paras Ekam Homes,54000.0,19400.0,54000.0
Landmark The Homes 81,54000.0,17200.0,54000.0
ROF Normanton Park,54000.0,35300.0,54000.0
Yashika 104,54000.0,5000.0,5000.0

In [567]:
location_df.at["Yashika 104", "IGI Airport"] = 5000.0

In [569]:
location_df[location_df["IMT Office Sohna"] +location_df["IMT Sohna"] < 108000][["IMT Office Sohna","IMT Sohna"]]

                        IMT Office Sohna  IMT Sohna
PropertyName
Signature Global Prime            8000.0    54000.0

In [578]:
location_df[location_df["IFFCO Chowk"] +location_df["Iffco Chowk"] < 108000][["IFFCO Chowk","Iffco Chowk"]]

                    IFFCO Chowk  Iffco Chowk
PropertyName
Emaar Palm Heights      54000.0        500.0
La Lagune                6600.0       6600.0

In [577]:
location_df.at["La Lagune", "Iffco Chowk"] = 6600.0

In [581]:
location_df[location_df["IFFCO Chowk Metro Station"] +location_df["Iffco Chowk Metro Station"] < 108000][["IFFCO Chowk Metro Station","Iffco Chowk Metro Station"]]

                  IFFCO Chowk Metro Station  Iffco Chowk Metro Station
PropertyName
Smart World Gems                    12200.0                    12200.0
DLF The Grove                       54000.0                     1300.0

In [580]:
location_df.at["Smart World Gems", "Iffco Chowk Metro Station"] = 12200.0

In [584]:
location_df[location_df["IMT Manesar"] +location_df["Imt Manesar"]+location_df["Imt Manesar, Gurugram"] < (3*54000)][["IMT Manesar","Imt Manesar","Imt Manesar, Gurugram"]]

,IMT Manesar,Imt Manesar,"Imt Manesar, Gurugram"
PropertyName,,,
Signature Global City 37D Ph 2,9500.0,54000.0,54000.0
DLF The Crest,13000.0,54000.0,54000.0
Indiabulls Enigma,9200.0,54000.0,54000.0
M3M Skywalk,8100.0,8100.0,54000.0
Ireo The Grand Arch,16000.0,54000.0,54000.0
JMS The Nation,6100.0,54000.0,54000.0
Central Park Resorts,15500.0,54000.0,54000.0
Suncity Avenue 76,15500.0,54000.0,54000.0
M3M Sierra 68,5900.0,5900.0,54000.0
Central Park Flower Valley Aqua Front Towers,8100.0,54000.0,54000.0
Parsvnath Exotica,14200.0,54000.0,54000.0
Suncity Platinum Towers,12600.0,54000.0,54000.0
Silverglades The Melia,10000.0,54000.0,54000.0
Shree Vardhman Flora,9100.0,54000.0,54000.0
M3M Heights,5200.0,54000.0,54000.0
Indiabulls Centrum Park,14400.0,54000.0,54000.0
DLF The Pinnacle,7700.0,54000.0,54000.0
Godrej Oasis,10000.0,10000.0,54000.0
Vatika Sovereign Park,16900.0,54000.0,54000.0
Central Park Flower Valley The Room,8800.0,54000.0,54000.0
Golden Park,6600.0,54000.0,54000.0
Silverglades Hightown Residences,7700.0,54000.0,7700.0

In [583]:
location_df.at["M3M Skywalk", "IMT Manesar"] = 8100.0
location_df.at["M3M Sierra 68", "IMT Manesar"] = 5900.0
location_df.at["Godrej Oasis", "IMT Manesar"] = 10000.0
location_df.at["Silverglades Hightown Residences", "IMT Manesar"] = 7700.0

In [596]:
pd.set_option('display.max_rows', None)

In [610]:
location_df[location_df["International Airport"]+location_df["Indira Gandhi International Airport"]  < (2*54000)][["International Airport","Indira Gandhi International Airport"]]

,International Airport,Indira Gandhi International Airport
PropertyName,,
Smartworld One DXP,54000.0,14700.0
M3M Crown,54000.0,15600.0
Adani Brahma Samsara Vilasa,54000.0,20800.0
Sobha City,54000.0,16100.0
Signature Global City 93,54000.0,24800.0
Whiteland The Aspen,54000.0,22700.0
Bestech Altura,54000.0,25200.0
Elan The Presidential,54000.0,21000.0
Signature Global City 92,54000.0,24200.0
Signature Global City 79B,54000.0,23600.0
DLF The Arbour,54000.0,16400.0
Signature Global City 81,54000.0,24100.0
SS Linden Floors,54000.0,22700.0
Mahindra Luminare,54000.0,25600.0
M3M Golf Hills,54000.0,25300.0
Whiteland Blissville,54000.0,26500.0
Tulip Monsella,54000.0,22800.0
Krisumi Waterfall Residences,54000.0,25400.0
M3M Capital,54000.0,18900.0
Godrej Meridien,54000.0,28500.0
Birla Navya,54000.0,22500.0
Signature Global City,54000.0,19000.0
Godrej 101,54000.0,21500.0
M3M Soulitude,54000.0,25800.0
M3M Skycity,54000.0,22800.0
Godrej Nature Plus Serenity,54000.0,22500.0
SS The Leaf,54000.0,22800.0
Eldeco Acclaim,54000.0,24100.0
Emaar Gurgaon Greens,54000.0,17800.0
Oxirich Chintamanis,54000.0,27700.0
DLF Garden City Floors,54000.0,21300.0
Tulip Yellow,54000.0,20400.0
BPTP Amstoria,54000.0,19500.0
Emaar Emerald Hills,54000.0,24100.0
M3M Golfestate,54000.0,19300.0
ATS Triumph,54000.0,21800.0
ATS Marigold,54000.0,17500.0
DLF Alameda,54000.0,18100.0
Experion Windchants,54000.0,23700.0
Saan Verdante,54000.0,18900.0
4S Aradhya Homes,54000.0,11000.0
Yash Vihar,54000.0,22800.0
Smart World Orchard,54000.0,22800.0
DLF The Camellias,54000.0,35300.0
Adani Samsara Avasa,54000.0,23200.0
DLF The Magnolias,54000.0,25000.0
DLF The Aralias,54000.0,21700.0
Pioneer Araya,54000.0,14100.0
M3M Merlin,54000.0,19300.0
Smart World Gems,54000.0,22100.0
Vatika Aspiration,54000.0,14700.0
Ace Palm Floors,54000.0,19600.0
DLF Gardencity Enclave,54000.0,17700.0
Emaar Palm Heights,54000.0,15500.0
Signature Global Park,54000.0,15000.0
Emaar MGF Marbella,54000.0,16900.0
Rishali Luxe Residency 112,54000.0,21800.0
Puri The Aravallis,54000.0,16700.0
International City by SOBHA Phase 2,54000.0,25300.0
Emaar MGF The Palm Drive,54000.0,16500.0
BPTP Green Oaks,54000.0,28000.0
Ireo Victory Valley,54000.0,31000.0
DLF Gardencity,54000.0,24200.0
Tata Primanti,54000.0,30000.0
DLF Park Place,54000.0,28000.0
Central Park Flower Valley,54000.0,32700.0
Ireo Skyon,54000.0,29200.0
AIPL The Peaceful Homes,54000.0,25300.0
Adani M2K Oyster Grande,54000.0,28600.0
G99,54000.0,24700.0
Emaar MGF Emerald Floors Premier,54000.0,28100.0
ROF Insignia Park,54000.0,21100.0
DLF The Ultima,54000.0,25900.0
Indiabulls Enigma,54000.0,31000.0
Experion The Westerlies,54000.0,20600.0
Hero Homes,54000.0,26600.0
Central Park Flower Valley Mikasa Plots,54000.0,24300.0
M3M Skywalk,54000.0,29900.0
Ireo The Grand Arch,54000.0,25700.0
JMS The Nation,54000.0,32400.0
Imperia The Esfera,54000.0,22800.0
Ramprastha Primera,54000.0,27500.0
Experion The Heartsong,54000.0,20600.0
DLF New Town Heights 2,54000.0,24800.0
DLF The Primus,54000.0,34500.0
DLF The Skycourt,54000.0,24000.0
Central Park Resorts,54000.0,29100.0
Suncity Avenue 76,54000.0,27700.0
International City by Sobha Phase 1,54000.0,21100.0
Ambience Creacions,54000.0,24500.0
Vatika Xpressions,54000.0,20500.0
M3M Sierra 68,54000.0,31600.0
Anand Niketan,54000.0,25900.0
DLF The Belaire,54000.0,31200.0
Godrej Aria,54000.0,30300.0
Ansals Shiva Som Valley,54000.0,15600.0
Vipul World,54000.0,19900.0
Central Park Flower Valley Aqua Front Towers,54000.0,30000.0
Tulip Violet,54000.0,30500.0
Eldeco Accolade,54000.0,20300.0
M3M Natura,54000.0,20400.0
Emaar Imperial Gardens,54000.0,21000.0
Ireo City Plots,54000.0,23400.0
Parsvnath Exotica,54000.0,25400.0
Pioneer Urban Presidia,54000.0,27300.0
Suncity Platinum Towers,54000.0,28300.0
Godrej Nature Plus,54000.0,20100.0
Bestech Park View Grand Spa,54000.0,32400.0
Shree Vardhman Victoria,54000.0,31000.0
Silverglades The Melia,54000.0,29500.0
Shree Vardhman Flora,54000.0,32700.0
Vatika Seven Elements,54000.0,28500.0
Bellavista Central Park Resorts,54000.0,27800.0
M3M Heights,54000.0,34300.0
Adani Brahma Samsara,54000.0,31500.0
DLF The Grove,54000.0,16100.0
Corona Optus,54000.0,20400.0
Central Park Flower Valley Flamingo Floors,54000.0,19400.0
ROF Insignia Park 2,54000.0,24800.0
Indiabulls Centrum Park,54000.0,26500.0
BPTP Fortuna,54000.0,34200.0
Bestech Park View Spa Next,54000.0,35800.0
DLF The Pinnacle,54000.0,29600.0
Godrej Oasis,54000.0,28200.0
Anant Raj Estate Plots,54000.0,15500.0
Mapsko The Icon 79,54000.0,19600.0
DLF The Icon,54000.0,20200.0
Vatika Sovereign Park,54000.0,28500.0
Vatika Sovereign Next,54000.0,22600.0
Central Park Flower Valley The Room,54000.0,28900.0
M3M Sky Lofts,54000.0,15200.0
Golden Park,54000.0,32500.0
Ashiana Amarah,54000.0,21300.0
Vatika City,54000.0,23100.0
DLF New Town Heights 1,54000.0,22900.0
Vatika Independent Floors,54000.0,31400.0
Emaar Palm Gardens,54000.0,31200.0
The Close North,54000.0,22800.0
Emaar The Palm Springs,54000.0,31000.0
BPTP Park Serene,54000.0,27900.0
Orchid IVY Floors,54000.0,22500.0
Paras Ekam Homes,54000.0,19400.0
Landmark The Homes 81,54000.0,17200.0
ROF Normanton Park,54000.0,35300.0
Silverglades Hightown Residences,54000.0,29400.0
Pioneer Park,54000.0,29400.0
Anant Raj Ashok Estate,54000.0,37100.0
Paras Dews,54000.0,35600.0
Bestech Park View Sanskruti,54000.0,30100.0
Signature Global the Millennia,54000.0,23000.0
Orchid Island,54000.0,32100.0
Ramprastha The Edge Towers,54000.0,30200.0
Bestech Park View Ananda,54000.0,20100.0
Mapsko Casa Bella,54000.0,30900.0
Mahindra Aura,54000.0,33400.0
Godrej Air,54000.0,36700.0
Conscient Habitat,54000.0,16900.0
Conscient Heritage Max,54000.0,36500.0
Vipul Belmonte,54000.0,16300.0
Unitech The Residences,54000.0,40900.0
ILD Grand,54000.0,16800.0
Signature Global Solera 2,54000.0,14500.0
Signature Global Solera,54000.0,40900.0
M3M Woodshire,54000.0,25900.0
Vatika India Next Plots,54000.0,35800.0
MV Buildcon Precore City,54000.0,36600.0
Lion Infra Green Valley,54000.0,32600.0
Yashika 104,54000.0,5000.0

In [601]:
location_df.at["M3M Crown", "Indira Gandhi International Airport"] = 15600.0
location_df.at["Adani Brahma Samsara Vilasa", "Indira Gandhi International Airport"] = 20800.0
location_df.at["Sobha City", "Indira Gandhi International Airport"] = 16100.0
location_df.at["Signature Global City 93", "Indira Gandhi International Airport"] = 24800.0
location_df.at["Elan The Presidential", "Indira Gandhi International Airport"] = 21000.0
location_df.at["Signature Global City 79B", "Indira Gandhi International Airport"] = 23600.0
location_df.at["Mahindra Luminare", "Indira Gandhi International Airport"] = 25600.0
location_df.at["M3M Golf Hills", "Indira Gandhi International Airport"] = 25300.0
location_df.at["Whiteland Blissville", "Indira Gandhi International Airport"] = 26500.0
location_df.at["Krisumi Waterfall Residences", "Indira Gandhi International Airport"] = 25400.0
location_df.at["M3M Capital", "Indira Gandhi International Airport"] = 18900.0
location_df.at["Godrej Meridien", "Indira Gandhi International Airport"] = 28500.0
location_df.at["Birla Navya", "Indira Gandhi International Airport"] = 22500.0
location_df.at["Signature Global City", "Indira Gandhi International Airport"] = 19000.0
location_df.at["Godrej 101", "Indira Gandhi International Airport"] = 21500.0
location_df.at["M3M Soulitude", "Indira Gandhi International Airport"] = 25800.0
location_df.at["M3M Skycity", "Indira Gandhi International Airport"] = 22800.0
location_df.at["Eldeco Acclaim", "Indira Gandhi International Airport"] = 24100.0
location_df.at["Emaar Gurgaon Greens", "Indira Gandhi International Airport"] = 17800.0
location_df.at["DLF Garden City Floors", "Indira Gandhi International Airport"] = 21300.0
location_df.at["Tulip Yellow", "Indira Gandhi International Airport"] = 20400.0
location_df.at["BPTP Amstoria", "Indira Gandhi International Airport"] = 19500.0
location_df.at["Emaar Emerald Hills", "Indira Gandhi International Airport"] = 24100.0
location_df.at["M3M Golfestate", "Indira Gandhi International Airport"] = 19300.0
location_df.at["ATS Triumph", "Indira Gandhi International Airport"] = 21800.0
location_df.at["DLF Alameda", "Indira Gandhi International Airport"] = 18100.0
location_df.at["DLF The Camellias", "Indira Gandhi International Airport"] = 35300.0
location_df.at["Ace Palm Floors", "Indira Gandhi International Airport"] = 19600.0
location_df.at["Emaar Palm Heights", "Indira Gandhi International Airport"] = 15500.0
location_df.at["Emaar MGF Marbella", "Indira Gandhi International Airport"] = 16900.0
location_df.at["Puri The Aravallis", "Indira Gandhi International Airport"] = 16700.0
location_df.at["BPTP Green Oaks", "Indira Gandhi International Airport"] = 28000.0
location_df.at["DLF Gardencity", "Indira Gandhi International Airport"] = 24200.0
location_df.at["Tata Primanti", "Indira Gandhi International Airport"] = 30000.0
location_df.at["DLF Park Place", "Indira Gandhi International Airport"] = 28000.0
location_df.at["Central Park Flower Valley", "Indira Gandhi International Airport"] = 32700.0
location_df.at["Ireo Skyon", "Indira Gandhi International Airport"] = 29200.0
location_df.at["AIPL The Peaceful Homes", "Indira Gandhi International Airport"] = 25300.0
location_df.at["Adani M2K Oyster Grande", "Indira Gandhi International Airport"] = 28600.0
location_df.at["G99", "Indira Gandhi International Airport"] = 24700.0
location_df.at["Emaar MGF Emerald Floors Premier", "Indira Gandhi International Airport"] = 28100.0
location_df.at["Golden Park", "Indira Gandhi International Airport"] = 32500.0
location_df.at["Vatika City", "Indira Gandhi International Airport"] = 23100.0
location_df.at["DLF New Town Heights 1", "Indira Gandhi International Airport"] = 22900.0
location_df.at["Emaar Palm Gardens", "Indira Gandhi International Airport"] = 31200.0
location_df.at["The Close North", "Indira Gandhi International Airport"] = 22800.0
location_df.at["Silverglades Hightown Residences", "Indira Gandhi International Airport"] = 29400.0
location_df.at["Pioneer Park", "Indira Gandhi International Airport"] = 29400.0
location_df.at["Paras Dews", "Indira Gandhi International Airport"] = 35600.0
location_df.at["Bestech Park View Sanskruti", "Indira Gandhi International Airport"] = 30100.0
location_df.at["Signature Global the Millennia", "Indira Gandhi International Airport"] = 23000.0
location_df.at["Orchid Island", "Indira Gandhi International Airport"] = 32100.0
location_df.at["Ramprastha The Edge Towers", "Indira Gandhi International Airport"] = 30200.0
location_df.at["Bestech Park View Ananda", "Indira Gandhi International Airport"] = 20100.0
location_df.at["Mapsko Casa Bella", "Indira Gandhi International Airport"] = 30900.0
location_df.at["Mahindra Aura", "Indira Gandhi International Airport"] = 33400.0
location_df.at["Godrej Air", "Indira Gandhi International Airport"] = 36700.0
location_df.at["Conscient Habitat", "Indira Gandhi International Airport"] = 16900.0
location_df.at["Conscient Heritage Max", "Indira Gandhi International Airport"] = 36500.0
location_df.at["Vipul Belmonte", "Indira Gandhi International Airport"] = 16300.0
location_df.at["ILD Grand", "Indira Gandhi International Airport"] = 16800.0
location_df.at["Unitech The Residences", "Indira Gandhi International Airport"] = 40900.0
location_df.at["Signature Global Solera 2", "Indira Gandhi International Airport"] = 14500.0
location_df.at["Signature Global Solera", "Indira Gandhi International Airport"] = 40900.0
location_df.at["M3M Woodshire", "Indira Gandhi International Airport"] = 25900.0
location_df.at["Vatika India Next Plots", "Indira Gandhi International Airport"] = 35800.0
location_df.at["MV Buildcon Precore City", "Indira Gandhi International Airport"] = 36600.0
location_df.at["Lion Infra Green Valley", "Indira Gandhi International Airport"] = 32600.0

In [590]:
location_df.at["Anant Raj Ashok Estate", "Indira Gandhi Int. Airport"] = 37100.0

In [593]:
location_df.at["Vatika Independent Floors", "IGI Airport"] = 31400.0
location_df.at["Anant Raj Ashok Estate", "IGI Airport"] = 37100.0

In [598]:
location_df.at["Whiteland The Aspen", "Indira Gandhi International Airport"] = 22700.0
location_df.at["DLF The Arbour", "Indira Gandhi International Airport"] = 16400.0
location_df.at["Godrej Nature Plus Serenity", "Indira Gandhi International Airport"] = 22500.0
location_df.at["M3M Merlin", "Indira Gandhi International Airport"] = 19300.0
location_df.at["Emaar MGF The Palm Drive", "Indira Gandhi International Airport"] = 16500.0
location_df.at["Ashiana Amarah", "Indira Gandhi International Airport"] = 21300.0
location_df.at["Vatika Independent Floors", "Indira Gandhi International Airport"] = 31400.0
location_df.at["Emaar The Palm Springs", "Indira Gandhi International Airport"] = 31000.0
location_df.at["BPTP Park Serene", "Indira Gandhi International Airport"] = 27900.0
location_df.at["Orchid IVY Floors", "Indira Gandhi International Airport"] = 22500.0
location_df.at["Paras Ekam Homes", "Indira Gandhi International Airport"] = 19400.0
location_df.at["Landmark The Homes 81", "Indira Gandhi International Airport"] = 17200.0
location_df.at["ROF Normanton Park", "Indira Gandhi International Airport"] = 35300.0
location_df.at["Anant Raj Ashok Estate", "Indira Gandhi International Airport"] = 37100.0
location_df.at["Yashika 104", "Indira Gandhi International Airport"] = 5000.0

In [609]:
location_df[location_df["InfinityS Badminton Academy"] +location_df["Infinitys Badminton Academy"] < 108000][["InfinityS Badminton Academy","Infinitys Badminton Academy"]]

                     InfinityS Badminton Academy  Infinitys Badminton Academy
PropertyName
Saan Verdante                             1100.0                      54000.0
Smart World Orchard                       5500.0                       5500.0
DLF The Aralias                           3100.0                      54000.0

In [608]:
location_df.at["Smart World Orchard", "InfinityS Badminton Academy"] = 5500.0

In [614]:
location_df[location_df["International Tech Park Gurgaon"] +location_df["International Tech Park Gurgaon,"] < 108000][["International Tech Park Gurgaon","International Tech Park Gurgaon,"]]

,International Tech Park Gurgaon,"International Tech Park Gurgaon,"
PropertyName,,
International City by Sobha Phase 1,1500.0,54000.0
Orchid IVY Floors,3000.0,3000.0

In [613]:
location_df.at["Orchid IVY Floors", "International Tech Park Gurgaon"] = 3000.0

In [615]:
location_df[location_df["JMS Marine Square"] +location_df["JMS Marine Square Mall"] < 108000][["JMS Marine Square","JMS Marine Square Mall"]]

                     JMS Marine Square  JMS Marine Square Mall
PropertyName
Ireo The Grand Arch            54000.0                  1500.0
Ambience Creacions             54000.0                  4300.0

In [617]:
location_df[location_df["Jinaglala Theme Park"] +location_df["Jinga Lala Theme Park Gurgaon Delhi"] < 108000][["Jinaglala Theme Park","Jinga Lala Theme Park Gurgaon Delhi"]]

,Jinaglala Theme Park,Jinga Lala Theme Park Gurgaon Delhi
PropertyName,,
International City by Sobha Phase 1,54000.0,2700.0

In [618]:
location_df["Jinaglala Theme Park"].min()

54000.0

In [620]:
location_df.drop(columns=["AIPL Business Co Working Space","AIPL Business Tower","AIPL Business Centre","Aman Hospital","Aman Hospital & Surgical Centre","ICICI Bank", "ICICI Bank ATM","ICICI ATM","IG International Airport","IGIA Airport","IMT Sohna","ISKCON Temple","ISKCON","IFFCO Chowk","IFFCO Chowk Metro Station","Imt Manesar","Imt Manesar, Gurugram","Indira Gandhi Airport","Indira Gandhi Int. Airport","IGI Airport","Indira Gandhi Intl Airport","Infinitys Badminton Academy","International Airport","International Tech Park Gurgaon,","JMS Marine Square","Jinaglala Theme Park"],inplace=True)

In [621]:
location_df.shape

(246, 897)

In [622]:
sorted(location_df.columns.to_list())

['AIPL Business Club',
 'AIPL Joy Street Mall',
 'APJ Abdul Kalam Park',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Ajit Stadium Dhanwapur',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Alpine Hospital',
 'Altrade Business Centre',
 'Ambience Mall',
 'Ambience Public School',
 'American Express',
 'Amity',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Ap Sports cricket ground',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Approved Sector 37 Mero Station',
 'Appu Ghar Water Park',
 'Aradhya Cricket Club Gurgaon',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Athena',
 'Au Grand Air',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BOB ATM',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Bamroli Cricket Ground',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Best IVF Centre',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharat Singh fuel company',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'BigBazaar',
 'Bijwasan Railway Station',
 'Biryani Shah',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CBR Cricket Ground',
 'CD International School',
 'CK Birla Hospital',
 'CNG Petrol Pump',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 "Cherub's Cradle",
 'Children Park',
 'Chirag Hospital',
 'Choice pharmacy',
 'Citibank ATM',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 'CoNexus.Life B35',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLC Cricket Ground',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPS Manesar',
 'DPS Sector 103',
 'DPSG Palam Vihar',
 'DSD College',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'Daultabad Village Park',
 'De Adventure Park',
 'Deerika HyperMart',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Delhi-Mumbai Expressway',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'Dishoom Cinemas',
 "Domino's Pizza",
 'Double Infinity market',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dreamz Cafe',
 'Drona Sports Village',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Early Basket Grocery shop',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Enkays Hospital',
 'Entertainland Mall',
 'Ernst & Young',
 'Eros City Square',
 'Eros Corporate Park',
 'Esplanade Mall',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'EuroKids Preschool Suncity',
 'Excellere World School',
 'Eye Doctors at Krishna Netralaya',
 'F9 Go Karting Gurgaon',
 'FUEL NATION',
 'Faridabad',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fortis hospital',
 'Fresco Market',
 'Frescos',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Garima Public School',
 'Gaytri Public School',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. Model Sanskriti Primary School',
 'Govt. PG College',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Green garden narsari',
 'Greenway Hospital',
 "Guls' Kitchen",
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon Dreamz Mall',
 'Gurgaon Gramin Bank',
 'Gurgaon Old Railway Station',
 'Gurgaon Railway Station',
 'Gurgaon Toll',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram City Bus Depot',
 'Gurugram Global Heights School',
 'Gurugram Hospital',
 'Gurugram Public School',
 'Gurugram Road',
 'Gurugram University',
 'Gurukul Preschool',
 'Gyaananda School',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HP Petrol Pump',
 'HSBC',
 'HUB 66',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Hanuman & Shani Mandir',
 'Harsaru Village Bus Stop',
 'Haryana City Gas',
 'Hasanpur',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Hero Honda Chowk',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Horizon 1 Mall',
 'Hotel Golf View Suites',
 'Huda Metro Station',
 'Huda Park',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency Gurgaon',
 'ICFAI University',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank ATM, Sector 86',
 'IDFC FIRST Bank',
 'IILM School of Management',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'INOX Cinema',
 'INXT High Street',
 'IRIS Broadway Mall',
 'ISBM College',
 'Ibis Hotel',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperfecto Patio',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi International Airport',
 'Indus World School',
 'Indus valley Public School',
 'IndusInd Bank',
 'IndusInd Bank ATM',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Info Technology Park Phase 2',
 'Insfire Sports',
 'International Tech Park Gurgaon',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jagdish Super Market',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Jungle Safari & Trails',
 'K. R. Mangalam University',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'K.R.Mangalam World School',
 'KDM Public School, Sohna',
 'KFG Sports Club',
 'KFG sports club Parking',
 'KIIT College',
 'KIIT College of Engineering',
 'KIIT College of Engineering Sohna Road',
 'KLAY Play School',
 'KMP Corridor',
 'KMP Expressway',
 'KMP corridor',
 'KR Mangalam',
 'KR Mangalam University',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Kangaroo Kids Preschool',
 'Karma Lakelands',
 'Keshav Pharmacy',
 'Khatu Shyam Mandir',
 'Kheri Railway station',
 'Kidzee',
 'Kidzee Sec-93',
 'Kinder Care Playschool',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kundli Manesar Palwal Expressway',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Learning Stars School',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel,',
 'Lemon Tree Hotel, Sohna Road',
 'Leopard hills',
 "Lingaya's Lalita Devi Institute",
 'Lions Public School',
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lotus Valley School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MCC Cricket Ground Dhankot',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Megacity Mall',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Mamta Hospital',
 'Manav Rachna School',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Marigold Secondary School',
 'Marriott Courtyard',
 'MatriKiran High School',
 'Matrikiran High School',
 'Matrikiran School',
 'Mavens Inn',
 'Mavens Orange - Hotel',
 'Max, Fortis',
 "McDonald's India",
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta Dialysis Center',
 'Medanta Hospital',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Medhaam Pre School & Daycare',
 'Medicity',
 'Meditree Market',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle / Spectra',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'Moksh Wellness Pvt Ltd.',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'N.H-8',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248',
 'NH 248 A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Neemrana Palace',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'New Water Pond',
 'Newtown Square Mall',
 'Ninex Mall',
 'Nirvana Rd',
 'Nischay Cricket Academy',
 'Nora Solomon Medicenter',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'OMAXE Gurgaon Mall',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Bengali Market',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Omex City Centre Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open Tap',
 'Open gym garden',
 'Orchid Business Park',
 'Oriental Bank of Commerce',
 "Oyster's Water Park",
 'PHC Garhi Harsaru',
 'PNB ATM',
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Park inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pataudi road',
 'Pathfinder Global School, Pataudi',
 'Pathways',
 'Pathways School Gurgaon',
 'Patil Station',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Peer Baba Ki Mazar',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Prakash Hospital',
 'Pranavananda Int. School',
 'Pranavananda International School',
 'Presidium School Gurgoan',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Propose Metro Station',
 'Proposed Metro Station',
 'Proposed Metro corridor',
 'Public Bazar',
 'Punjab National Bank',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Raheja Market',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Rajiv Chowk - Sohna Highway',
 'Ram Krishna Public School',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 55-56',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 55 56',
 'Rapid Metro Station Sector 56',
 'Rathore IMT Hospital',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCJ Academy',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UHTC Basai',
 'SGT UNIVERSITY',
 'SGT University',
 'SPM Hospital',
 'SRS Cinemas',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sanskar Jyoti School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Scottish International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 102 Dhankot',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43',
 'Sector 42-43 Metro Station',
 'Sector 42-43 Metro station',
 'Sector 42-43 Rapid Metro',
 'Sector 42-43 Rapid Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 45 SO Post Office',
 'Sector 53 Metro Station',
 'Sector 53-54',
 'Sector 53-54 Metro Station',
 'Sector 53-54 Rapid Metro',
 'Sector 53/54 Metro Station',
 'Sector 54 Chowk',
 'Sector 54 Chowk Metro Station',
 'Sector 55 Metro Station',
 'Sector 55-56 Metro',
 'Sector 55-56 Metro Station',
 'Sector 55-56 Metro station',
 'Sector 55-56 Rapid Metro',
 'Sector 55-56 Rapid Metro Station',
 'Sector 55-56 metro',
 'Sector 55-56 metro station',
 'Sector 55-56 rapid metro station',
 'Sector 55/56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shaheed Bhagat Singh Chowk',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shikshantar - Primary School',
 'Shishu Kalyan School',
 'Shiskshantar',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shiva Temple Tigra',
 'Shivai Hospital',
 'Shivani public school',
 'Shoppers Stop',
 'Shopping complex',
 'Shree Balaji College',
 'Shree Deep Petrol Pump',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Shri Hanuman Ji Mandir',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Hospital',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Hospital',
 'Silver Streak Multi Speciality',
 'Silver Streak Multi Speciality Hospital',
 'Singhania University, Manesar',
 'SkyJumper Trampoline Park',
 'SkyJumper Trampoline Park Gurgaon',
 'Skylark Cricket Academy',
 'Skyview Corporate Park',
 'Smart View Hotel and Resort',
 'Sneh Hospital',
 'Society Park',
 "Sodhi's Supermarket, Sector 82",
 'Sohna Bus Stand',
 'Sohna Gurgaon Road',
 'Sohna Hill Viewpoint',
 'Sohna Rd',
 'Sohna Road',
 'Sohna road dhunela',
 'Solitaire Banquet Hall',
 'South point Mall',
 'Southern Peripheral Rd',
 'Southern Peripheral Rd, Dhani',
 'Southern Peripheral Rd, Gurugram',
 'Southern Peripheral Road',
 'Southern Periphery Road',
 'Spaze Business Park',
 'Spaze Itech Park',
 'Spaze Palazo, Golf Course Ext Rd',
 'Spazedge IT Park',
 'Spectra Hospital',
 'Splendor Trade Tower',
 'SportsCube Center(Sports Complex)',
 'Sri Ma Montessori International',
 'St Pauls School',
 'St Xavier High School',
 "St. Angel's Global",
 "St. Xavier's High School",
 "St. Xavier's School",
 'Star Mall',
 'Star Nursery',
 'Starbucks',
 'State Bank of India',
 'Stymerra Chowk',
 'Subway',
 'Sultanpur National Park',
 'Summer Fields School',
 "Sun's Spa",
 'Suncity Market',
 'Suncity School',
 'Suncity School Gurgaon',
 'Suncity School, Sector 37D',
 'Suncity Shopping Complex',
 'Sunrise University',
 'Sunset point',
 'Suraj PG Degree College, Sec -75',
 'Surajgarh Gurgaon',
 'Surajgarh Gurgaon, Golf Course Ext Rd',
 'Sushant University',
 'Sushil Park',
 'Swastik Hospital',
 'Swastik Hospital Sec 66',
 'Swastik Multispeciality Hospital',
 'Syndicate Bank',

In [625]:
location_df[location_df["K. R. Mangalam University"] +location_df["K.R. Mangalam University"] < 108000][["K. R. Mangalam University","K.R. Mangalam University"]]

,K. R. Mangalam University,K.R. Mangalam University
PropertyName,,
Bestech Park View Spa Next,54000.0,4400.0
Anant Raj Ashok Estate,1900.0,1900.0
Paras Dews,1100.0,1100.0
Godrej Air,1100.0,1100.0
Unitech The Residences,54000.0,20800.0
MV Buildcon Precore City,1000.0,1000.0
Antriksh Heights,54000.0,2200.0
Pegasus Atulyam 83,54000.0,4700.0

In [624]:
location_df.at["Paras Dews", "K.R. Mangalam University"] = 1100.0
location_df.at["Anant Raj Ashok Estate", "K.R. Mangalam University"] = 1900.0
location_df.at["Godrej Air", "K.R. Mangalam University"] = 1100.0
location_df.at["MV Buildcon Precore City", "K.R. Mangalam University"] = 1000.0

In [632]:
location_df[location_df["KIIT College"] +location_df["KIIT College of Engineering"]+location_df["KIIT College of Engineering Sohna Road"] < (3*54000)][["KIIT College","KIIT College of Engineering","KIIT College of Engineering Sohna Road"]]

,KIIT College,KIIT College of Engineering,KIIT College of Engineering Sohna Road
PropertyName,,,
Elan The Presidential,54000.0,9000.0,54000.0
ROF Insignia Park,54000.0,8400.0,8400.0
Imperia The Esfera,54000.0,8000.0,54000.0
Ramprastha Primera,54000.0,6300.0,54000.0
Anand Niketan,54000.0,6100.0,54000.0
Ireo City Plots,54000.0,4000.0,54000.0
ROF Insignia Park 2,54000.0,4100.0,54000.0
Vatika Sovereign Next,54000.0,9700.0,54000.0

In [631]:
location_df.at["ROF Insignia Park", "KIIT College of Engineering"] = 8400.0

In [636]:
location_df[location_df["KR Mangalam University"] +location_df["KR Mangalam University Sohna"]+location_df["KR Mangalam"] < (3*54000)][["KR Mangalam University","KR Mangalam University Sohna","KR Mangalam"]]

,KR Mangalam University,KR Mangalam University Sohna,KR Mangalam
PropertyName,,,
DLF The Camellias,54000.0,1700.0,54000.0
Vatika The Seven Lamps,3700.0,3700.0,54000.0

In [635]:
location_df.at["Vatika The Seven Lamps", "KR Mangalam University Sohna"] = 3700.0

In [643]:
location_df["KR Mangalam"].min()

54000.0

In [648]:
location_df.drop(columns=["K. R. Mangalam University","KFG sports club Parking","KFG Sports Club","KIIT College","KIIT College of Engineering Sohna Road","KR Mangalam","KR Mangalam University"],inplace=True)

In [649]:
columns_to_drop = []
for i in location_df.columns:
    if location_df[i].min() == 54000:
        columns_to_drop.append(i)

In [650]:
len(columns_to_drop)

204

In [651]:
location_df.drop(columns=columns_to_drop,inplace=True)

In [652]:
location_df.shape

(246, 686)

In [653]:
sorted(location_df.columns.to_list())

['AIPL Business Club',
 'AIPL Joy Street Mall',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Altrade Business Centre',
 'Ambience Mall',
 'Ambience Public School',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Appu Ghar Water Park',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'Bijwasan Railway Station',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CD International School',
 'CK Birla Hospital',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 'Chirag Hospital',
 'Choice pharmacy',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPSG Palam Vihar',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'De Adventure Park',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Entertainland Mall',
 'Eros City Square',
 'Eros Corporate Park',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'Excellere World School',
 'F9 Go Karting Gurgaon',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. PG College',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Greenway Hospital',
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon Dreamz Mall',
 'Gurgaon Gramin Bank',
 'Gurgaon Railway Station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram Global Heights School',
 'Gurugram Road',
 'Gurugram University',
 'Gurukul Preschool',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HP Petrol Pump',
 'HUB 66',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Harsaru Village Bus Stop',
 'Hasanpur',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Hero Honda Chowk',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Hotel Golf View Suites',
 'Huda Metro Station',
 'Huda Park',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency Gurgaon',
 'ICFAI University',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank ATM, Sector 86',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'INOX Cinema',
 'IRIS Broadway Mall',
 'ISBM College',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi International Airport',
 'Indus World School',
 'Indus valley Public School',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Info Technology Park Phase 2',
 'International Tech Park Gurgaon',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'KDM Public School, Sohna',
 'KIIT College of Engineering',
 'KLAY Play School',
 'KMP Expressway',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Keshav Pharmacy',
 'Kidzee Sec-93',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel, Sohna Road',
 "Lingaya's Lalita Devi Institute",
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lotus Valley Intl School, Gurgaon',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan Mall',
 'M3M IFC',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Matrikiran High School',
 'Matrikiran School',
 "McDonald's India 24 Hours",
 'Medanta - The Medicity',
 'Medanta -The Medicity',
 'Medanta The Medicity',
 'Medanta-The Medicity',
 'Medeor Hospital, Manesar',
 'Mehrauli-Gurgaon Rd',
 'Mehrauli-Gurgaon Road',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Cradle Spectra Hospital',
 'Miracles Apollo Cradle/Spectra Hospital',
 'Miracles Apollo Hospital',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'NH -8',
 'NH 08',
 'NH 148A',
 'NH 248A',
 'NH 352W',
 'NH 352W, Pataudi',
 'NH 48',
 'NH 48 Gurugram',
 'NH 48, Sector 78',
 'NH 8',
 'NH 8, Sector 15 Part 2',
 'NH-48',
 'NH-8',
 'NH-8 Delhi Jaipur Highway',
 'NH-8 IMT Manesar',
 'NH-8, IMT Manesar',
 'NH-8, Imt Manesar',
 'NH248A',
 'NH48',
 'NH8',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Nakhrola Stadium Sector 81A',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway  48',
 'National Highway 48',
 'National Highway 8',
 'National Highway-48',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'Newtown Square Mall',
 'Nirvana Rd',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open gym garden',
 'Orchid Business Park',
 "Oyster's Water Park",
 'PVR Drive In Cinema',
 'PVR Drive In Theater',
 'PVR Drive In Theatre',
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospital',
 'Paras Hospitals',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity Mall',
 'Paras Trinity Mall Sector 63',
 'Paras Trinity Shopping Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Hospital, Palam Vihar',
 'Park Inn',
 'Park Inn, Gurgaon',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Rd',
 'Pataudi Rd, Sector 95B',
 'Pataudi Road',
 'Pathfinder Global School, Pataudi',
 'Pathways School Gurgaon',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Pranavananda International School',
 'Primamed Super Speciality Hospital',
 'Prime Scholars Int. School',
 'Prime Scholars International School',
 'Public Bazar',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 56',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UNIVERSITY',
 'SGT University',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43 Metro Station',
 'Sector 42-43 Rapid Metro',
 'Sector 42-43 Rapid Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 53 Metro Station',
 'Sector 53-54 Metro Station',
 'Sector 53-54 Rapid Metro',
 'Sector 53/54 Metro Station',
 'Sector 54 Chowk Metro Station',
 'Sector 55 Metro Station',
 'Sector 55-56 Metro',
 'Sector 55-56 Metro Station',
 'Sector 55-56 Metro station',
 'Sector 55-56 Rapid Metro',
 'Sector 55-56 Rapid Metro Station',
 'Sector 55-56 metro',
 'Sector 55/56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shivai Hospital',
 'Shivani public school',
 'Shree Balaji College',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Hospital',
 'Silver Streak Multi Speciality',
 'Silver Streak Multi Speciality Hospital',
 'Singhania University, Manesar',
 'SkyJumper Trampoline Park',
 'SkyJumper Trampoline Park Gurgaon',
 'Skylark Cricket Academy',
 'Skyview Corporate Park',
 'Sneh Hospital',
 "Sodhi's Supermarket, Sector 82",
 'Sohna Bus Stand',
 'Sohna Gurgaon Road',
 'Sohna Hill Viewpoint',
 'Sohna Road',
 'Sohna road dhunela',
 'Solitaire Banquet Hall',
 'South point Mall',
 'Southern Peripheral Rd',
 'Southern Peripheral Rd, Dhani',
 'Southern Peripheral Rd, Gurugram',
 'Southern Peripheral Road',
 'Southern Periphery Road',
 'Spaze Business Park',
 'Spaze Itech Park',
 'Spaze Palazo, Golf Course Ext Rd',
 'Spazedge IT Park',
 'Spectra Hospital',
 'Splendor Trade Tower',
 'SportsCube Center(Sports Complex)',
 'Sri Ma Montessori International',
 'St Xavier High School',
 "St. Xavier's High School",
 "St. Xavier's School",
 'Star Mall',
 'Starbucks',
 'State Bank of India',
 'Sultanpur National Park',
 'Summer Fields School',
 'Suncity School',
 'Suncity School, Sector 37D',
 'Sunrise University',
 'Sunset point',
 'Suraj PG Degree College, Sec -75',
 'Surajgarh Gurgaon',
 'Surajgarh Gurgaon, Golf Course Ext Rd',
 'Sushant University',
 'Swastik Hospital',
 'Swastik Hospital Sec 66',
 'Swastik Multispeciality Hospital',
 'TERI Golf Course',
 'Taj City Centre Gurugram',
 'Taj City Centre Hotel',
 'Taj Hotel & Family Restaurant',
 'Tau DeviLal Sports Complex',
 'Tennis Vidyalaya (Tennis Academy)',
 'Teri Golf Course',
 'The Banyan Tree Hiking Area',
 'The Banyan Tree World School',
 'The Big Tree Cafe',
 'The Club, International City',
 'The Esplanade Mall',
 'The Executive Centre',
 'The Hive Shopping Mall',
 'The Holy Kingdom Public School',
 'The Medicity, Spaze iTech Park',
 'The NorthCap University',
 'The Oberoi',
 'The Oberoi Gurgaon',
 'The Oberoi, Gurgaon',
 'The Paras World School',
 'The Phoenix Project, Sohna - Gurgaon Rd',
 'The Shikshiyan School',
 'The Shri Ram School Aravali',
 'The Shriram Millennium School',
 'The Signature Advanced Super Speciality',
 'The Signature Super Speciality Hospital',
 'The Sylvan Trails School',
 'The Vivekananda School',
 'The Westin Gurgaon',
 'The Westin Hotel',
 'Tomar Hospital',
 'Trident Hotel Gurgaon',
 'Tulip Violet Society, Sector 69',
 'Uma Sanjeevani Health Centre',
 'Umang Bhawaj Chawk',
 'Umkal Hospital',
 'Unicosmos School',
 'Unitech Business Zone',
 'V Club',
 "V'Lante Mall",
 'V-Square Sohna New Residential',
 'VATIKA BUSINESS PARK Sohna Rd',
 'VIBGYOR High School',
 'Vallores Pre School',
 'Vardaan Hospital',
 'Vardaan Hospital & Trauma Centre',
 'Vardaan Hospital and Trauma Centre',
 'Vardaan hospital and trauma centre',
 'Vasant Kunj',
 'Vatika Business Centre',
 'Vatika Business Park Sector 49',
 'Vatika City Centre',
 'Vatika City Centre Mall',
 'Vatika Sector Road',
 'Vatika Town Square',
 'Vatika Town Square-INXT',
 'Vatika Town Square-INXT Mall',
 'Vedic Hospital',
 'Vega Schools NH-8',
 'Vega Schools Sector 48',
 'Vibrant Hospital',
 'Vidya Niketan Sr Sec School',
 'Vipul Trade Business Centre',
 'Vipul Trade Centre',
 'Vishwas Hospital',
 'Vistar Complex',
 'Vivanta Dwarka New Delhi',
 'Vivanta New Delhi, Dwarka',
 'Vivek Model School',
 'W Pratiksha Hospital',
 'WTC Plaza',
 'Western Peripheral Expressway',
 'Western Peripheral Expy, Gurugram',
 'WorldMark Gurgaon',
 'WorldMark Gurgaon, Maidawas Rd',
 'YES Bank',
 'YES Bank ATM',
 'Yaduvanshi Shiksha Niketan',
 'Yashlok Medical Centre',
 'Yashroop Hospital',
 'ZEN Golf Range & Academy',
 'Zooper India Trampoline Park',
 'iGrow Montessori Play School',
 'iON Digital Zone (Gurugram)',
 'iON Digital Zone, Gurgaon',
 'infinity Business Park',
 'nfinitys Badminton Academy']

In [656]:
location_df[location_df["Lotus Valley International School"] +location_df["Lotus Valley Intl School, Gurgaon"] < 108000][["Lotus Valley International School","Lotus Valley Intl School, Gurgaon"]]

,Lotus Valley International School,"Lotus Valley Intl School, Gurgaon"
PropertyName,,
Signature Global City 93,2600.0,2600.0
Birla Navya,700.0,54000.0

In [655]:
location_df.at["Signature Global City 93", "Lotus Valley International School"] = 2600.0

In [659]:
location_df[location_df["M3M IFC"] +location_df["M3M International Financial Center (IFC)"] < 108000][["M3M IFC","M3M International Financial Center (IFC)"]]

,M3M IFC,M3M International Financial Center (IFC)
PropertyName,,
Godrej Nature Plus Serenity,1400.0,1400.0
Optimal ultra luxury builder floors,54000.0,1100.0

In [658]:
location_df.at["Godrej Nature Plus Serenity", "M3M International Financial Center (IFC)"] = 1400.0

In [663]:
location_df[location_df["Medanta - The Medicity"]+location_df["Medanta -The Medicity"]+location_df["Medanta The Medicity"] +location_df["Medanta-The Medicity"]  < (4*54000)][["Medanta - The Medicity","Medanta -The Medicity","Medanta The Medicity","Medanta-The Medicity"]]

,Medanta - The Medicity,Medanta -The Medicity,Medanta The Medicity,Medanta-The Medicity
PropertyName,,,,
Emaar Digihomes,54000.0,9000.0,54000.0,9000.0
Yash Vihar,54000.0,8900.0,8900.0,54000.0
Central Park Flower Valley Mikasa Plots,54000.0,10000.0,54000.0,54000.0
Ambience Creacions,54000.0,10200.0,10200.0,54000.0
Eldeco Accolade,4500.0,4500.0,54000.0,54000.0
Mapsko The Icon 79,54000.0,3400.0,3400.0,54000.0
Signature The Roselia,54000.0,5100.0,54000.0,54000.0
Optimal ultra luxury builder floors,54000.0,6000.0,54000.0,54000.0

In [662]:
location_df.at["Emaar Digihomes", "Medanta -The Medicity"] = 9000.0
location_df.at["Yash Vihar", "Medanta -The Medicity"] = 8900.0
location_df.at["Ambience Creacions", "Medanta -The Medicity"] = 10200.0
location_df.at["Eldeco Accolade", "Medanta -The Medicity"] = 4500.0
location_df.at["Mapsko The Icon 79", "Medanta -The Medicity"] = 3400.0

In [666]:
location_df[location_df["Mehrauli-Gurgaon Rd"] +location_df["Mehrauli-Gurgaon Road"] < 108000][["Mehrauli-Gurgaon Rd","Mehrauli-Gurgaon Road"]]

                         Mehrauli-Gurgaon Rd  Mehrauli-Gurgaon Road
PropertyName
ROF Insignia Park                    11800.0                11800.0
Ansals Shiva Som Valley               6600.0                54000.0
DLF The Grove                         4400.0                54000.0

In [665]:
location_df.at["ROF Insignia Park", "Mehrauli-Gurgaon Rd"] = 11800.0

In [669]:
location_df[location_df["Miracles Apollo Cradle /Spectra Hospital"] +location_df["Miracles Apollo Cradle Spectra Hospital"]+location_df["Miracles Apollo Cradle/Spectra Hospital"] < (3*54000)][["Miracles Apollo Cradle /Spectra Hospital","Miracles Apollo Cradle Spectra Hospital","Miracles Apollo Cradle/Spectra Hospital"]]

,Miracles Apollo Cradle /Spectra Hospital,Miracles Apollo Cradle Spectra Hospital,Miracles Apollo Cradle/Spectra Hospital
PropertyName,,,
Oxirich Chintamanis,2900.0,2900.0,54000.0
DLF The Pinnacle,800.0,54000.0,54000.0
Puri Diplomatic Greens,1500.0,54000.0,1500.0

In [668]:
location_df.at["Oxirich Chintamanis", "Miracles Apollo Cradle /Spectra Hospital"] = 2900.0
location_df.at["Puri Diplomatic Greens", "Miracles Apollo Cradle /Spectra Hospital"] = 1500.0

In [672]:
location_df[location_df["NH -8"] +location_df["NH 08"]+location_df["NH 8"]+location_df["NH 8, Sector 15 Part 2"]+location_df["NH-8"]+location_df["NH8"]+location_df["NH-8 Delhi Jaipur Highway"] < (7*54000)][["NH -8","NH 08","NH 8","NH 8, Sector 15 Part 2","NH-8","NH8","NH-8 Delhi Jaipur Highway"]]

,NH -8,NH 08,NH 8,"NH 8, Sector 15 Part 2",NH-8,NH8,NH-8 Delhi Jaipur Highway
PropertyName,,,,,,,
Signature Global City,54000.0,54000.0,54000.0,5100.0,5100.0,54000.0,54000.0
Signature Global City 37D Ph 2,54000.0,54000.0,54000.0,54000.0,9500.0,54000.0,54000.0
DLF The Crest,54000.0,54000.0,5000.0,54000.0,5000.0,54000.0,54000.0
Indiabulls Enigma,6500.0,54000.0,54000.0,54000.0,6500.0,54000.0,54000.0
Hero Homes,54000.0,54000.0,54000.0,54000.0,14900.0,54000.0,14900.0
M3M Skywalk,54000.0,8100.0,54000.0,54000.0,8100.0,54000.0,54000.0
JMS The Nation,54000.0,54000.0,54000.0,54000.0,7700.0,54000.0,54000.0
Ireo Savannah,54000.0,54000.0,54000.0,54000.0,4500.0,4500.0,54000.0

In [671]:
location_df.at["Signature Global City", "NH-8"] = 5100.0
location_df.at["DLF The Crest", "NH-8"] = 5000.0
location_df.at["Indiabulls Enigma", "NH-8"] = 6500.0
location_df.at["Hero Homes", "NH-8"] = 14900.0
location_df.at["M3M Skywalk", "NH-8"] = 8100.0
location_df.at["Ireo Savannah", "NH-8"] = 4500.0

In [675]:
location_df[location_df["NH 352W"] +location_df["NH 352W, Pataudi"] < 108000][["NH 352W","NH 352W, Pataudi"]]

                         NH 352W  NH 352W, Pataudi
PropertyName
Ireo Victory Valley       1500.0           54000.0
Pyramid Spring Valley     2400.0            2400.0
Lion Infra Green Valley   4900.0           54000.0

In [674]:
location_df.at["Pyramid Spring Valley", "NH 352W"] = 2400.0

In [678]:
location_df[location_df["NH 248A"] +location_df["NH248A"] < 108000][["NH 248A","NH248A"]]

                          NH 248A   NH248A
PropertyName
Bestech Altura             6300.0  54000.0
Signature Global City 92   5200.0  54000.0
SS Linden Floors           3800.0  54000.0
M3M Soulitude              6900.0   6900.0
Vatika City               11400.0  54000.0
Anant Raj Ashok Estate     1000.0  54000.0
Godrej Air                 8700.0  54000.0
Vipul Belmonte             8100.0  54000.0

In [677]:
location_df.at["M3M Soulitude", "NH 248A"] = 6900.0

In [681]:
location_df[location_df["NH 48"] +location_df["NH 48 Gurugram"]+location_df["NH 48, Sector 78"] < (3*54000)][["NH 48","NH 48 Gurugram","NH 48, Sector 78"]]

                                       NH 48  NH 48 Gurugram  NH 48, Sector 78
PropertyName
Signature Global City 81              2300.0         54000.0           54000.0
Emaar Palm Heights                    3800.0         54000.0           54000.0
International City by SOBHA Phase 2   3100.0         54000.0           54000.0
DLF The Ultima                        3300.0         54000.0           54000.0
Pioneer Urban Presidia                3000.0         54000.0           54000.0
Vatika Seven Elements                 6800.0          6800.0           54000.0
Emaar Palm Gardens                    4600.0         54000.0           54000.0
BPTP Park Serene                      1900.0         54000.0           54000.0
Pioneer Park                          2800.0         54000.0           54000.0
Bestech Park View Sanskruti           3100.0         54000.0           54000.0
Optimal ultra luxury builder floors  12600.0         54000.0           12600.0

In [680]:
location_df.at["Vatika Seven Elements", "NH 48"] = 6800.0
location_df.at["Optimal ultra luxury builder floors", "NH 48"] = 12600.0

In [684]:
location_df[location_df["NH 48"] +location_df["NH-48"]+location_df["NH48"] < (3*54000)][["NH 48","NH-48","NH48"]]

                                       NH 48    NH-48     NH48
PropertyName
Signature Global City 81              2300.0  54000.0  54000.0
Emaar Palm Heights                    3800.0  54000.0  54000.0
International City by SOBHA Phase 2   3100.0  54000.0  54000.0
DLF The Ultima                        3300.0  54000.0  54000.0
Pioneer Urban Presidia                3000.0  54000.0  54000.0
Shree Vardhman Flora                  9400.0   9400.0  54000.0
Vatika Seven Elements                 6800.0  54000.0  54000.0
Emaar Palm Gardens                    4600.0  54000.0  54000.0
Emaar The Palm Springs                6900.0  54000.0   6900.0
BPTP Park Serene                      1900.0  54000.0  54000.0
Pioneer Park                          2800.0  54000.0  54000.0
Bestech Park View Sanskruti           3100.0  54000.0  54000.0
Optimal ultra luxury builder floors  12600.0  54000.0  54000.0

In [683]:
location_df.at["Shree Vardhman Flora", "NH 48"] = 9400.0
location_df.at["Emaar The Palm Springs", "NH 48"] = 6900.0

In [687]:
location_df[location_df["NH-8 IMT Manesar"] +location_df["NH-8, IMT Manesar"]+location_df["NH-8, Imt Manesar"] < (3*54000)][["NH-8 IMT Manesar","NH-8, IMT Manesar","NH-8, Imt Manesar"]]

,NH-8 IMT Manesar,"NH-8, IMT Manesar","NH-8, Imt Manesar"
PropertyName,,,
Suncity Avenue 76,54000.0,15400.0,54000.0
M3M Sierra 68,54000.0,8700.0,8700.0
Central Park Flower Valley Aqua Front Towers,54000.0,5400.0,54000.0
BPTP Fortuna,54000.0,6400.0,6400.0
Satya The Hermitage,7600.0,7600.0,54000.0

In [686]:
location_df.at["M3M Sierra 68", "NH-8, IMT Manesar"] = 8700.0
location_df.at["BPTP Fortuna", "NH-8, IMT Manesar"] = 6400.0
location_df.at["Satya The Hermitage", "NH-8, IMT Manesar"] = 7600.0

In [690]:
location_df[location_df["Nakhrola Stadium"] +location_df["Nakhrola Stadium Sector 81A"] < 108000][["Nakhrola Stadium","Nakhrola Stadium Sector 81A"]]

,Nakhrola Stadium,Nakhrola Stadium Sector 81A
PropertyName,,
Ireo Victory Valley,6000.0,54000.0
Emaar MGF Emerald Floors Premier,5200.0,54000.0
M3M Skywalk,5300.0,5300.0
DLF The Belaire,5700.0,54000.0
Vatika Seven Elements,4600.0,54000.0
Central Park Flower Valley The Room,3400.0,54000.0
Ireo Savannah,2300.0,54000.0
Vatika Independent Floors,6000.0,54000.0
Emaar Palm Gardens,5800.0,54000.0
Silverglades Hightown Residences,3800.0,54000.0
Bestech Park View Sanskruti,4600.0,54000.0

In [689]:
location_df.at["M3M Skywalk", "Nakhrola Stadium"] = 5300.0

In [696]:
location_df[location_df["NH 48"] +location_df["National Highway  48"]+location_df["National Highway 48"]+location_df["National Highway-48"] < (4*54000)][["NH 48","National Highway  48","National Highway 48","National Highway-48"]]

,NH 48,National Highway 48,National Highway 48,National Highway-48
PropertyName,,,,
Signature Global City 81,2300.0,54000.0,54000.0,54000.0
Emaar Palm Heights,3800.0,54000.0,54000.0,54000.0
International City by SOBHA Phase 2,3100.0,54000.0,54000.0,54000.0
DLF The Ultima,3300.0,54000.0,54000.0,54000.0
Central Park Resorts,9600.0,54000.0,54000.0,9600.0
Pioneer Urban Presidia,3000.0,54000.0,54000.0,54000.0
Shree Vardhman Flora,9400.0,54000.0,54000.0,54000.0
Vatika Seven Elements,6800.0,54000.0,54000.0,54000.0
Emaar Palm Gardens,4600.0,54000.0,54000.0,54000.0
Emaar The Palm Springs,6900.0,54000.0,54000.0,54000.0
BPTP Park Serene,1900.0,54000.0,54000.0,54000.0
Pioneer Park,2800.0,54000.0,54000.0,54000.0
Bestech Park View Sanskruti,3100.0,54000.0,54000.0,54000.0
Orchid Island,5700.0,5700.0,54000.0,54000.0
Mapsko Casa Bella,5700.0,54000.0,5700.0,54000.0
Optimal ultra luxury builder floors,12600.0,54000.0,54000.0,54000.0

In [695]:
location_df.at["Central Park Resorts", "NH 48"] = 9600.0
location_df.at["Orchid Island", "NH 48"] = 5700.0
location_df.at["Mapsko Casa Bella", "NH 48"] = 5700.0

In [699]:
location_df[location_df["PVR Drive In Cinema"]+location_df["PVR Drive In Theater"]+location_df["PVR Drive In Theatre"] +location_df["PVR Drive in Theatre"]  < (4*54000)][["PVR Drive In Cinema","PVR Drive In Theater","PVR Drive In Theatre","PVR Drive in Theatre"]]

,PVR Drive In Cinema,PVR Drive In Theater,PVR Drive In Theatre,PVR Drive in Theatre
PropertyName,,,,
Tulip Monsella,54000.0,54000.0,54000.0,5700.0
Vatika Aspiration,54000.0,54000.0,9900.0,9900.0
Experion The Westerlies,2200.0,54000.0,54000.0,2200.0
Ramprastha Primera,54000.0,54000.0,8100.0,8100.0
DLF New Town Heights 2,54000.0,54000.0,54000.0,5400.0
DLF The Skycourt,54000.0,54000.0,54000.0,4800.0
Ansals Shiva Som Valley,54000.0,54000.0,54000.0,7700.0
Vipul World,54000.0,54000.0,54000.0,3300.0
Emaar Imperial Gardens,54000.0,54000.0,54000.0,1500.0
Ireo City Plots,54000.0,6500.0,54000.0,6500.0
DLF The Grove,54000.0,54000.0,54000.0,10600.0
Corona Optus,54000.0,54000.0,3400.0,3400.0
ROF Insignia Park 2,54000.0,54000.0,54000.0,5600.0
M3M Sky Lofts,54000.0,54000.0,54000.0,7400.0

In [698]:
location_df.at["Vatika Aspiration", "PVR Drive in Theatre"] = 9900.0
location_df.at["Experion The Westerlies", "PVR Drive in Theatre"] = 2200.0
location_df.at["Ramprastha Primera", "PVR Drive in Theatre"] = 8100.0
location_df.at["Ireo City Plots", "PVR Drive in Theatre"] = 6500.0
location_df.at["Corona Optus", "PVR Drive in Theatre"] = 3400.0

In [702]:
location_df[location_df["Paras Hospital"] +location_df["Paras Hospitals"]+location_df["Paras Hospitals, Gurgaon"] < (3*54000)][["Paras Hospital","Paras Hospitals","Paras Hospitals, Gurgaon"]]

,Paras Hospital,Paras Hospitals,"Paras Hospitals, Gurgaon"
PropertyName,,,
DLF Garden City Floors,54000.0,54000.0,8900.0
ATS Marigold,54000.0,54000.0,4800.0
Emaar Palm Heights,54000.0,54000.0,4500.0
Godrej Nature Plus,54000.0,54000.0,7400.0
M3M Sky Lofts,2000.0,54000.0,2000.0
Landmark The Homes 81,4500.0,54000.0,4500.0
Conscient Habitat,54000.0,4200.0,4200.0
Vipul Belmonte,54000.0,54000.0,1600.0
Signature Global Solera 2,54000.0,54000.0,1800.0

In [701]:
location_df.at["M3M Sky Lofts", "Paras Hospitals, Gurgaon"] = 2000.0
location_df.at["Landmark The Homes 81", "Paras Hospitals, Gurgaon"] = 4500.0
location_df.at["Conscient Habitat", "Paras Hospitals, Gurgaon"] = 4200.0

In [705]:
location_df[location_df["Paras Trinity Mall"] +location_df["Paras Trinity Mall Sector 63"]+location_df["Paras Trinity Shopping Mall"] < (3*54000)][["Paras Trinity Mall","Paras Trinity Mall Sector 63","Paras Trinity Shopping Mall"]]

,Paras Trinity Mall,Paras Trinity Mall Sector 63,Paras Trinity Shopping Mall
PropertyName,,,
Elan The Presidential,2200.0,54000.0,54000.0
ATS Triumph,280.0,54000.0,54000.0
ROF Insignia Park,3500.0,3500.0,54000.0
Experion The Heartsong,1800.0,54000.0,1800.0
International City by Sobha Phase 1,3500.0,54000.0,54000.0
Emaar Imperial Gardens,1000.0,54000.0,54000.0
ROF Insignia Park 2,3700.0,54000.0,54000.0
Vatika Sovereign Next,1700.0,54000.0,54000.0
Vatika City,2300.0,54000.0,54000.0

In [704]:
location_df.at["ROF Insignia Park", "Paras Trinity Mall"] = 3500.0
location_df.at["Experion The Heartsong", "Paras Trinity Mall"] = 1800.0

In [708]:
location_df[location_df["Park Hospital"] +location_df["Park Hospital, Palam Vihar"] < 108000][["Park Hospital","Park Hospital, Palam Vihar"]]

                              Park Hospital  Park Hospital, Palam Vihar
PropertyName
Smartworld One DXP                   3100.0                     54000.0
Signature Global City 93             5500.0                     54000.0
Whiteland The Aspen                  5800.0                     54000.0
Bestech Altura                       4400.0                     54000.0
Elan The Presidential                8500.0                     54000.0
Signature Global City 92             2900.0                     54000.0
Signature Global City 79B            5200.0                     54000.0
Signature Global City 81             3300.0                     54000.0
SS Linden Floors                     2800.0                     54000.0
Mahindra Luminare                    7200.0                     54000.0
M3M Golf Hills                       9000.0                     54000.0
Whiteland Blissville                 7800.0                     54000.0
Tulip Monsella                       3500.0                     54000.0
Krisumi Waterfall Residences         7600.0                     54000.0
M3M Capital                          2700.0                     54000.0
Godrej Meridien                     12100.0                     54000.0
Birla Navya                          2800.0                     54000.0
Signature Global City                2100.0                     54000.0
Godrej 101                           1800.0                     54000.0
M3M Soulitude                        4800.0                     54000.0
M3M Skycity                          2800.0                     54000.0
Godrej Nature Plus Serenity          2300.0                     54000.0
SS The Leaf                          2000.0                     54000.0
Eldeco Acclaim                       4100.0                     54000.0
Pioneer Araya                        1400.0                      1400.0
Emaar MGF Marbella                   2200.0                      2200.0

In [707]:
location_df.at["Pioneer Araya", "Park Hospital"] = 1400.0
location_df.at["Emaar MGF Marbella", "Park Hospital"] = 2200.0

In [712]:
location_df[location_df["Park Inn"] +location_df["Park Inn, Gurgaon"] < 108000][["Park Inn","Park Inn, Gurgaon"]]

                     Park Inn  Park Inn, Gurgaon
PropertyName
Experion Windchants    7400.0            54000.0
Smart World Gems       6900.0            54000.0
The Close North       10300.0            10300.0

In [711]:
location_df.at["The Close North", "Park Inn"] = 10300.0

In [715]:
location_df[location_df["Pataudi Rd"] +location_df["Pataudi Rd, Sector 95B"]+location_df["Pataudi Road"] < (3*54000)][["Pataudi Rd","Pataudi Rd, Sector 95B","Pataudi Road"]]

,Pataudi Rd,"Pataudi Rd, Sector 95B",Pataudi Road
PropertyName,,,
Emaar Digihomes,54000.0,54000.0,1000.0
Signature Global City 37D Ph 2,54000.0,54000.0,8500.0
Tata Primanti,54000.0,54000.0,400.0
Hero Homes,54000.0,54000.0,6000.0
M3M Skywalk,54000.0,54000.0,9200.0
Eldeco Accolade,54000.0,54000.0,5000.0
Shree Vardhman Victoria,54000.0,54000.0,100.0
Shree Vardhman Flora,54000.0,54000.0,4800.0
Godrej Oasis,54000.0,54000.0,11000.0
Golden Park,54000.0,54000.0,3300.0
Mahindra Aura,54000.0,1100.0,1100.0
BPTP Mansions Park Prime,5700.0,54000.0,5700.0

In [714]:
location_df.at["Mahindra Aura", "Pataudi Road"] = 1100.0
location_df.at["BPTP Mansions Park Prime", "Pataudi Road"] = 5700.0

In [718]:
location_df[location_df["Prime Scholars Int. School"] +location_df["Prime Scholars International School"] < 108000][["Prime Scholars Int. School","Prime Scholars International School"]]

,Prime Scholars Int. School,Prime Scholars International School
PropertyName,,
AIPL The Peaceful Homes,54000.0,2900.0
Ireo The Grand Arch,2500.0,2500.0
The Close North,54000.0,800.0

In [717]:
location_df.at["Ireo The Grand Arch", "Prime Scholars International School"] = 2500.0

In [719]:
location_df.drop(columns=["Lotus Valley Intl School, Gurgaon","M3M IFC","Medanta - The Medicity","Medanta The Medicity","Medanta-The Medicity","Mehrauli-Gurgaon Road","Miracles Apollo Cradle Spectra Hospital","Miracles Apollo Cradle/Spectra Hospital","NH -8","NH 08","NH 8","NH 8, Sector 15 Part 2","NH8","NH-8 Delhi Jaipur Highway","NH 352W, Pataudi","NH248A","NH 48 Gurugram","NH 48, Sector 78","NH-48","NH48","NH-8 IMT Manesar","NH-8, Imt Manesar","Nakhrola Stadium Sector 81A","National Highway  48","National Highway 48","National Highway-48","PVR Drive In Cinema","PVR Drive In Theater","PVR Drive In Theatre","Paras Hospital","Paras Hospitals","Paras Trinity Mall Sector 63","Paras Trinity Shopping Mall","Park Hospital, Palam Vihar","Park Inn, Gurgaon","Pataudi Rd","Pataudi Rd, Sector 95B","Prime Scholars Int. School"],inplace=True)

In [720]:
location_df.shape

(246, 648)

In [721]:
sorted(location_df.columns.to_list())

['AIPL Business Club',
 'AIPL Joy Street Mall',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Altrade Business Centre',
 'Ambience Mall',
 'Ambience Public School',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Appu Ghar Water Park',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'Bijwasan Railway Station',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CD International School',
 'CK Birla Hospital',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 'Chirag Hospital',
 'Choice pharmacy',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPSG Palam Vihar',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'De Adventure Park',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Entertainland Mall',
 'Eros City Square',
 'Eros Corporate Park',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'Excellere World School',
 'F9 Go Karting Gurgaon',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. PG College',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Greenway Hospital',
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon Dreamz Mall',
 'Gurgaon Gramin Bank',
 'Gurgaon Railway Station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram Global Heights School',
 'Gurugram Road',
 'Gurugram University',
 'Gurukul Preschool',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HP Petrol Pump',
 'HUB 66',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Harsaru Village Bus Stop',
 'Hasanpur',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Hero Honda Chowk',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Hotel Golf View Suites',
 'Huda Metro Station',
 'Huda Park',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency Gurgaon',
 'ICFAI University',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank ATM, Sector 86',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'INOX Cinema',
 'IRIS Broadway Mall',
 'ISBM College',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi International Airport',
 'Indus World School',
 'Indus valley Public School',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Info Technology Park Phase 2',
 'International Tech Park Gurgaon',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'KDM Public School, Sohna',
 'KIIT College of Engineering',
 'KLAY Play School',
 'KMP Expressway',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Keshav Pharmacy',
 'Kidzee Sec-93',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel, Sohna Road',
 "Lingaya's Lalita Devi Institute",
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan Mall',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Matrikiran High School',
 'Matrikiran School',
 "McDonald's India 24 Hours",
 'Medanta -The Medicity',
 'Medeor Hospital, Manesar',
 'Mehrauli-Gurgaon Rd',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Hospital',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'NH 148A',
 'NH 248A',
 'NH 352W',
 'NH 48',
 'NH-8',
 'NH-8, IMT Manesar',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway 8',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'Newtown Square Mall',
 'Nirvana Rd',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open gym garden',
 'Orchid Business Park',
 "Oyster's Water Park",
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Road',
 'Pathfinder Global School, Pataudi',
 'Pathways School Gurgaon',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Pranavananda International School',
 'Primamed Super Speciality Hospital',
 'Prime Scholars International School',
 'Public Bazar',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'RPS International School Sector 89',
 'Radha Krishan Mandir',
 'Radisson Hotel',
 'Radisson Hotel Gurugram',
 'Radisson Hotel Gurugram Sohna Road',
 'Radisson Hotel Sohna Road',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Sector 56',
 'Rapid Metro Station Sector 56',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rions Hospital',
 'Rotary Public School',
 'Royal Institute Of Science',
 'Royal Institute Of Science & Management',
 'Royal Institute Of Science and Mgt',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT UNIVERSITY',
 'SGT University',
 'SS Omnia Mall',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanjeevani Hospital - Child Specialist',
 'Sanjivani Hospital',
 'Sanskar Bharti Public School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83 Mall',
 'Sapphire 83 Mall Sector 83',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43 Metro Station',
 'Sector 42-43 Rapid Metro',
 'Sector 42-43 Rapid Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 53 Metro Station',
 'Sector 53-54 Metro Station',
 'Sector 53-54 Rapid Metro',
 'Sector 53/54 Metro Station',
 'Sector 54 Chowk Metro Station',
 'Sector 55 Metro Station',
 'Sector 55-56 Metro',
 'Sector 55-56 Metro Station',
 'Sector 55-56 Metro station',
 'Sector 55-56 Rapid Metro',
 'Sector 55-56 Rapid Metro Station',
 'Sector 55-56 metro',
 'Sector 55/56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shivai Hospital',
 'Shivani public school',
 'Shree Balaji College',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Hospital',
 'Silver Streak Multi Speciality',
 'Silver Streak Multi Speciality Hospital',
 'Singhania University, Manesar',
 'SkyJumper Trampoline Park',
 'SkyJumper Trampoline Park Gurgaon',
 'Skylark Cricket Academy',
 'Skyview Corporate Park',
 'Sneh Hospital',
 "Sodhi's Supermarket, Sector 82",
 'Sohna Bus Stand',
 'Sohna Gurgaon Road',
 'Sohna Hill Viewpoint',
 'Sohna Road',
 'Sohna road dhunela',
 'Solitaire Banquet Hall',
 'South point Mall',
 'Southern Peripheral Rd',
 'Southern Peripheral Rd, Dhani',
 'Southern Peripheral Rd, Gurugram',
 'Southern Peripheral Road',
 'Southern Periphery Road',
 'Spaze Business Park',
 'Spaze Itech Park',
 'Spaze Palazo, Golf Course Ext Rd',
 'Spazedge IT Park',
 'Spectra Hospital',
 'Splendor Trade Tower',
 'SportsCube Center(Sports Complex)',
 'Sri Ma Montessori International',
 'St Xavier High School',
 "St. Xavier's High School",
 "St. Xavier's School",
 'Star Mall',
 'Starbucks',
 'State Bank of India',
 'Sultanpur National Park',
 'Summer Fields School',
 'Suncity School',
 'Suncity School, Sector 37D',
 'Sunrise University',
 'Sunset point',
 'Suraj PG Degree College, Sec -75',
 'Surajgarh Gurgaon',
 'Surajgarh Gurgaon, Golf Course Ext Rd',
 'Sushant University',
 'Swastik Hospital',
 'Swastik Hospital Sec 66',
 'Swastik Multispeciality Hospital',
 'TERI Golf Course',
 'Taj City Centre Gurugram',
 'Taj City Centre Hotel',
 'Taj Hotel & Family Restaurant',
 'Tau DeviLal Sports Complex',
 'Tennis Vidyalaya (Tennis Academy)',
 'Teri Golf Course',
 'The Banyan Tree Hiking Area',
 'The Banyan Tree World School',
 'The Big Tree Cafe',
 'The Club, International City',
 'The Esplanade Mall',
 'The Executive Centre',
 'The Hive Shopping Mall',
 'The Holy Kingdom Public School',
 'The Medicity, Spaze iTech Park',
 'The NorthCap University',
 'The Oberoi',
 'The Oberoi Gurgaon',
 'The Oberoi, Gurgaon',
 'The Paras World School',
 'The Phoenix Project, Sohna - Gurgaon Rd',
 'The Shikshiyan School',
 'The Shri Ram School Aravali',
 'The Shriram Millennium School',
 'The Signature Advanced Super Speciality',
 'The Signature Super Speciality Hospital',
 'The Sylvan Trails School',
 'The Vivekananda School',
 'The Westin Gurgaon',
 'The Westin Hotel',
 'Tomar Hospital',
 'Trident Hotel Gurgaon',
 'Tulip Violet Society, Sector 69',
 'Uma Sanjeevani Health Centre',
 'Umang Bhawaj Chawk',
 'Umkal Hospital',
 'Unicosmos School',
 'Unitech Business Zone',
 'V Club',
 "V'Lante Mall",
 'V-Square Sohna New Residential',
 'VATIKA BUSINESS PARK Sohna Rd',
 'VIBGYOR High School',
 'Vallores Pre School',
 'Vardaan Hospital',
 'Vardaan Hospital & Trauma Centre',
 'Vardaan Hospital and Trauma Centre',
 'Vardaan hospital and trauma centre',
 'Vasant Kunj',
 'Vatika Business Centre',
 'Vatika Business Park Sector 49',
 'Vatika City Centre',
 'Vatika City Centre Mall',
 'Vatika Sector Road',
 'Vatika Town Square',
 'Vatika Town Square-INXT',
 'Vatika Town Square-INXT Mall',
 'Vedic Hospital',
 'Vega Schools NH-8',
 'Vega Schools Sector 48',
 'Vibrant Hospital',
 'Vidya Niketan Sr Sec School',
 'Vipul Trade Business Centre',
 'Vipul Trade Centre',
 'Vishwas Hospital',
 'Vistar Complex',
 'Vivanta Dwarka New Delhi',
 'Vivanta New Delhi, Dwarka',
 'Vivek Model School',
 'W Pratiksha Hospital',
 'WTC Plaza',
 'Western Peripheral Expressway',
 'Western Peripheral Expy, Gurugram',
 'WorldMark Gurgaon',
 'WorldMark Gurgaon, Maidawas Rd',
 'YES Bank',
 'YES Bank ATM',
 'Yaduvanshi Shiksha Niketan',
 'Yashlok Medical Centre',
 'Yashroop Hospital',
 'ZEN Golf Range & Academy',
 'Zooper India Trampoline Park',
 'iGrow Montessori Play School',
 'iON Digital Zone (Gurugram)',
 'iON Digital Zone, Gurgaon',
 'infinity Business Park',
 'nfinitys Badminton Academy']

In [724]:
location_df[location_df["RPS International School"] +location_df["RPS International School Sector 89"] < 108000][["RPS International School","RPS International School Sector 89"]]

,RPS International School,RPS International School Sector 89
PropertyName,,
Signature Global City 37D Ph 2,3400.0,54000.0
Shree Vardhman Victoria,3400.0,54000.0
BPTP Fortuna,3700.0,3700.0
Golden Park,3800.0,54000.0
Umang Winter Hills,2300.0,54000.0
Mapsko Casa Bella,4200.0,54000.0
Mahindra Aura,3900.0,54000.0
BPTP Mansions Park Prime,3600.0,54000.0

In [723]:
location_df.at["BPTP Fortuna", "RPS International School"] = 3700.0

In [727]:
location_df[location_df["Radisson Hotel"]+location_df["Radisson Hotel Gurugram"]+location_df["Radisson Hotel Gurugram Sohna Road"] +location_df["Radisson Hotel Sohna Road"]  < (4*54000)][["Radisson Hotel","Radisson Hotel Gurugram","Radisson Hotel Gurugram Sohna Road","Radisson Hotel Sohna Road"]]

,Radisson Hotel,Radisson Hotel Gurugram,Radisson Hotel Gurugram Sohna Road,Radisson Hotel Sohna Road
PropertyName,,,,
Bestech Altura,5300.0,5300.0,54000.0,54000.0
Godrej Nature Plus Serenity,54000.0,3300.0,54000.0,54000.0
DLF The Skycourt,54000.0,5000.0,54000.0,5000.0
Godrej Aria,54000.0,5200.0,54000.0,54000.0
Ireo City Plots,54000.0,4400.0,54000.0,54000.0
Bellavista Central Park Resorts,54000.0,4700.0,4700.0,54000.0
Corona Optus,54000.0,7600.0,54000.0,54000.0
Vatika Sovereign Park,54000.0,4700.0,54000.0,4700.0
BPTP Park Generations,54000.0,3500.0,3500.0,54000.0

In [726]:
location_df.at["Bestech Altura", "Radisson Hotel Gurugram"] = 5300.0
location_df.at["DLF The Skycourt", "Radisson Hotel Gurugram"] = 5000.0
location_df.at["Bellavista Central Park Resorts", "Radisson Hotel Gurugram"] = 4700.0
location_df.at["Vatika Sovereign Park", "Radisson Hotel Gurugram"] = 4700.0
location_df.at["BPTP Park Generations", "Radisson Hotel Gurugram"] = 3500.0

In [730]:
location_df[location_df["Rapid Metro Sector 56"] +location_df["Rapid Metro Station Sector 56"] < 108000][["Rapid Metro Sector 56","Rapid Metro Station Sector 56"]]

                   Rapid Metro Sector 56  Rapid Metro Station Sector 56
PropertyName
Tulip Monsella                    5000.0                         5000.0
ROF Insignia Park                54000.0                         3800.0

In [729]:
location_df.at["Tulip Monsella", "Rapid Metro Station Sector 56"] = 5000.0

In [733]:
location_df[location_df["Rion's Hospital"] +location_df["Rions Hospital"] < 108000][["Rion's Hospital","Rions Hospital"]]

                        Rion's Hospital  Rions Hospital
PropertyName
M3M Crown                        3100.0         54000.0
Sobha City                       2400.0         54000.0
BPTP Amstoria                    4900.0         54000.0
M3M Merlin                       5600.0          5600.0
DLF Gardencity Enclave           5700.0         54000.0
Puri The Aravallis               2300.0         54000.0

In [732]:
location_df.at["M3M Merlin", "Rion's Hospital"] = 5600.0

In [736]:
location_df[location_df["Royal Institute Of Science"] +location_df["Royal Institute Of Science & Management"]+location_df["Royal Institute Of Science and Mgt"] < (3*54000)][["Royal Institute Of Science","Royal Institute Of Science & Management","Royal Institute Of Science and Mgt"]]

,Royal Institute Of Science,Royal Institute Of Science & Management,Royal Institute Of Science and Mgt
PropertyName,,,
Ireo Victory Valley,54000.0,3000.0,3000.0
Golden Park,54000.0,1400.0,54000.0
Emaar The Palm Springs,2400.0,2400.0,54000.0

In [735]:
location_df.at["Ireo Victory Valley", "Royal Institute Of Science & Management"] = 3000.0
location_df.at["Emaar The Palm Springs", "Royal Institute Of Science & Management"] = 2400.0

In [739]:
location_df[location_df["SGT UNIVERSITY"] +location_df["SGT University"] < 108000][["SGT UNIVERSITY","SGT University"]]

                            SGT UNIVERSITY  SGT University
PropertyName
Godrej Meridien                    54000.0         11900.0
Tata Primanti                      54000.0          9600.0
Ambience Creacions                 54000.0         10000.0
Parsvnath Exotica                  54000.0          8800.0
Shree Vardhman Victoria            54000.0         11100.0
The Close North                    54000.0          9000.0
Pioneer Park                       54000.0         14400.0
Ramprastha The Edge Towers         54000.0          9000.0
Mapsko Casa Bella                  54000.0         13200.0
Mahindra Aura                      54000.0         12800.0
M3M Woodshire                      11300.0         11300.0
Lion Infra Green Valley            54000.0          8500.0

In [738]:
location_df.at["M3M Woodshire", "SGT University"] = 11300.0

In [742]:
location_df[location_df["SS Omnia, Sector 86"] +location_df["SS Omnia Mall"] < 108000][["SS Omnia, Sector 86","SS Omnia Mall"]]

                                     SS Omnia, Sector 86  SS Omnia Mall
PropertyName
Central Park Flower Valley The Room               3300.0         3300.0
Umang Winter Hills                                1900.0        54000.0

In [741]:
location_df.at["Central Park Flower Valley The Room", "SS Omnia, Sector 86"] = 3300.0

In [745]:
location_df[location_df["Sanjeevani Hospital"] +location_df["Sanjeevani Hospital - Child Specialist"]+location_df["Sanjivani Hospital"] < (3*54000)][["Sanjeevani Hospital","Sanjeevani Hospital - Child Specialist","Sanjivani Hospital"]]

,Sanjeevani Hospital,Sanjeevani Hospital - Child Specialist,Sanjivani Hospital
PropertyName,,,
ROF Normanton Park,2500.0,54000.0,54000.0
Paras Dews,7000.0,54000.0,7000.0
BPTP Mansions Park Prime,2600.0,54000.0,54000.0
BPTP Pedestal,4200.0,4200.0,54000.0

In [744]:
location_df.at["Paras Dews", "Sanjeevani Hospital"] = 7000.0
location_df.at["BPTP Pedestal", "Sanjeevani Hospital"] = 4200.0

In [748]:
location_df[location_df["Sapphire 83 Mall"] +location_df["Sapphire 83 Mall Sector 83"] < 108000][["Sapphire 83 Mall","Sapphire 83 Mall Sector 83"]]

,Sapphire 83 Mall,Sapphire 83 Mall Sector 83
PropertyName,,
DLF Park Place,1700.0,54000.0
Ireo Skyon,4400.0,54000.0
G99,4200.0,54000.0
Emaar MGF Emerald Floors Premier,2700.0,54000.0
DLF The Ultima,3700.0,54000.0
Indiabulls Enigma,5400.0,54000.0
Hero Homes,8600.0,8600.0
M3M Skywalk,2600.0,54000.0
JMS The Nation,7700.0,54000.0
M3M Sierra 68,6100.0,54000.0
DLF The Belaire,6000.0,54000.0
Central Park Flower Valley Aqua Front Towers,2500.0,54000.0
Pioneer Urban Presidia,600.0,54000.0
Shree Vardhman Victoria,7000.0,54000.0
Silverglades The Melia,3400.0,54000.0
DLF The Pinnacle,2100.0,54000.0
Emaar Palm Gardens,6000.0,54000.0
Emaar The Palm Springs,6300.0,54000.0
Puri Diplomatic Greens,1000.0,54000.0
Silverglades Hightown Residences,3200.0,54000.0

In [747]:
location_df.at["Hero Homes", "Sapphire 83 Mall"] = 8600.0

In [751]:
location_df[location_df["Savoy Suites"] +location_df["Savoy Suites, Manesar"] < 108000][["Savoy Suites","Savoy Suites, Manesar"]]

                           Savoy Suites  Savoy Suites, Manesar
PropertyName
Indiabulls Enigma               54000.0                 6900.0
DLF The Belaire                 54000.0                 6100.0
Vatika Independent Floors        6400.0                 6400.0
Emaar Palm Gardens              54000.0                 6200.0

In [750]:
location_df.at["Vatika Independent Floors", "Savoy Suites, Manesar"] = 6400.0

In [757]:
location_df[location_df["Sector 42-43 Metro Station"] +location_df["Sector 42-43 Rapid Metro Station"] < 108000][["Sector 42-43 Metro Station","Sector 42-43 Rapid Metro Station"]]

,Sector 42-43 Metro Station,Sector 42-43 Rapid Metro Station
PropertyName,,
Vatika Aspiration,4400.0,54000.0
M3M Sky Lofts,1800.0,54000.0
Landmark The Homes 81,3600.0,54000.0
Vipul Belmonte,750.0,750.0
La Lagune,1800.0,1800.0

In [756]:
location_df.at["La Lagune", "Sector 42-43 Metro Station"] = 1800.0
location_df.at["Vipul Belmonte", "Sector 42-43 Metro Station"] = 750.0

In [760]:
location_df[location_df["Sector 53 Metro Station"]+location_df["Sector 53-54 Metro Station"]+location_df["Sector 53-54 Rapid Metro"]+location_df["Sector 53/54 Metro Station"]+location_df["Sector 54 Chowk Metro Station"] < (5*54000)][["Sector 53 Metro Station","Sector 53-54 Metro Station","Sector 53-54 Rapid Metro","Sector 53/54 Metro Station","Sector 54 Chowk Metro Station"]]

,Sector 53 Metro Station,Sector 53-54 Metro Station,Sector 53-54 Rapid Metro,Sector 53/54 Metro Station,Sector 54 Chowk Metro Station
PropertyName,,,,,
Signature Global City 92,54000.0,7500.0,54000.0,54000.0,7500.0
Tulip Yellow,54000.0,4100.0,54000.0,54000.0,4100.0
ATS Marigold,54000.0,2700.0,54000.0,54000.0,54000.0
Ansals Shiva Som Valley,54000.0,850.0,54000.0,54000.0,54000.0
Anant Raj Estate Plots,54000.0,700.0,54000.0,700.0,54000.0
Landmark The Homes 81,54000.0,2900.0,54000.0,54000.0,54000.0
Conscient Habitat,54000.0,2100.0,54000.0,54000.0,54000.0
ILD Grand,54000.0,2000.0,54000.0,54000.0,54000.0
Signature Global Solera 2,54000.0,500.0,54000.0,54000.0,54000.0
Breez Global Heights 89,54000.0,1300.0,54000.0,54000.0,54000.0
La Lagune,54000.0,2200.0,2200.0,54000.0,54000.0
Suncity Avenue 102,5200.0,5200.0,54000.0,54000.0,54000.0

In [759]:
location_df.at["Signature Global City 92", "Sector 53-54 Metro Station"] = 7500.0
location_df.at["Tulip Yellow", "Sector 53-54 Metro Station"] = 4100.0
location_df.at["Anant Raj Estate Plots", "Sector 53-54 Metro Station"] = 700.0
location_df.at["La Lagune", "Sector 53-54 Metro Station"] = 2200.0
location_df.at["Suncity Avenue 102", "Sector 53-54 Metro Station"] = 5200.0

In [763]:
location_df[location_df["Sector 55 Metro Station"]+location_df["Sector 55-56 Metro"] +location_df["Sector 55-56 Metro Station"]+location_df["Sector 55-56 Metro station"]+location_df["Sector 55-56 Rapid Metro"]+location_df["Sector 55-56 Rapid Metro Station"]+location_df["Sector 55-56 metro"]+location_df["Sector 55/56 Metro Station"] < (8*54000)][["Sector 55 Metro Station","Sector 55-56 Metro","Sector 55-56 Metro Station","Sector 55-56 Metro station","Sector 55-56 Rapid Metro","Sector 55-56 Rapid Metro Station","Sector 55-56 metro","Sector 55/56 Metro Station"]]

,Sector 55 Metro Station,Sector 55-56 Metro,Sector 55-56 Metro Station,Sector 55-56 Metro station,Sector 55-56 Rapid Metro,Sector 55-56 Rapid Metro Station,Sector 55-56 metro,Sector 55/56 Metro Station
PropertyName,,,,,,,,
Signature Global City 93,54000.0,54000.0,3900.0,54000.0,54000.0,54000.0,54000.0,54000.0
Whiteland The Aspen,54000.0,54000.0,5300.0,54000.0,54000.0,54000.0,54000.0,54000.0
Bestech Altura,54000.0,54000.0,6500.0,54000.0,54000.0,54000.0,54000.0,6500.0
Elan The Presidential,54000.0,54000.0,3600.0,54000.0,54000.0,54000.0,54000.0,54000.0
Signature Global City 81,54000.0,54000.0,6300.0,54000.0,54000.0,6300.0,54000.0,54000.0
SS Linden Floors,54000.0,54000.0,6500.0,54000.0,54000.0,6500.0,54000.0,54000.0
Mahindra Luminare,54000.0,54000.0,10800.0,54000.0,54000.0,54000.0,54000.0,54000.0
Krisumi Waterfall Residences,54000.0,54000.0,10700.0,54000.0,54000.0,54000.0,54000.0,54000.0
Birla Navya,54000.0,54000.0,4400.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Skycity,54000.0,54000.0,7100.0,54000.0,54000.0,54000.0,54000.0,7100.0
Godrej Nature Plus Serenity,54000.0,54000.0,5000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Eldeco Acclaim,54000.0,54000.0,7000.0,54000.0,54000.0,54000.0,54000.0,54000.0
DLF Garden City Floors,54000.0,54000.0,6600.0,54000.0,54000.0,54000.0,54000.0,54000.0
Emaar Emerald Hills,54000.0,54000.0,9200.0,54000.0,54000.0,54000.0,54000.0,54000.0
M3M Golfestate,54000.0,54000.0,1900.0,1900.0,54000.0,54000.0,54000.0,54000.0
ATS Triumph,54000.0,54000.0,3800.0,54000.0,54000.0,54000.0,54000.0,54000.0
Experion The Westerlies,54000.0,54000.0,2700.0,54000.0,54000.0,54000.0,54000.0,54000.0
DLF The Primus,54000.0,54000.0,19400.0,54000.0,54000.0,54000.0,19400.0,54000.0
International City by Sobha Phase 1,54000.0,54000.0,3700.0,54000.0,3700.0,54000.0,54000.0,54000.0
Emaar Imperial Gardens,54000.0,54000.0,3200.0,54000.0,3200.0,54000.0,54000.0,54000.0
Godrej Nature Plus,54000.0,54000.0,5000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Bellavista Central Park Resorts,54000.0,54000.0,9000.0,54000.0,54000.0,54000.0,54000.0,54000.0
Corona Optus,54000.0,54000.0,3000.0,54000.0,3000.0,54000.0,54000.0,54000.0
Vatika Sovereign Next,54000.0,54000.0,4400.0,54000.0,54000.0,54000.0,54000.0,54000.0
Vatika City,54000.0,54000.0,3700.0,54000.0,54000.0,54000.0,54000.0,54000.0
DLF New Town Heights 1,6100.0,54000.0,6100.0,54000.0,54000.0,54000.0,54000.0,54000.0
Orchid IVY Floors,54000.0,3400.0,3400.0,54000.0,54000.0,54000.0,54000.0,54000.0
Raheja Vanya,54000.0,54000.0,6200.0,54000.0,54000.0,54000.0,54000.0,54000.0
Anant Raj Ashok Estate,54000.0,54000.0,21900.0,54000.0,54000.0,54000.0,54000.0,54000.0
Bestech Park View Ananda,54000.0,54000.0,2700.0,54000.0,54000.0,54000.0,54000.0,54000.0
Optimal ultra luxury builder floors,54000.0,54000.0,6300.0,54000.0,54000.0,54000.0,54000.0,54000.0
BPTP Park Generations,54000.0,54000.0,7700.0,54000.0,54000.0,54000.0,54000.0,54000.0

In [762]:
location_df.at["Bestech Altura", "Sector 55-56 Metro Station"] = 6500.0
location_df.at["Signature Global City 81", "Sector 55-56 Metro Station"] = 6300.0
location_df.at["SS Linden Floors", "Sector 55-56 Metro Station"] = 6500.0
location_df.at["M3M Skycity", "Sector 55-56 Metro Station"] = 7100.0
location_df.at["M3M Golfestate", "Sector 55-56 Metro Station"] = 1900.0
location_df.at["DLF The Primus", "Sector 55-56 Metro Station"] = 19400.0
location_df.at["International City by Sobha Phase 1", "Sector 55-56 Metro Station"] = 3700.0
location_df.at["Emaar Imperial Gardens", "Sector 55-56 Metro Station"] = 3200.0
location_df.at["Corona Optus", "Sector 55-56 Metro Station"] = 3000.0
location_df.at["DLF New Town Heights 1", "Sector 55-56 Metro Station"] = 6100.0
location_df.at["Orchid IVY Floors", "Sector 55-56 Metro Station"] = 3400.0

In [770]:
location_df[location_df["Silver Streak Hospital"] +location_df["Silver Streak Multi Speciality"]+location_df["Silver Streak Multi Speciality Hospital"] < (3*54000)][["Silver Streak Hospital","Silver Streak Multi Speciality","Silver Streak Multi Speciality Hospital"]]

,Silver Streak Hospital,Silver Streak Multi Speciality,Silver Streak Multi Speciality Hospital
PropertyName,,,
M3M Heights,54000.0,54000.0,1300.0
Umang Winter Hills,54000.0,2300.0,2300.0
BPTP Mansions Park Prime,1400.0,54000.0,1400.0
Satya The Hermitage,54000.0,54000.0,2800.0

In [769]:
location_df.at["Umang Winter Hills", "Silver Streak Multi Speciality Hospital"] = 2300.0
location_df.at["BPTP Mansions Park Prime", "Silver Streak Multi Speciality Hospital"] = 1400.0

In [773]:
location_df[location_df["SkyJumper Trampoline Park"] +location_df["SkyJumper Trampoline Park Gurgaon"] < 108000][["SkyJumper Trampoline Park","SkyJumper Trampoline Park Gurgaon"]]

,SkyJumper Trampoline Park,SkyJumper Trampoline Park Gurgaon
PropertyName,,
Tulip Monsella,5100.0,54000.0
Signature Global City,3600.0,3600.0
Godrej Nature Plus Serenity,6000.0,54000.0
Yash Vihar,9000.0,54000.0
DLF The Aralias,10100.0,10100.0
Vatika Aspiration,16500.0,16500.0
Rishali Luxe Residency 112,12400.0,12400.0
AIPL The Peaceful Homes,11300.0,11300.0
Experion The Westerlies,10000.0,54000.0
Hero Homes,10200.0,10200.0
Central Park Flower Valley Mikasa Plots,9500.0,54000.0
M3M Skywalk,13400.0,54000.0
Ireo The Grand Arch,10500.0,54000.0
Imperia The Esfera,5900.0,5900.0
Experion The Heartsong,7900.0,54000.0
DLF New Town Heights 2,5200.0,54000.0
DLF The Skycourt,5600.0,54000.0
Central Park Resorts,7300.0,54000.0
Suncity Avenue 76,11300.0,54000.0
Vatika Xpressions,12100.0,54000.0
Anand Niketan,6700.0,54000.0
Godrej Aria,6100.0,54000.0
Ansals Shiva Som Valley,9200.0,54000.0
Vipul World,7800.0,54000.0
Central Park Flower Valley Aqua Front Towers,13500.0,54000.0
Ireo City Plots,4900.0,54000.0
Parsvnath Exotica,10200.0,54000.0
Bellavista Central Park Resorts,9800.0,54000.0
Corona Optus,8200.0,54000.0
Central Park Flower Valley Flamingo Floors,10600.0,54000.0
Indiabulls Centrum Park,10100.0,54000.0
DLF The Pinnacle,13100.0,54000.0
Godrej Oasis,14200.0,54000.0
Mapsko The Icon 79,1800.0,54000.0
Vatika Sovereign Park,5600.0,54000.0
Central Park Flower Valley The Room,12500.0,54000.0
DLF New Town Heights 1,9000.0,54000.0
BPTP Park Generations,3900.0,3900.0

In [772]:
location_df.at["Signature Global City", "SkyJumper Trampoline Park"] = 3600.0
location_df.at["DLF The Aralias", "SkyJumper Trampoline Park"] = 10100.0
location_df.at["Vatika Aspiration", "SkyJumper Trampoline Park"] = 16500.0
location_df.at["Rishali Luxe Residency 112", "SkyJumper Trampoline Park"] = 12400.0
location_df.at["AIPL The Peaceful Homes", "SkyJumper Trampoline Park"] = 11300.0
location_df.at["Hero Homes", "SkyJumper Trampoline Park"] = 10200.0
location_df.at["Imperia The Esfera", "SkyJumper Trampoline Park"] = 5900.0
location_df.at["BPTP Park Generations", "SkyJumper Trampoline Park"] = 3900.0

In [776]:
location_df[location_df["Southern Peripheral Rd"]+location_df["Southern Peripheral Road"]+location_df["Southern Periphery Road"]+location_df["Southern Peripheral Rd, Dhani"]+location_df["Southern Peripheral Rd, Gurugram"] < (5*54000)][["Southern Peripheral Rd","Southern Peripheral Road","Southern Periphery Road","Southern Peripheral Rd, Dhani","Southern Peripheral Rd, Gurugram"]]

,Southern Peripheral Rd,Southern Peripheral Road,Southern Periphery Road,"Southern Peripheral Rd, Dhani","Southern Peripheral Rd, Gurugram"
PropertyName,,,,,
Mahindra Luminare,54000.0,2800.0,54000.0,54000.0,54000.0
Krisumi Waterfall Residences,54000.0,2600.0,54000.0,2600.0,54000.0
Emaar Emerald Hills,54000.0,1300.0,54000.0,54000.0,54000.0
Imperia The Esfera,54000.0,2000.0,54000.0,54000.0,54000.0
Ramprastha Primera,54000.0,6200.0,54000.0,54000.0,54000.0
Godrej Aria,54000.0,6100.0,54000.0,54000.0,54000.0
ROF Insignia Park 2,54000.0,3700.0,54000.0,54000.0,54000.0
Vatika Sovereign Park,54000.0,5600.0,5600.0,54000.0,54000.0
BPTP Park Serene,4900.0,4900.0,54000.0,54000.0,54000.0
BPTP Pedestal,54000.0,3500.0,54000.0,54000.0,3500.0

In [775]:
location_df.at["Krisumi Waterfall Residences", "Southern Peripheral Road"] = 2600.0
location_df.at["Vatika Sovereign Park", "Southern Peripheral Road"] = 5600.0
location_df.at["BPTP Park Serene", "Southern Peripheral Road"] = 4900.0
location_df.at["BPTP Pedestal", "Southern Peripheral Road"] = 3500.0

In [779]:
location_df[location_df["St. Xavier's High School"] +location_df["St. Xavier's School"] < 108000][["St. Xavier's High School","St. Xavier's School"]]

,St. Xavier's High School,St. Xavier's School
PropertyName,,
Central Park Flower Valley Aqua Front Towers,650.0,54000.0
Ireo City Plots,3400.0,3400.0
DLF The Pinnacle,1900.0,54000.0
Ireo Savannah,900.0,54000.0
Signature The Roselia,3300.0,54000.0
Silverglades Hightown Residences,2000.0,54000.0
Optimal ultra luxury builder floors,1100.0,54000.0
Zara Rossa,5700.0,54000.0

In [778]:
location_df.at["Ireo City Plots", "St. Xavier's High School"] = 3400.0

In [782]:
location_df[location_df["Surajgarh Gurgaon"] +location_df["Surajgarh Gurgaon, Golf Course Ext Rd"] < 108000][["Surajgarh Gurgaon","Surajgarh Gurgaon, Golf Course Ext Rd"]]

,Surajgarh Gurgaon,"Surajgarh Gurgaon, Golf Course Ext Rd"
PropertyName,,
Ansals Shiva Som Valley,9500.0,54000.0
Vipul World,5500.0,54000.0
Ireo City Plots,8700.0,54000.0
DLF The Grove,12500.0,54000.0
Corona Optus,5600.0,54000.0
Vatika Sovereign Next,5900.0,54000.0
M3M Sky Lofts,9200.0,54000.0
Orchid IVY Floors,4100.0,4100.0

In [781]:
location_df.at["Orchid IVY Floors", "Surajgarh Gurgaon"] = 4100.0

In [785]:
location_df[location_df["Swastik Hospital"] +location_df["Swastik Hospital Sec 66"]+location_df["Swastik Multispeciality Hospital"] < (3*54000)][["Swastik Hospital","Swastik Hospital Sec 66","Swastik Multispeciality Hospital"]]

,Swastik Hospital,Swastik Hospital Sec 66,Swastik Multispeciality Hospital
PropertyName,,,
Experion The Heartsong,2000.0,54000.0,2000.0
Vatika Sovereign Next,2000.0,54000.0,54000.0
Orchid IVY Floors,800.0,800.0,54000.0

In [784]:
location_df.at["Experion The Heartsong", "Swastik Hospital"] = 2000.0
location_df.at["Orchid IVY Floors", "Swastik Hospital"] = 800.0

In [786]:
location_df.drop(columns=["RPS International School Sector 89","Radisson Hotel","Radisson Hotel Gurugram Sohna Road","Radisson Hotel Sohna Road","Rapid Metro Sector 56","Rions Hospital","Royal Institute Of Science","Royal Institute Of Science and Mgt","SGT UNIVERSITY","SS Omnia Mall","Sanjeevani Hospital - Child Specialist","Sanjivani Hospital","Sapphire 83 Mall Sector 83","Savoy Suites","Sector 42-43 Rapid Metro","Sector 42-43 Rapid Metro Station","Sector 53 Metro Station","Sector 53-54 Rapid Metro","Sector 53/54 Metro Station","Sector 54 Chowk Metro Station","Sector 55 Metro Station","Sector 55-56 Metro","Sector 55-56 Metro station","Sector 55-56 Rapid Metro","Sector 55-56 Rapid Metro Station","Sector 55-56 metro","Sector 55/56 Metro Station","Silver Streak Hospital","Silver Streak Multi Speciality","SkyJumper Trampoline Park Gurgaon","Southern Peripheral Rd","Southern Periphery Road","Southern Peripheral Rd, Dhani","Southern Peripheral Rd, Gurugram","St. Xavier's School","Surajgarh Gurgaon, Golf Course Ext Rd","Swastik Hospital Sec 66","Swastik Multispeciality Hospital"],inplace=True)

In [787]:
location_df.shape

(246, 610)

In [788]:
sorted(location_df.columns.to_list())

['AIPL Business Club',
 'AIPL Joy Street Mall',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Altrade Business Centre',
 'Ambience Mall',
 'Ambience Public School',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Appu Ghar Water Park',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'Bijwasan Railway Station',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CD International School',
 'CK Birla Hospital',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 'Chirag Hospital',
 'Choice pharmacy',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPSG Palam Vihar',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'De Adventure Park',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Entertainland Mall',
 'Eros City Square',
 'Eros Corporate Park',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'Excellere World School',
 'F9 Go Karting Gurgaon',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. PG College',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Greenway Hospital',
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon Dreamz Mall',
 'Gurgaon Gramin Bank',
 'Gurgaon Railway Station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram Global Heights School',
 'Gurugram Road',
 'Gurugram University',
 'Gurukul Preschool',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HP Petrol Pump',
 'HUB 66',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Harsaru Village Bus Stop',
 'Hasanpur',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Hero Honda Chowk',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Hotel Golf View Suites',
 'Huda Metro Station',
 'Huda Park',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency Gurgaon',
 'ICFAI University',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank ATM, Sector 86',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'INOX Cinema',
 'IRIS Broadway Mall',
 'ISBM College',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi International Airport',
 'Indus World School',
 'Indus valley Public School',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Info Technology Park Phase 2',
 'International Tech Park Gurgaon',
 'Iris Broadway Gurugram',
 'Iris Broadway Mall',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'KDM Public School, Sohna',
 'KIIT College of Engineering',
 'KLAY Play School',
 'KMP Expressway',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Keshav Pharmacy',
 'Kidzee Sec-93',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel, Sohna Road',
 "Lingaya's Lalita Devi Institute",
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan Mall',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Matrikiran High School',
 'Matrikiran School',
 "McDonald's India 24 Hours",
 'Medanta -The Medicity',
 'Medeor Hospital, Manesar',
 'Mehrauli-Gurgaon Rd',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Hospital',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'NH 148A',
 'NH 248A',
 'NH 352W',
 'NH 48',
 'NH-8',
 'NH-8, IMT Manesar',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway 8',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'Newtown Square Mall',
 'Nirvana Rd',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open gym garden',
 'Orchid Business Park',
 "Oyster's Water Park",
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Road',
 'Pathfinder Global School, Pataudi',
 'Pathways School Gurgaon',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Pranavananda International School',
 'Primamed Super Speciality Hospital',
 'Prime Scholars International School',
 'Public Bazar',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'Radha Krishan Mandir',
 'Radisson Hotel Gurugram',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Station Sector 56',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rotary Public School',
 'Royal Institute Of Science & Management',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT University',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanskar Bharti Public School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83 Mall',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43 Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 53-54 Metro Station',
 'Sector 55-56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shivai Hospital',
 'Shivani public school',
 'Shree Balaji College',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Multi Speciality Hospital',
 'Singhania University, Manesar',
 'SkyJumper Trampoline Park',
 'Skylark Cricket Academy',
 'Skyview Corporate Park',
 'Sneh Hospital',
 "Sodhi's Supermarket, Sector 82",
 'Sohna Bus Stand',
 'Sohna Gurgaon Road',
 'Sohna Hill Viewpoint',
 'Sohna Road',
 'Sohna road dhunela',
 'Solitaire Banquet Hall',
 'South point Mall',
 'Southern Peripheral Road',
 'Spaze Business Park',
 'Spaze Itech Park',
 'Spaze Palazo, Golf Course Ext Rd',
 'Spazedge IT Park',
 'Spectra Hospital',
 'Splendor Trade Tower',
 'SportsCube Center(Sports Complex)',
 'Sri Ma Montessori International',
 'St Xavier High School',
 "St. Xavier's High School",
 'Star Mall',
 'Starbucks',
 'State Bank of India',
 'Sultanpur National Park',
 'Summer Fields School',
 'Suncity School',
 'Suncity School, Sector 37D',
 'Sunrise University',
 'Sunset point',
 'Suraj PG Degree College, Sec -75',
 'Surajgarh Gurgaon',
 'Sushant University',
 'Swastik Hospital',
 'TERI Golf Course',
 'Taj City Centre Gurugram',
 'Taj City Centre Hotel',
 'Taj Hotel & Family Restaurant',
 'Tau DeviLal Sports Complex',
 'Tennis Vidyalaya (Tennis Academy)',
 'Teri Golf Course',
 'The Banyan Tree Hiking Area',
 'The Banyan Tree World School',
 'The Big Tree Cafe',
 'The Club, International City',
 'The Esplanade Mall',
 'The Executive Centre',
 'The Hive Shopping Mall',
 'The Holy Kingdom Public School',
 'The Medicity, Spaze iTech Park',
 'The NorthCap University',
 'The Oberoi',
 'The Oberoi Gurgaon',
 'The Oberoi, Gurgaon',
 'The Paras World School',
 'The Phoenix Project, Sohna - Gurgaon Rd',
 'The Shikshiyan School',
 'The Shri Ram School Aravali',
 'The Shriram Millennium School',
 'The Signature Advanced Super Speciality',
 'The Signature Super Speciality Hospital',
 'The Sylvan Trails School',
 'The Vivekananda School',
 'The Westin Gurgaon',
 'The Westin Hotel',
 'Tomar Hospital',
 'Trident Hotel Gurgaon',
 'Tulip Violet Society, Sector 69',
 'Uma Sanjeevani Health Centre',
 'Umang Bhawaj Chawk',
 'Umkal Hospital',
 'Unicosmos School',
 'Unitech Business Zone',
 'V Club',
 "V'Lante Mall",
 'V-Square Sohna New Residential',
 'VATIKA BUSINESS PARK Sohna Rd',
 'VIBGYOR High School',
 'Vallores Pre School',
 'Vardaan Hospital',
 'Vardaan Hospital & Trauma Centre',
 'Vardaan Hospital and Trauma Centre',
 'Vardaan hospital and trauma centre',
 'Vasant Kunj',
 'Vatika Business Centre',
 'Vatika Business Park Sector 49',
 'Vatika City Centre',
 'Vatika City Centre Mall',
 'Vatika Sector Road',
 'Vatika Town Square',
 'Vatika Town Square-INXT',
 'Vatika Town Square-INXT Mall',
 'Vedic Hospital',
 'Vega Schools NH-8',
 'Vega Schools Sector 48',
 'Vibrant Hospital',
 'Vidya Niketan Sr Sec School',
 'Vipul Trade Business Centre',
 'Vipul Trade Centre',
 'Vishwas Hospital',
 'Vistar Complex',
 'Vivanta Dwarka New Delhi',
 'Vivanta New Delhi, Dwarka',
 'Vivek Model School',
 'W Pratiksha Hospital',
 'WTC Plaza',
 'Western Peripheral Expressway',
 'Western Peripheral Expy, Gurugram',
 'WorldMark Gurgaon',
 'WorldMark Gurgaon, Maidawas Rd',
 'YES Bank',
 'YES Bank ATM',
 'Yaduvanshi Shiksha Niketan',
 'Yashlok Medical Centre',
 'Yashroop Hospital',
 'ZEN Golf Range & Academy',
 'Zooper India Trampoline Park',
 'iGrow Montessori Play School',
 'iON Digital Zone (Gurugram)',
 'iON Digital Zone, Gurgaon',
 'infinity Business Park',
 'nfinitys Badminton Academy']

In [791]:
location_df[location_df["St Xavier High School"] +location_df["St. Xavier's High School"] < (2*54000)][["St Xavier High School","St. Xavier's High School"]]

,St Xavier High School,St. Xavier's High School
PropertyName,,
Godrej Nature Plus Serenity,300.0,300.0
Central Park Flower Valley Aqua Front Towers,54000.0,650.0
Ireo City Plots,54000.0,3400.0
DLF The Pinnacle,54000.0,1900.0
Ireo Savannah,54000.0,900.0
Signature The Roselia,54000.0,3300.0
Silverglades Hightown Residences,54000.0,2000.0
Optimal ultra luxury builder floors,54000.0,1100.0
Zara Rossa,54000.0,5700.0

In [790]:
location_df.at["Godrej Nature Plus Serenity", "St. Xavier's High School"] = 300.0

In [794]:
location_df[location_df["Taj City Centre Gurugram"] +location_df["Taj City Centre Hotel"]+location_df["Taj Hotel & Family Restaurant"] < (3*54000)][["Taj City Centre Gurugram","Taj City Centre Hotel","Taj Hotel & Family Restaurant"]]

,Taj City Centre Gurugram,Taj City Centre Hotel,Taj Hotel & Family Restaurant
PropertyName,,,
DLF The Icon,54000.0,9600.0,54000.0
M3M Sky Lofts,4000.0,4000.0,54000.0
Vatika The Seven Lamps,54000.0,3400.0,3400.0

In [793]:
location_df.at["M3M Sky Lofts", "Taj City Centre Hotel"] = 4000.0
location_df.at["Vatika The Seven Lamps", "Taj City Centre Hotel"] = 3400.0

In [797]:
location_df[location_df["The Oberoi"] +location_df["The Oberoi Gurgaon"]+location_df["The Oberoi, Gurgaon"] < (3*54000)][["The Oberoi","The Oberoi Gurgaon","The Oberoi, Gurgaon"]]

                          The Oberoi  The Oberoi Gurgaon  The Oberoi, Gurgaon
PropertyName
Signature Global City 81     16000.0             54000.0              16000.0
SS Linden Floors             54000.0             15000.0              15000.0
Saan Verdante                54000.0             54000.0              11300.0
Signature Global Park        54000.0             54000.0               9000.0

In [796]:
location_df.at["Signature Global City 81", "The Oberoi, Gurgaon"] = 16000.0
location_df.at["SS Linden Floors", "The Oberoi, Gurgaon"] = 15000.0

In [800]:
location_df[location_df["The Signature Advanced Super Speciality"] +location_df["The Signature Super Speciality Hospital"] < (2*54000)][["The Signature Advanced Super Speciality","The Signature Super Speciality Hospital"]]

,The Signature Advanced Super Speciality,The Signature Super Speciality Hospital
PropertyName,,
Puri Emerald Bay,6400.0,54000.0
DLF Gardencity,5400.0,5400.0
AIPL The Peaceful Homes,3300.0,54000.0

In [799]:
location_df.at["DLF Gardencity", "The Signature Advanced Super Speciality"] = 5400.0

In [803]:
location_df[location_df["The Westin Gurgaon"] +location_df["The Westin Hotel"] < (2*54000)][["The Westin Gurgaon","The Westin Hotel"]]

                    The Westin Gurgaon  The Westin Hotel
PropertyName
DLF The Grove                  54000.0            3100.0
Mapsko The Icon 79             10600.0           10600.0

In [804]:
location_df.at["Mapsko The Icon 79", "The Westin Hotel"] = 10600.0

In [807]:
location_df[location_df["Vardaan Hospital"]+location_df["Vardaan Hospital & Trauma Centre"]+location_df["Vardaan Hospital and Trauma Centre"] +location_df["Vardaan hospital and trauma centre"]  < (4*54000)][["Vardaan Hospital","Vardaan Hospital & Trauma Centre","Vardaan Hospital and Trauma Centre","Vardaan hospital and trauma centre"]]

,Vardaan Hospital,Vardaan Hospital & Trauma Centre,Vardaan Hospital and Trauma Centre,Vardaan hospital and trauma centre
PropertyName,,,,
DLF The Primus,54000.0,5200.0,54000.0,5200.0
Bestech Park View Spa Next,3700.0,3700.0,54000.0,54000.0
Godrej Air,54000.0,3900.0,54000.0,54000.0
Unitech The Residences,54000.0,2800.0,54000.0,54000.0
Signature Global Solera,54000.0,2900.0,54000.0,54000.0
Vatika India Next Plots,54000.0,3600.0,54000.0,54000.0
MV Buildcon Precore City,54000.0,2800.0,54000.0,54000.0
Signature Global Prime,1700.0,1700.0,54000.0,54000.0
Vatika Express City,54000.0,4700.0,4700.0,54000.0
Pegasus Atulyam 83,7600.0,7600.0,54000.0,54000.0

In [806]:
location_df.at["DLF The Primus", "Vardaan Hospital & Trauma Centre"] = 5200.0
location_df.at["Bestech Park View Spa Next", "Vardaan Hospital & Trauma Centre"] = 3700.0
location_df.at["Signature Global Prime", "Vardaan Hospital & Trauma Centre"] = 1700.0
location_df.at["Vatika Express City", "Vardaan Hospital & Trauma Centre"] = 4700.0
location_df.at["Pegasus Atulyam 83", "Vardaan Hospital & Trauma Centre"] = 7600.0

In [810]:
location_df[location_df["VATIKA BUSINESS PARK Sohna Rd"] +location_df["Vatika Business Park Sector 49"] < (2*54000)][["VATIKA BUSINESS PARK Sohna Rd","Vatika Business Park Sector 49"]]

,VATIKA BUSINESS PARK Sohna Rd,Vatika Business Park Sector 49
PropertyName,,
Signature Global City 37D Ph 2,17000.0,17000.0
BPTP Pedestal,4200.0,54000.0

In [809]:
location_df.at["Signature Global City 37D Ph 2", "VATIKA BUSINESS PARK Sohna Rd"] = 17000.0

In [815]:
location_df[location_df["Vatika City Centre"] +location_df["Vatika City Centre Mall"] < (2*54000)][["Vatika City Centre","Vatika City Centre Mall"]]

                  Vatika City Centre  Vatika City Centre Mall
PropertyName
Godrej Oasis                  2900.0                   2900.0
BPTP Park Serene              3500.0                  54000.0

In [814]:
location_df.at["Godrej Oasis", "Vatika City Centre"] = 2900.0

In [818]:
location_df[location_df["Vatika Town Square"] +location_df["Vatika Town Square-INXT"]+location_df["Vatika Town Square-INXT Mall"] < (3*54000)][["Vatika Town Square","Vatika Town Square-INXT","Vatika Town Square-INXT Mall"]]

,Vatika Town Square,Vatika Town Square-INXT,Vatika Town Square-INXT Mall
PropertyName,,,
BPTP Green Oaks,54000.0,4100.0,54000.0
Vatika Independent Floors,54000.0,5800.0,5800.0
Pioneer Park,54000.0,2700.0,54000.0
Bestech Park View Sanskruti,54000.0,4400.0,54000.0
Orchid Island,54000.0,6400.0,54000.0
Zara Rossa,2000.0,2000.0,54000.0

In [817]:
location_df.at["Vatika Independent Floors", "Vatika Town Square-INXT"] = 5800.0
location_df.at["Zara Rossa", "Vatika Town Square-INXT"] = 2000.0

In [821]:
location_df[location_df["Vipul Trade Business Centre"] +location_df["Vipul Trade Centre"] < (2*54000)][["Vipul Trade Business Centre","Vipul Trade Centre"]]

                       Vipul Trade Business Centre  Vipul Trade Centre
PropertyName
SS The Leaf                                54000.0              2800.0
Godrej Aria                                 5000.0              5000.0
Signature The Roselia                      54000.0              2700.0

In [820]:
location_df.at["Godrej Aria", "Vipul Trade Centre"] = 5000.0

In [824]:
location_df[location_df["Vivanta Dwarka New Delhi"] +location_df["Vivanta New Delhi, Dwarka"] < (2*54000)][["Vivanta Dwarka New Delhi","Vivanta New Delhi, Dwarka"]]

                   Vivanta Dwarka New Delhi  Vivanta New Delhi, Dwarka
PropertyName
Sobha City                           9200.0                    54000.0
BPTP Amstoria                       12700.0                    54000.0
Vatika Xpressions                   13300.0                    13300.0

In [823]:
location_df.at["Vatika Xpressions", "Vivanta Dwarka New Delhi"] = 13300.0

In [827]:
location_df[location_df["Western Peripheral Expressway"] +location_df["Western Peripheral Expy, Gurugram"] < (2*54000)][["Western Peripheral Expressway","Western Peripheral Expy, Gurugram"]]

,Western Peripheral Expressway,"Western Peripheral Expy, Gurugram"
PropertyName,,
Shree Vardhman Victoria,6800.0,54000.0
BPTP Fortuna,18200.0,54000.0
Bestech Park View Spa Next,11800.0,54000.0
Conscient Heritage Max,3300.0,3300.0
Antriksh Heights,10000.0,54000.0
Vatika Express City,12900.0,54000.0
DLF The Summit,9800.0,54000.0

In [826]:
location_df.at["Conscient Heritage Max", "Western Peripheral Expressway"] = 3300.0

In [830]:
location_df[location_df["WorldMark Gurgaon"] +location_df["WorldMark Gurgaon, Maidawas Rd"] < (2*54000)][["WorldMark Gurgaon","WorldMark Gurgaon, Maidawas Rd"]]

                       WorldMark Gurgaon  WorldMark Gurgaon, Maidawas Rd
PropertyName
Whiteland The Aspen               1500.0                         54000.0
Tulip Yellow                      3600.0                         54000.0
Signature The Roselia             5900.0                          5900.0

In [829]:
location_df.at["Signature The Roselia", "WorldMark Gurgaon"] = 5900.0

In [833]:
location_df[location_df["iON Digital Zone (Gurugram)"] +location_df["iON Digital Zone, Gurgaon"] < (2*54000)][["iON Digital Zone (Gurugram)","iON Digital Zone, Gurgaon"]]

,iON Digital Zone (Gurugram),"iON Digital Zone, Gurgaon"
PropertyName,,
DLF The Skycourt,8300.0,8300.0
Indiabulls Centrum Park,54000.0,8200.0

In [832]:
location_df.at["DLF The Skycourt", "iON Digital Zone, Gurgaon"] = 8300.0

In [836]:
location_df[location_df["Infinity Business Park"] +location_df["infinity Business Park"] < (2*54000)][["Infinity Business Park","infinity Business Park"]]

                     Infinity Business Park  infinity Business Park
PropertyName
Anant Raj Estates                    8700.0                 54000.0
Adani Samsara Avasa                  8600.0                  8600.0
DLF The Magnolias                    9100.0                 54000.0
DLF The Aralias                      9400.0                  9400.0
Ansal API Esencia                   10500.0                 54000.0
Ambience Creacions                   9900.0                  9900.0

In [835]:
location_df.at["Adani Samsara Avasa", "Infinity Business Park"] = 8600.0
location_df.at["DLF The Aralias", "Infinity Business Park"] = 9400.0
location_df.at["Ambience Creacions", "Infinity Business Park"] = 9900.0

In [837]:
location_df[location_df["nfinitys Badminton Academy"] +location_df["InfinityS Badminton Academy"] < (2*54000)][["nfinitys Badminton Academy","InfinityS Badminton Academy"]]

                     nfinitys Badminton Academy  InfinityS Badminton Academy
PropertyName
Smart World Orchard                      5500.0                       5500.0

In [842]:
location_df[location_df["Iris Broadway Gurugram"] +location_df["Iris Broadway Mall"] < (2*54000)][["Iris Broadway Gurugram","Iris Broadway Mall"]]

                            Iris Broadway Gurugram  Iris Broadway Mall
PropertyName
Central Park Flower Valley                  8100.0             54000.0
Golden Park                                 4800.0              4800.0

In [841]:
location_df.at["Golden Park", "Iris Broadway Gurugram"] = 4800.0

In [843]:
location_df.drop(columns=["St Xavier High School","Taj City Centre Gurugram","Taj Hotel & Family Restaurant","The Oberoi","The Oberoi Gurgaon","The Signature Super Speciality Hospital","The Westin Gurgaon","Vardaan Hospital","Vardaan Hospital and Trauma Centre","Vardaan hospital and trauma centre","Vatika Business Park Sector 49","Vatika City Centre Mall","Vatika Town Square","Vatika Town Square-INXT Mall","Vipul Trade Business Centre","Vivanta New Delhi, Dwarka","Western Peripheral Expy, Gurugram","WorldMark Gurgaon, Maidawas Rd","iON Digital Zone (Gurugram)","infinity Business Park","nfinitys Badminton Academy","Iris Broadway Mall"],inplace=True)

In [844]:
location_df.shape

(246, 588)

In [845]:
sorted(location_df.columns.to_list())

['AIPL Business Club',
 'AIPL Joy Street Mall',
 'ASF Insignia SEZ',
 'AapnoGhar',
 'Aarvy Healthcare Super Speciality',
 'Aatish Hospital',
 'Accenture DDC5',
 'Adarsh Senior Secondary School',
 'Agri Business Management Collage',
 'Airia Mall',
 'Airport',
 'Alfaa Health Care Hospital',
 'Alpine Convent School',
 'Altrade Business Centre',
 'Ambience Mall',
 'Ambience Public School',
 'Amity University Gurugram',
 'Amma Hospital',
 'Anand Multispeciality Hospital',
 'Anand Preschool',
 'Ananta Hospital',
 'Ansal Plaza',
 'Anya Gurgaon',
 'Apex Plus Hospital',
 'Apollo Pharmacy',
 'Appu Ghar Water Park',
 'Aravalli Hills',
 'Arc Multi Speciality Hospital',
 'Ardee Mall',
 'Artemis Hospital Gurgaon',
 'Aryan Hospital',
 'Ascendas OneHub Gurgaon',
 'Ashiana Anmol  Kid Centric Homes',
 'Ashoka International School',
 'Axis Bank, Sohna Rd',
 'BM College of Technology & Mgmt',
 'BML Munjal University (BMU)',
 'BSF Golf Course',
 'Baba Kanala Chowk',
 'Badsa AMS Hospital',
 'Badshahpur Sohna Rd Hwy',
 'Baghera University',
 'Bajghera Road',
 'Bal Bharati Public School',
 'Balaji Hospital',
 'Banjara Market Gurugram',
 'Bank Of Baroda',
 'Basai Dhankot Railway Station',
 'Basai Enclave Park',
 'Basai Metro Station',
 'Basai Road',
 'Basant Valley Global School',
 'Bestech Business Tower',
 'Bestech Central Square Mall',
 'Bharat Petroleum Retail Outlet',
 'Bharat Petroleum Shree Shyam Filling',
 'Bharat Ram Global School',
 'Bharti International Convent School',
 'Bhondsi Nature Park',
 'Bijwasan Railway Station',
 'Blue Bells Public School',
 'Broadways International School',
 'CANARA BANK',
 'CD International School',
 'CK Birla Hospital',
 'Cambridge Montessori Preschool',
 'Candor TechSpace, Sector 48',
 'Capital Business Park',
 'Capital Cyberscape',
 'Captain Chandan Lal Marg',
 'Central Bank Of India Sohna Rd',
 'Central Park II Road',
 'Central Peripheral Road',
 'Central Plaza Mall',
 'Chauma Road',
 'Chirag Hospital',
 'Choice pharmacy',
 'City Hospital',
 'City Square',
 'Civil Hospital',
 'Cloudnine Hospital Sector 47',
 "Colonel's Central Academy",
 'Conscient One',
 'Cool Deck Coffee',
 'Country Inn & Suites by Radisson',
 'Creative Tennis Academy',
 'Cricket Academy',
 'Cyber \u200b\u200bPark',
 'DLF Golf and Country Club',
 'DPG Degree College',
 'DPG Institute of Technology',
 'DPGITM Engineering College Sector 34',
 'DPS',
 'DPSG Palam Vihar',
 'Damdama Lake',
 'Damdama Lake Rd',
 'Damdama More',
 'Daultabad Stadium',
 'De Adventure Park',
 'Delhi',
 'Delhi Ajmer Expressway',
 'Delhi International Airport',
 'Delhi Jaipur Expressway',
 'Delhi Jaipur Highway',
 'Delhi Public School',
 'Delhi Public School Gurugram Sector 67A',
 'Delhi Public School, Sector 103',
 'Delhi Public School, Sector 84',
 'Dhanwapur Road',
 'Dharampeth Main Road',
 'Dharampur Main Road',
 'Diamond Public School',
 'Discount Department Store',
 'DoubleTree by Hilton Hotel',
 'Dr Naveen Chawla General Physician',
 'Dronacharya College of Engineering',
 'Duke Horse Riding Club',
 'Dwarka',
 'Dwarka Expressway',
 'Dwarka Expressway Link Road',
 'Dwarka Expy, Block D, New Palam Vihar',
 'Dwarka Expy, Dhanwapur Village',
 'Dwarka Expy, Sector 109',
 'Dwarka Expy, Sector 88',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka Sector 21',
 'Dwarka Sector 21 Metro Station',
 'Dwarka expressway Basai crossing',
 'EPF Regional Office',
 'ESIC Dispensary',
 'ESIC Hospital',
 'Edge towers tennis court',
 'Ektaa Hospitals',
 'Elan Miracle Mall',
 'Emaar Business Park',
 'Emerald Plaza Shopping Mall',
 'Entertainland Mall',
 'Eros City Square',
 'Eros Corporate Park',
 'Essar Petrol Pump',
 'Euro Int School, Sector 37D, Gurugram',
 'Euro International School',
 'Euro International School, Sec 84',
 'Euro International School, Sector- 109',
 'Euro International School, sector- 51',
 'Excellere World School',
 'F9 Go Karting Gurgaon',
 'Faridabad Gurgaon Road',
 'Farrukh Nagar Railway Station',
 'Federal Bank Sector 71',
 'First Step Play School',
 'Fitso Sector 48 Spuddy, Badminton',
 'Fly India Adventure Resort',
 'Flying Wings Badminton Academy',
 'Fortis Memorial Research Institute',
 'Fun N Food Village',
 'Fun N Food WaterPark',
 'GD Goenka High School',
 'GD Goenka Public School',
 'GD Goenka Signature School',
 'GD Goenka University, Gurugram',
 'GD Goenka World School',
 'GEMS International School',
 'Galleria 108 Mall',
 'Galleria Market',
 'Garhi Budhera Road',
 'Garhi Harsaru Junction',
 'Garhi harsaru railway station Gurgaon',
 'Genesis Hospital',
 'Genpact Chowk Bus Stop',
 'Global City Centre',
 'Global Foyer Mall',
 'Global Ways School',
 'GlobalHealthcare Multispeciality',
 'Glorious World School',
 'Golden Greens Golf & Resorts',
 'Golden Tulip Suites Gurgaon',
 'Golf Course Extension Road',
 'Golf Pavilion',
 'Govind Hospital',
 'Govt. PG College',
 'Grand Hyatt Gurgaon',
 'Green Field Public School',
 'Greenway Hospital',
 'Gurgaon',
 'Gurgaon - Delhi Expy',
 'Gurgaon Dreamz Mall',
 'Gurgaon Gramin Bank',
 'Gurgaon Railway Station',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Gurugram Global Heights School',
 'Gurugram Road',
 'Gurugram University',
 'Gurukul Preschool',
 'Gyan Bharti Public School',
 'HDFC Bank',
 'HDFC Bank ATM',
 'HP Petrol Pump',
 'HUB 66',
 'HUDA Market, Sector 14',
 'HUDA Metro Station',
 'HUDA Mini Golf Course',
 'Hamoni Golf Camp',
 'Harsaru Village Bus Stop',
 'Hasanpur',
 'Health care pharmacy',
 'Heritage Badminton Academy',
 'Heritage Intl Xperiential School',
 'Heritage School',
 'Heritage Village Resort & Spa',
 'Heritage Xperiential Learning School',
 'Hero Honda Chowk',
 'Holiday Inn Express Gurugram Sector 50',
 'Holiday Inn Gurugram Sector 90',
 'Holiday Inn Sector 90',
 'Hong Kong Bazaar',
 'Hotel Golf View Suites',
 'Huda Metro Station',
 'Huda Park',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Hyatt Regency Gurgaon',
 'ICFAI University',
 'ICICI BANK ATM, Annapurna MKT',
 'ICICI Bank ATM, Sector 86',
 'IILM University, Gurugram',
 'IMT Manesar',
 'IMT Office Sohna',
 'IMT Road',
 'INOX Cinema',
 'IRIS Broadway Mall',
 'ISBM College',
 'Idea Cosmic Plaza',
 'Iffco Chowk',
 'Iffco Chowk Metro Station',
 'Imperia Mindspace',
 'Imperial Heritage School',
 'Imperio School',
 'Indian School of Hospitality',
 'IndianOil, Hasanpur',
 'Indianoil, Sohna - Gurgaon Rd',
 'Indira Gandhi Eye Hospital',
 'Indira Gandhi International Airport',
 'Indus World School',
 'Indus valley Public School',
 'Infinity Business Park',
 'InfinityS Badminton Academy',
 'Info Technology Park Phase 2',
 'International Tech Park Gurgaon',
 'Iris Broadway Gurugram',
 'JMD Megapolis',
 'JMD Regent Mall',
 'JMS Crosswalk',
 'JMS Marine Square Mall',
 'Jadon Pharmacy',
 'Jai Sai Ram Hospital',
 'Jhankar Group of Institutions',
 'Jhankar Senior Secondary School',
 'Jharsha Chowk',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'K.D. Hospital',
 'K.R. Mangalam University',
 'KDM Public School, Sohna',
 'KIIT College of Engineering',
 'KLAY Play School',
 'KMP Expressway',
 'KR Mangalam University Sohna',
 'Kadipur Industrial Area',
 'Kamal Hospital',
 'Keshav Pharmacy',
 'Kidzee Sec-93',
 'Kingdom of Dreams',
 'Kings International School',
 'Knowledge Tree World School',
 'Kotak Mahindra Bank, MBS Tower',
 'Krishna Hospital',
 'Kriti Hospital',
 'Kunskapsskolan International',
 'Kunskapsskolan School',
 'Kutumbh Hospital',
 'Lancers International School',
 'Le Meridien Gurgaon',
 'Leisure Valley Park',
 'Lemon Tree Hotel',
 'Lemon Tree Hotel Sector 60',
 'Lemon Tree Hotel, Sohna Road',
 "Lingaya's Lalita Devi Institute",
 'Little E Step –Pre School',
 'Lotus Sports Academy',
 'Lotus Valley International School',
 'Lovely Public School',
 'Luxus Haritma Resort',
 'M3M Cosmopolitan Mall',
 'M3M International Financial Center (IFC)',
 'M3M SCO Shop cum Office',
 'M3m 65th Avenue Mall',
 'MDS Public School',
 'MG Road',
 'MG Road Metro Station',
 'MGF Metropolitan Mall',
 'MKD Hospital',
 'Maharana pratap school',
 'Mall Fifty One',
 'Manesar Bus Stand',
 'Manesar Golf Course',
 'Manesar Road',
 'Manesar toll plaza - Kherki Daula',
 'Manipal Hospital',
 'Manipal Hospital, Gurugram',
 'Manipal Hospital, Palam Vihar',
 'Manish Gallexie 91',
 'Marengo Asia Hospitals',
 'Matrikiran High School',
 'Matrikiran School',
 "McDonald's India 24 Hours",
 'Medanta -The Medicity',
 'Medeor Hospital, Manesar',
 'Mehrauli-Gurgaon Rd',
 'Metro Hospital, Palam Vihar',
 'Metro Station Kankrola sec 87',
 'Metro World Mall',
 'Minda Industries  Corporate Office',
 'Minda Industries Limited',
 'Minda Industries Nawada Fatehpur',
 'Miracles Apollo Cradle',
 'Miracles Apollo Cradle /Spectra Hospital',
 'Miracles Apollo Cradle Hospital',
 'Miracles Apollo Hospital',
 'More Hypermart , Vipul business park',
 'Mother land public school',
 'Moulsari Avenue',
 'Mount Olympus Junior School',
 'Mount Olympus School, Sec 79',
 'Mps World School',
 'Muincipal Corporation of Gurugram',
 'Museum of Folk and Tribal Art',
 'NH 148A',
 'NH 248A',
 'NH 352W',
 'NH 48',
 'NH-8',
 'NH-8, IMT Manesar',
 'Najafgarh Jheel Bird Sanctuary',
 'Najafgarh Kapashera Road',
 'Nakhrola Stadium',
 'Narayana E Techno',
 'Narayana Junior College',
 'Narayana e Techno School',
 'Narayana e-Techno School - Manesar',
 'National Highway 8',
 'National Tennis Academy',
 'National Tennis Academy Sector 98',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'Nawada Cricket Accadmy',
 'Nazafgarh - Gurgaon Road',
 'Nehru Stadium',
 'NeoSquare Shopping Mall',
 'Netaji Subhash Marg',
 'Newtown Square Mall',
 'Nirvana Rd',
 'Northern Peripheral Road',
 'Nouveau Medics Multispeciality OPD',
 'Numberdar market, IMT Manesar',
 'ORCHIDS The International School',
 'Ocus Medley Mall',
 'Old Delhi Gurgaon Road',
 'Old Sohna Dhani Road',
 'Omaxe Celebration Mall',
 'Omaxe City Centre',
 'Omaxe City Centre Mall',
 'Omaxe Gurgaon Mall',
 'Ompee International School',
 'One Horizon Center Bus Stop',
 'Open gym garden',
 'Orchid Business Park',
 "Oyster's Water Park",
 'PVR Drive in Theatre',
 'Pacific D21 Mall',
 'Palam Vihar Halt',
 'Palam Vihar Halt Railway Station',
 'Pallavan PreSchool, Sohna Road',
 'Paras Hospitals, Gurgaon',
 'Paras Trinity Mall',
 'Park Dr, DLF Phase 5',
 'Park Hospital',
 'Park Inn',
 'Pasco Automobiles, Alipur, Sohna',
 'Pataudi Road',
 'Pathfinder Global School, Pataudi',
 'Pathways School Gurgaon',
 'Patli Railway Station',
 'Pawlywoof - Dog Park',
 'Phase 2 Metro Station',
 'Plaza Mall',
 'Polaris Hospital',
 'Pragyanam School',
 'Pranavananda International School',
 'Primamed Super Speciality Hospital',
 'Prime Scholars International School',
 'Public Bazar',
 'Pushpanjali Hospital',
 'Quality Inn Gurgaon',
 'Qutub Plaza',
 'RBSM Public school',
 'RELIANCE TRENDS Newtown Square Mall',
 'RHM Public School',
 'RPS International School',
 'Radha Krishan Mandir',
 'Radisson Hotel Gurugram',
 'Raghunath Bal Vidya Mandir School',
 'Raheja Mall',
 'Rajesh Pilot Road',
 'Rajiv Chowk',
 'Ramada by Wyndham Gurgaon',
 'Ramgarh Farms & Resort',
 'Ramprastha Police Post',
 'Rampura Flyover, Naurangpur Rd',
 'Rao Bharat Singh International School',
 'Rapid Metro Station Sector 56',
 'Reach 3 Roads Shopping Mall',
 'Red Roses Public School',
 'Reliance Trends Newtown Square Mall',
 "Rion's Hospital",
 'Rotary Public School',
 'Royal Institute Of Science & Management',
 'Rx Pharmacy',
 'S N International School',
 'SCC Drive-In Cinema',
 'SCC Rooftop Drive-In',
 'SCR Model School',
 'SGT Hospital 1',
 'SGT Medical College',
 'SGT University',
 'SS Omnia, Sector 86',
 'Sahara Mall',
 'Sai Sports Club cricket ground',
 "Saint Paul's School",
 'Samrat Mihir Bhoj Road',
 'Sanar International Hospital',
 'Sanjeevani Hospital',
 'Sanskar Bharti Public School',
 'Sant Soordas Sihi Metro Station',
 'Sapphire 83 Mall',
 'Sapphire 93 Mall',
 'Sapphire Mall',
 'Saraswati Model School',
 'Satya The Hive Mall',
 'Satyam Medicare Hospital',
 'Savoy Suites, Manesar',
 'Scottish High International School',
 'Sealdah',
 'Sealdah Railway Station',
 'Sector 10 Market',
 'Sector 29 Gurgaon Pubs and Bars',
 'Sector 37 Police Station',
 'Sector 42-43 Metro Station',
 'Sector 42/43 Bus Stand',
 'Sector 53-54 Metro Station',
 'Sector 55-56 Metro Station',
 'Sector 84 Road',
 'Sector 86 Road',
 'Sector-21 Metro Dwarka',
 'Sethi Hospital',
 'Shalom Hills International School',
 'Shalom Presidency School',
 'Shambhu Dayal High School',
 'Shanti Tennis Academy',
 'Sheetla Mata Mandir',
 'Shiksha Bharti Public School',
 'Shiv Mandir',
 'Shiv Nadar School',
 'Shivai Hospital',
 'Shivani public school',
 'Shree Balaji College',
 'Shree Krishna Hospital',
 'Shri Balaji’s Multispeciality Hospital',
 'Signature Advanced Hospital',
 'Signature Global Infinity Mall Sohna',
 'Signature Global Park',
 'Signature Super Speciality Hospital',
 'Signature tower',
 'Signum 107',
 'Signum 36',
 'Silver Streak Multi Speciality Hospital',
 'Singhania University, Manesar',
 'SkyJumper Trampoline Park',
 'Skylark Cricket Academy',
 'Skyview Corporate Park',
 'Sneh Hospital',
 "Sodhi's Supermarket, Sector 82",
 'Sohna Bus Stand',
 'Sohna Gurgaon Road',
 'Sohna Hill Viewpoint',
 'Sohna Road',
 'Sohna road dhunela',
 'Solitaire Banquet Hall',
 'South point Mall',
 'Southern Peripheral Road',
 'Spaze Business Park',
 'Spaze Itech Park',
 'Spaze Palazo, Golf Course Ext Rd',
 'Spazedge IT Park',
 'Spectra Hospital',
 'Splendor Trade Tower',
 'SportsCube Center(Sports Complex)',
 'Sri Ma Montessori International',
 "St. Xavier's High School",
 'Star Mall',
 'Starbucks',
 'State Bank of India',
 'Sultanpur National Park',
 'Summer Fields School',
 'Suncity School',
 'Suncity School, Sector 37D',
 'Sunrise University',
 'Sunset point',
 'Suraj PG Degree College, Sec -75',
 'Surajgarh Gurgaon',
 'Sushant University',
 'Swastik Hospital',
 'TERI Golf Course',
 'Taj City Centre Hotel',
 'Tau DeviLal Sports Complex',
 'Tennis Vidyalaya (Tennis Academy)',
 'Teri Golf Course',
 'The Banyan Tree Hiking Area',
 'The Banyan Tree World School',
 'The Big Tree Cafe',
 'The Club, International City',
 'The Esplanade Mall',
 'The Executive Centre',
 'The Hive Shopping Mall',
 'The Holy Kingdom Public School',
 'The Medicity, Spaze iTech Park',
 'The NorthCap University',
 'The Oberoi, Gurgaon',
 'The Paras World School',
 'The Phoenix Project, Sohna - Gurgaon Rd',
 'The Shikshiyan School',
 'The Shri Ram School Aravali',
 'The Shriram Millennium School',
 'The Signature Advanced Super Speciality',
 'The Sylvan Trails School',
 'The Vivekananda School',
 'The Westin Hotel',
 'Tomar Hospital',
 'Trident Hotel Gurgaon',
 'Tulip Violet Society, Sector 69',
 'Uma Sanjeevani Health Centre',
 'Umang Bhawaj Chawk',
 'Umkal Hospital',
 'Unicosmos School',
 'Unitech Business Zone',
 'V Club',
 "V'Lante Mall",
 'V-Square Sohna New Residential',
 'VATIKA BUSINESS PARK Sohna Rd',
 'VIBGYOR High School',
 'Vallores Pre School',
 'Vardaan Hospital & Trauma Centre',
 'Vasant Kunj',
 'Vatika Business Centre',
 'Vatika City Centre',
 'Vatika Sector Road',
 'Vatika Town Square-INXT',
 'Vedic Hospital',
 'Vega Schools NH-8',
 'Vega Schools Sector 48',
 'Vibrant Hospital',
 'Vidya Niketan Sr Sec School',
 'Vipul Trade Centre',
 'Vishwas Hospital',
 'Vistar Complex',
 'Vivanta Dwarka New Delhi',
 'Vivek Model School',
 'W Pratiksha Hospital',
 'WTC Plaza',
 'Western Peripheral Expressway',
 'WorldMark Gurgaon',
 'YES Bank',
 'YES Bank ATM',
 'Yaduvanshi Shiksha Niketan',
 'Yashlok Medical Centre',
 'Yashroop Hospital',
 'ZEN Golf Range & Academy',
 'Zooper India Trampoline Park',
 'iGrow Montessori Play School',
 'iON Digital Zone, Gurgaon']

In [848]:
location_df[location_df["DPS"] +location_df["Delhi Public School"] < (2*54000)][["DPS","Delhi Public School"]]

                              DPS  Delhi Public School
PropertyName
Signature Global City 81  54000.0               6600.0
Tulip Monsella              850.0                850.0
M3M Skycity                1500.0               1500.0
Oxirich Chintamanis       54000.0                650.0
Experion Windchants       54000.0               3500.0
Smart World Gems          54000.0               3500.0
DLF New Town Heights 1     1400.0               1400.0
Zara Rossa                 4000.0               4000.0

In [847]:
location_df.at["Tulip Monsella", "Delhi Public School"] = 850.0
location_df.at["M3M Skycity", "Delhi Public School"] = 1500.0
location_df.at["DLF New Town Heights 1", "Delhi Public School"] = 1400.0
location_df.at["Zara Rossa", "Delhi Public School"] = 4000.0

In [851]:
location_df[location_df["Fun N Food Village"] +location_df["Fun N Food WaterPark"] < (2*54000)][["Fun N Food Village","Fun N Food WaterPark"]]

                            Fun N Food Village  Fun N Food WaterPark
PropertyName
Smartworld One DXP                     54000.0                8800.0
Saan Verdante                          12900.0               54000.0
4S Aradhya Homes                        3200.0                3200.0
Pioneer Araya                           8100.0                8100.0
M3M Merlin                             12100.0               12100.0
Vatika Aspiration                      10600.0               54000.0
Rishali Luxe Residency 112             15900.0               54000.0
Vatika Xpressions                      14100.0               54000.0
Ansals Shiva Som Valley                11500.0               54000.0

In [850]:
location_df.at["4S Aradhya Homes", "Fun N Food Village"] = 3200.0
location_df.at["Pioneer Araya", "Fun N Food Village"] = 8100.0
location_df.at["M3M Merlin", "Fun N Food Village"] = 12100.0

In [854]:
location_df[location_df["Holiday Inn Gurugram Sector 90"] +location_df["Holiday Inn Sector 90"] < (2*54000)][["Holiday Inn Gurugram Sector 90","Holiday Inn Sector 90"]]

,Holiday Inn Gurugram Sector 90,Holiday Inn Sector 90
PropertyName,,
Oxirich Chintamanis,2700.0,54000.0
Signature Global City 37D Ph 2,4100.0,54000.0
Yash Vihar,12900.0,54000.0
International City by SOBHA Phase 2,9100.0,54000.0
Ireo Victory Valley,2300.0,54000.0
AIPL The Peaceful Homes,11900.0,54000.0
Hero Homes,8700.0,54000.0
Central Park Flower Valley Mikasa Plots,10300.0,10300.0
M3M Skywalk,3000.0,54000.0
JMS The Nation,3100.0,54000.0
Ambience Creacions,10500.0,54000.0
M3M Sierra 68,1700.0,54000.0
Tulip Violet,1900.0,54000.0
Suncity Platinum Towers,7200.0,54000.0
Bestech Park View Grand Spa,2500.0,54000.0
Shree Vardhman Victoria,5500.0,54000.0
Shree Vardhman Flora,5600.0,5600.0
M3M Heights,2100.0,2100.0
Indiabulls Centrum Park,9000.0,54000.0
BPTP Fortuna,2000.0,2000.0
Golden Park,3500.0,3500.0
Emaar The Palm Springs,2000.0,54000.0
Umang Winter Hills,1600.0,54000.0

In [853]:
location_df.at["Central Park Flower Valley Mikasa Plots", "Holiday Inn Gurugram Sector 90"] = 10300.0
location_df.at["Shree Vardhman Flora", "Holiday Inn Gurugram Sector 90"] = 5600.0
location_df.at["M3M Heights", "Holiday Inn Gurugram Sector 90"] = 2100.0
location_df.at["BPTP Fortuna", "Holiday Inn Gurugram Sector 90"] = 2000.0
location_df.at["Golden Park", "Holiday Inn Gurugram Sector 90"] = 3500.0

In [857]:
location_df[location_df["Airport"] +location_df["Delhi International Airport"]+location_df["Indira Gandhi International Airport"] < (3*54000)][["Airport","Delhi International Airport","Indira Gandhi International Airport"]]

,Airport,Delhi International Airport,Indira Gandhi International Airport
PropertyName,,,
Smartworld One DXP,54000.0,54000.0,14700.0
M3M Crown,54000.0,54000.0,15600.0
Adani Brahma Samsara Vilasa,54000.0,54000.0,20800.0
Sobha City,54000.0,54000.0,16100.0
Signature Global City 93,54000.0,54000.0,24800.0
Whiteland The Aspen,54000.0,54000.0,22700.0
Bestech Altura,54000.0,54000.0,25200.0
Elan The Presidential,54000.0,54000.0,21000.0
Signature Global City 92,54000.0,54000.0,24200.0
Signature Global City 79B,54000.0,54000.0,23600.0
DLF The Arbour,54000.0,54000.0,16400.0
Signature Global City 81,54000.0,54000.0,24100.0
SS Linden Floors,54000.0,54000.0,22700.0
Mahindra Luminare,54000.0,54000.0,25600.0
M3M Golf Hills,54000.0,54000.0,25300.0
Whiteland Blissville,54000.0,54000.0,26500.0
Tulip Monsella,54000.0,54000.0,22800.0
Krisumi Waterfall Residences,54000.0,54000.0,25400.0
M3M Capital,54000.0,54000.0,18900.0
Godrej Meridien,54000.0,54000.0,28500.0
Birla Navya,54000.0,54000.0,22500.0
Signature Global City,54000.0,54000.0,19000.0
Godrej 101,54000.0,54000.0,21500.0
M3M Soulitude,54000.0,54000.0,25800.0
M3M Skycity,54000.0,54000.0,22800.0
Godrej Nature Plus Serenity,54000.0,54000.0,22500.0
SS The Leaf,54000.0,54000.0,22800.0
Eldeco Acclaim,54000.0,54000.0,24100.0
Emaar Gurgaon Greens,54000.0,54000.0,17800.0
Oxirich Chintamanis,54000.0,54000.0,27700.0
DLF Garden City Floors,54000.0,54000.0,21300.0
Tulip Yellow,54000.0,54000.0,20400.0
BPTP Amstoria,54000.0,54000.0,19500.0
Emaar Emerald Hills,54000.0,54000.0,24100.0
M3M Golfestate,54000.0,54000.0,19300.0
ATS Triumph,54000.0,54000.0,21800.0
ATS Marigold,54000.0,54000.0,17500.0
DLF Alameda,54000.0,54000.0,18100.0
Experion Windchants,54000.0,54000.0,23700.0
Saan Verdante,54000.0,54000.0,18900.0
4S Aradhya Homes,54000.0,54000.0,11000.0
Yash Vihar,54000.0,54000.0,22800.0
Smart World Orchard,54000.0,54000.0,22800.0
DLF The Camellias,54000.0,54000.0,35300.0
Adani Samsara Avasa,54000.0,54000.0,23200.0
DLF The Magnolias,54000.0,54000.0,25000.0
DLF The Aralias,54000.0,54000.0,21700.0
Pioneer Araya,54000.0,54000.0,14100.0
M3M Merlin,54000.0,54000.0,19300.0
Smart World Gems,54000.0,54000.0,22100.0
Vatika Aspiration,54000.0,54000.0,14700.0
Ace Palm Floors,54000.0,54000.0,19600.0
DLF Gardencity Enclave,54000.0,54000.0,17700.0
Emaar Palm Heights,54000.0,54000.0,15500.0
Signature Global Park,54000.0,54000.0,15000.0
Emaar MGF Marbella,54000.0,54000.0,16900.0
Rishali Luxe Residency 112,54000.0,54000.0,21800.0
Puri The Aravallis,54000.0,54000.0,16700.0
International City by SOBHA Phase 2,54000.0,54000.0,25300.0
Emaar MGF The Palm Drive,54000.0,54000.0,16500.0
BPTP Green Oaks,54000.0,54000.0,28000.0
Ireo Victory Valley,54000.0,54000.0,31000.0
DLF Gardencity,54000.0,54000.0,24200.0
Tata Primanti,54000.0,54000.0,30000.0
DLF Park Place,54000.0,54000.0,28000.0
Central Park Flower Valley,54000.0,54000.0,32700.0
Ireo Skyon,54000.0,54000.0,29200.0
AIPL The Peaceful Homes,54000.0,54000.0,25300.0
Adani M2K Oyster Grande,54000.0,54000.0,28600.0
G99,54000.0,54000.0,24700.0
Emaar MGF Emerald Floors Premier,54000.0,54000.0,28100.0
ROF Insignia Park,54000.0,54000.0,21100.0
DLF The Ultima,54000.0,54000.0,25900.0
Indiabulls Enigma,54000.0,54000.0,31000.0
Experion The Westerlies,54000.0,54000.0,20600.0
Hero Homes,54000.0,54000.0,26600.0
Central Park Flower Valley Mikasa Plots,54000.0,54000.0,24300.0
M3M Skywalk,54000.0,54000.0,29900.0
Ireo The Grand Arch,54000.0,54000.0,25700.0
JMS The Nation,54000.0,54000.0,32400.0
Imperia The Esfera,54000.0,54000.0,22800.0
Ramprastha Primera,54000.0,54000.0,27500.0
Experion The Heartsong,54000.0,54000.0,20600.0
DLF New Town Heights 2,54000.0,54000.0,24800.0
DLF The Primus,54000.0,54000.0,34500.0
DLF The Skycourt,54000.0,54000.0,24000.0
Central Park Resorts,54000.0,54000.0,29100.0
Suncity Avenue 76,54000.0,54000.0,27700.0
International City by Sobha Phase 1,54000.0,54000.0,21100.0
Ambience Creacions,54000.0,54000.0,24500.0
Vatika Xpressions,54000.0,54000.0,20500.0
M3M Sierra 68,54000.0,54000.0,31600.0
Anand Niketan,54000.0,54000.0,25900.0
DLF The Belaire,54000.0,54000.0,31200.0
Godrej Aria,54000.0,54000.0,30300.0
Ansals Shiva Som Valley,54000.0,54000.0,15600.0
Vipul World,54000.0,54000.0,19900.0
Central Park Flower Valley Aqua Front Towers,54000.0,54000.0,30000.0
Tulip Violet,54000.0,54000.0,30500.0
Eldeco Accolade,54000.0,54000.0,20300.0
M3M Natura,54000.0,54000.0,20400.0
Emaar Imperial Gardens,54000.0,54000.0,21000.0
Ireo City Plots,54000.0,54000.0,23400.0
Parsvnath Exotica,54000.0,54000.0,25400.0
Pioneer Urban Presidia,54000.0,54000.0,27300.0
Suncity Platinum Towers,54000.0,54000.0,28300.0
Godrej Nature Plus,54000.0,54000.0,20100.0
Bestech Park View Grand Spa,54000.0,54000.0,32400.0
Shree Vardhman Victoria,54000.0,54000.0,31000.0
Silverglades The Melia,54000.0,54000.0,29500.0
Shree Vardhman Flora,54000.0,54000.0,32700.0
Vatika Seven Elements,54000.0,54000.0,28500.0
Bellavista Central Park Resorts,54000.0,54000.0,27800.0
M3M Heights,54000.0,54000.0,34300.0
Adani Brahma Samsara,54000.0,54000.0,31500.0
DLF The Grove,54000.0,54000.0,16100.0
Corona Optus,54000.0,54000.0,20400.0
Central Park Flower Valley Flamingo Floors,54000.0,54000.0,19400.0
ROF Insignia Park 2,54000.0,54000.0,24800.0
Indiabulls Centrum Park,54000.0,54000.0,26500.0
BPTP Fortuna,54000.0,54000.0,34200.0
Bestech Park View Spa Next,54000.0,54000.0,35800.0
DLF The Pinnacle,54000.0,54000.0,29600.0
Godrej Oasis,54000.0,54000.0,28200.0
Anant Raj Estate Plots,54000.0,54000.0,15500.0
Mapsko The Icon 79,54000.0,54000.0,19600.0
DLF The Icon,54000.0,54000.0,20200.0
Vatika Sovereign Park,54000.0,54000.0,28500.0
Vatika Sovereign Next,54000.0,54000.0,22600.0
Central Park Flower Valley The Room,54000.0,54000.0,28900.0
M3M Sky Lofts,54000.0,54000.0,15200.0
Golden Park,54000.0,54000.0,32500.0
Ashiana Amarah,54000.0,54000.0,21300.0
Vatika City,54000.0,54000.0,23100.0
DLF New Town Heights 1,54000.0,54000.0,22900.0
Vatika Gurgaon 21,54000.0,23400.0,23400.0
Vatika Independent Floors,54000.0,54000.0,31400.0
Emaar Palm Gardens,54000.0,54000.0,31200.0
The Close North,54000.0,54000.0,22800.0
Emaar The Palm Springs,54000.0,54000.0,31000.0
BPTP Park Serene,54000.0,54000.0,27900.0
Orchid IVY Floors,54000.0,54000.0,22500.0
Paras Ekam Homes,54000.0,54000.0,19400.0
Landmark The Homes 81,54000.0,54000.0,17200.0
ROF Normanton Park,54000.0,54000.0,35300.0
Silverglades Hightown Residences,54000.0,54000.0,29400.0
Pioneer Park,54000.0,54000.0,29400.0
Anant Raj Ashok Estate,54000.0,54000.0,37100.0
Paras Dews,54000.0,54000.0,35600.0
Bestech Park View Sanskruti,54000.0,54000.0,30100.0
Signature Global the Millennia,54000.0,54000.0,23000.0
Orchid Island,54000.0,54000.0,32100.0
Ramprastha The Edge Towers,54000.0,54000.0,30200.0
Bestech Park View Ananda,54000.0,54000.0,20100.0
Mapsko Casa Bella,54000.0,54000.0,30900.0
Mahindra Aura,54000.0,54000.0,33400.0
Godrej Air,54000.0,54000.0,36700.0
Conscient Habitat,54000.0,54000.0,16900.0
Conscient Heritage Max,54000.0,54000.0,36500.0
Vipul Belmonte,54000.0,54000.0,16300.0
Unitech The Residences,54000.0,54000.0,40900.0
ILD Grand,54000.0,54000.0,16800.0
Signature Global Solera 2,54000.0,54000.0,14500.0
Signature Global Solera,54000.0,54000.0,40900.0
M3M Woodshire,54000.0,54000.0,25900.0
Vatika India Next Plots,54000.0,54000.0,35800.0
MV Buildcon Precore City,54000.0,54000.0,36600.0
Lion Infra Green Valley,54000.0,54000.0,32600.0
Yashika 104,54000.0,54000.0,5000.0
Satya The Hermitage,35100.0,54000.0,35100.0

In [856]:
location_df.at["Vatika Gurgaon 21", "Indira Gandhi International Airport"] = 23400.0
location_df.at["Satya The Hermitage", "Indira Gandhi International Airport"] = 35100.0

In [860]:
location_df[location_df["Miracles Apollo Cradle"]+location_df["Miracles Apollo Cradle /Spectra Hospital"]+location_df["Miracles Apollo Cradle Hospital"] +location_df["Miracles Apollo Hospital"]  < (4*54000)][["Miracles Apollo Cradle","Miracles Apollo Cradle /Spectra Hospital","Miracles Apollo Cradle Hospital","Miracles Apollo Hospital"]]

,Miracles Apollo Cradle,Miracles Apollo Cradle /Spectra Hospital,Miracles Apollo Cradle Hospital,Miracles Apollo Hospital
PropertyName,,,,
Oxirich Chintamanis,54000.0,2900.0,2900.0,54000.0
DLF The Ultima,54000.0,54000.0,6000.0,54000.0
Indiabulls Enigma,54000.0,54000.0,4800.0,4800.0
DLF The Belaire,54000.0,54000.0,5500.0,54000.0
Pioneer Urban Presidia,54000.0,54000.0,2200.0,54000.0
Adani Brahma Samsara,54000.0,54000.0,4500.0,4500.0
DLF The Pinnacle,54000.0,800.0,800.0,54000.0
Ireo Savannah,1600.0,54000.0,1600.0,54000.0
Vatika Independent Floors,54000.0,54000.0,5700.0,54000.0
Emaar Palm Gardens,54000.0,54000.0,5500.0,54000.0
Umang Winter Hills,54000.0,54000.0,3200.0,54000.0
Puri Diplomatic Greens,54000.0,1500.0,1500.0,54000.0
Pioneer Park,54000.0,54000.0,700.0,54000.0
Bestech Park View Sanskruti,4300.0,54000.0,4300.0,54000.0

In [859]:
location_df.at["Oxirich Chintamanis", "Miracles Apollo Cradle Hospital"] = 2900.0
location_df.at["Indiabulls Enigma", "Miracles Apollo Cradle Hospital"] = 4800.0
location_df.at["Adani Brahma Samsara", "Miracles Apollo Cradle Hospital"] = 4500.0
location_df.at["DLF The Pinnacle", "Miracles Apollo Cradle Hospital"] = 800.0
location_df.at["Ireo Savannah", "Miracles Apollo Cradle Hospital"] = 1600.0
location_df.at["Puri Diplomatic Greens", "Miracles Apollo Cradle Hospital"] = 1500.0
location_df.at["Bestech Park View Sanskruti", "Miracles Apollo Cradle Hospital"] = 4300.0

In [863]:
location_df[location_df["NH-8"] +location_df["NH-8, IMT Manesar"]+location_df["National Highway 8"] < (3*54000)][["NH-8","NH-8, IMT Manesar","National Highway 8"]]

,NH-8,"NH-8, IMT Manesar",National Highway 8
PropertyName,,,
Signature Global City,5100.0,54000.0,54000.0
Signature Global City 37D Ph 2,9500.0,54000.0,54000.0
DLF The Crest,5000.0,54000.0,54000.0
Indiabulls Enigma,6500.0,54000.0,54000.0
Hero Homes,14900.0,54000.0,54000.0
M3M Skywalk,8100.0,54000.0,54000.0
JMS The Nation,7700.0,54000.0,54000.0
Suncity Avenue 76,15400.0,15400.0,54000.0
M3M Sierra 68,8700.0,8700.0,54000.0
Central Park Flower Valley Aqua Front Towers,5400.0,5400.0,54000.0
M3M Natura,6200.0,54000.0,6200.0
BPTP Fortuna,6400.0,6400.0,54000.0
Ireo Savannah,4500.0,54000.0,54000.0
Satya The Hermitage,7600.0,7600.0,54000.0

In [862]:
location_df.at["Suncity Avenue 76", "NH-8"] = 15400.0
location_df.at["M3M Sierra 68", "NH-8"] = 8700.0
location_df.at["Central Park Flower Valley Aqua Front Towers", "NH-8"] = 5400.0
location_df.at["M3M Natura", "NH-8"] = 6200.0
location_df.at["BPTP Fortuna", "NH-8"] = 6400.0
location_df.at["Satya The Hermitage", "NH-8"] = 7600.0

In [866]:
location_df[location_df["National Tennis Academy"] +location_df["National Tennis Academy Sector 98"] < (2*54000)][["National Tennis Academy","National Tennis Academy Sector 98"]]

,National Tennis Academy,National Tennis Academy Sector 98
PropertyName,,
Signature Global City 37D Ph 2,8700.0,8700.0
Hero Homes,11700.0,11700.0
JMS The Nation,5000.0,54000.0
M3M Sierra 68,7200.0,7200.0
Central Park Flower Valley Aqua Front Towers,9700.0,54000.0
Shree Vardhman Flora,4900.0,54000.0
M3M Heights,5800.0,54000.0
BPTP Fortuna,5300.0,5300.0
DLF The Pinnacle,10400.0,54000.0

In [865]:
location_df.at["Signature Global City 37D Ph 2", "National Tennis Academy"] = 8700.0
location_df.at["Hero Homes", "National Tennis Academy"] = 11700.0
location_df.at["M3M Sierra 68", "National Tennis Academy"] = 7200.0
location_df.at["BPTP Fortuna", "National Tennis Academy"] = 5300.0

In [867]:
location_df.drop(columns=["DPS","Fun N Food WaterPark","Holiday Inn Sector 90","Airport","Delhi International Airport","Miracles Apollo Hospital","Miracles Apollo Cradle","Miracles Apollo Cradle /Spectra Hospital","NH-8, IMT Manesar","National Highway 8","National Tennis Academy Sector 98"],inplace=True)

In [868]:
location_df.shape

(246, 577)

In [869]:

with open('location_df1.pkl', 'wb') as file:
    pickle.dump(location_df, file)